/* ---------------------------------------------------------------
   The beginner scaffolding that sits on top of every topic page.

   Four things per topic, all bilingual, all deliberately dumb:
     say   — what the thing is, with no Angular words in it
     like  — a real-world object it behaves like
     when  — the moment you would actually reach for it
     strip — the whole mechanism as three or four small pictures
     one   — the single sentence worth memorising

   Keys are the *base* slug (no number). Order and track live in
   the PLAN in build.mjs; this file only cares about the topic.
   --------------------------------------------------------------- */
export default {

'how-an-app-starts': {
  say:  {en:"Your entire app is <b>one HTML file with one empty tag in it</b>. Angular fills that tag in, then keeps it up to date forever.",
         ar:"التطبيق كله عبارة عن <b>ملف HTML واحد فيه تاج فاضي</b>. أنجولار بيملا التاج ده، وبعد كده بيفضل يحدّثه على طول."},
  like: {en:"A picture frame on a wall. The wall is <code>index.html</code>, the frame is <code>&lt;app-root&gt;</code>, and Angular is the person who keeps swapping the picture inside it — without ever taking the frame down.",
         ar:"برواز معلّق على الحيطة. الحيطة هي <code>index.html</code>، والبرواز هو <code>&lt;app-root&gt;</code>، وأنجولار هو اللي بيغيّر الصورة اللي جواه — من غير ما ينزّل البرواز نفسه."},
  when: {en:"Never directly. But every bug that starts with <b>nothing shows up at all</b> ends in this file, so read it once.",
         ar:"مش هتلمسه بإيدك أبداً. بس أي مشكلة بتبدأ بـ <b>مفيش أي حاجة ظاهرة</b> بتنتهي في الملف ده، فاقراه مرة."},
  one:  {en:"<code>index.html</code> is the only page you will ever have. Everything else is Angular putting things inside <code>&lt;app-root&gt;</code>.",
         ar:"<code>index.html</code> هو الصفحة الوحيدة اللي هتملكها. أي حاجة تانية هي أنجولار بيحط حاجات جوه <code>&lt;app-root&gt;</code>."},
  strip:[
    {i:'doc',    t:{en:"The browser gets one file",     ar:"المتصفح بياخد ملف واحد"},
                 p:{en:"<code>index.html</code> arrives almost empty — one <code>&lt;app-root&gt;</code> tag and one script tag. That is the whole page.", ar:"<code>index.html</code> بيوصل شبه فاضي — تاج <code>&lt;app-root&gt;</code> وتاج script. دي الصفحة كلها."}},
    {i:'bolt',   t:{en:"main.ts starts the engine",     ar:"main.ts بيشغّل الموتور"},
                 p:{en:"<code>bootstrapApplication(App)</code> hands Angular your root component and says: take it from here.", ar:"<code>bootstrapApplication(App)</code> بيسلّم أنجولار الـ component الرئيسي ويقوله: كمّل إنت."}},
    {i:'box',    t:{en:"The root component draws",      ar:"الـ component بيرسم"},
                 p:{en:"Angular reads the template, builds real DOM out of it, and drops it inside the empty tag.", ar:"أنجولار بيقرا الـ template، بيبني منه DOM حقيقي، وبيحطه جوه التاج الفاضي."}},
    {i:'refresh',t:{en:"Then it never reloads",         ar:"وبعد كده مفيش reload"},
                 p:{en:"No more page loads, ever. From now on Angular edits that DOM in place — that is what makes it feel instant.", ar:"مفيش تحميل صفحة تاني خالص. من هنا ورايح أنجولار بيعدّل الـ DOM في مكانه — وده اللي بيخليه سريع كده."}},
  ],
},

'cli-and-project-files': {
  say:  {en:"<code>ng</code> is a command that <b>writes the boring files for you</b> and runs your app while you work on it.",
         ar:"<code>ng</code> ده أمر بيكتبلك <b>الملفات المملة</b> وبيشغّل التطبيق وإنت شغال عليه."},
  like: {en:"A kitchen assistant. You say <em>component, product-card</em> and the prep work is already on the counter before you finish the sentence.",
         ar:"زي مساعد في المطبخ. تقوله <em>component اسمه product-card</em> وتلاقي التحضير خلص قبل ما تخلّص الجملة."},
  when: {en:"Every single time you need a new component, service or route. Typing these files by hand is how typos get in.",
         ar:"كل مرة محتاج component أو service أو route جديد. لما بتكتبهم بإيدك بتيجي الغلطات الإملائية."},
  one:  {en:"<code>ng generate</code> and <code>ng serve</code> are ninety percent of the CLI. Learn those two properly; the rest can wait.",
         ar:"<code>ng generate</code> و <code>ng serve</code> هما تسعين في المية من الـ CLI. اتقنهم الاتنين، والباقي يستنى."},
  strip:[
    {i:'folder', t:{en:"ng new makes the folder",  ar:"ng new بيعمل الفولدر"},
                 p:{en:"One command builds the whole project skeleton: config, dependencies, the first component.", ar:"أمر واحد بيبني هيكل المشروع كله: الإعدادات، المكتبات، وأول component."}},
    {i:'wand',   t:{en:"ng generate makes parts",  ar:"ng generate بيعمل القطع"},
                 p:{en:"Component, service, guard, pipe — correct file names, correct imports, correct place, every time.", ar:"component أو service أو guard أو pipe — بأسماء وimports ومكان صح في كل مرة."}},
    {i:'screen', t:{en:"ng serve watches you",     ar:"ng serve بيراقبك"},
                 p:{en:"Runs a dev server and rebuilds the second you save. Leave it running all day.", ar:"بيشغّل سيرفر تطوير وبيعيد البناء بمجرد ما تحفظ. سيبه شغال طول اليوم."}},
    {i:'ship',   t:{en:"ng build ships it",        ar:"ng build بيطلّعه"},
                 p:{en:"Produces the small, optimised files you actually put on a server.", ar:"بيطلّع الملفات الصغيرة المضغوطة اللي بتحطها فعلاً على السيرفر."}},
  ],
},

'components': {
  say:  {en:"A component is <b>one area of the screen</b>: a class that holds the data, an HTML file that draws it, and a CSS file that styles it.",
         ar:"الـ component هو <b>جزء واحد من الشاشة</b>: class شايل الداتا، وملف HTML بيرسمها، وملف CSS بينسّقها."},
  like: {en:"A Lego brick. It knows its own shape and colour, it does not care what is next to it, and you click it together with others to build a page.",
         ar:"زي تيلة ليجو. عارفة شكلها ولونها، ومش فارق معاها اللي جنبها، وبتركّبها مع غيرها عشان تبني صفحة."},
  when: {en:"Any time a piece of the page has its own data, or repeats, or is big enough that you scroll to find it.",
         ar:"أي جزء في الصفحة ليه داتا خاصة بيه، أو بيتكرر، أو كبير لدرجة إنك بتنزل تدوّر عليه."},
  one:  {en:"A component is a class + a template + a selector. The selector is the tag name other people write in <em>their</em> HTML to use yours.",
         ar:"الـ component = class + template + selector. الـ selector هو اسم التاج اللي الناس بتكتبه في الـ HTML بتاعهم عشان تستخدم بتاعك."},
  strip:[
    {i:'box',   t:{en:"A class holds the data", ar:"الـ class شايل الداتا"},
                p:{en:"Plain TypeScript. Properties for state, methods for behaviour. Nothing Angular-specific yet.", ar:"TypeScript عادي. properties للحالة، وmethods للسلوك. لسه مفيش حاجة أنجولار هنا."}},
    {i:'doc',   t:{en:"A template draws it",    ar:"الـ template بيرسمها"},
                p:{en:"HTML that can read the class: <code>{{ title }}</code> reaches straight into the property above.", ar:"HTML بيقدر يقرا الـ class: <code>{{ title }}</code> بيوصل للـ property اللي فوق على طول."}},
    {i:'wand',  t:{en:"@Component ties them",   ar:"@Component بيربطهم"},
                p:{en:"The decorator is the label that says: this class and that template belong together, under this tag name.", ar:"الديكوريتور هو اللافتة اللي بتقول: الـ class ده والـ template ده مع بعض، تحت اسم التاج ده."}},
    {i:'boxes', t:{en:"The selector places it", ar:"الـ selector بيحطه"},
                p:{en:"Write <code>&lt;app-product-card /&gt;</code> in a parent template and your component appears there.", ar:"اكتب <code>&lt;app-product-card /&gt;</code> في template الأب، وهتلاقي الـ component ظهر هناك."}},
  ],
},

'template-syntax': {
  say:  {en:"Template syntax is the <b>small set of extra symbols</b> you write inside HTML so Angular knows which bits to fill in.",
         ar:"الـ template syntax هي <b>شوية رموز زيادة</b> بتكتبها جوه الـ HTML عشان أنجولار يعرف الحتت اللي هيملاها."},
  like: {en:"Mail merge in a word processor. You write <em>Dear {{name}}</em> once, and the printer swaps in a real name on every letter.",
         ar:"زي الـ mail merge في الوورد. بتكتب <em>عزيزي {{name}}</em> مرة واحدة، والطابعة بتحط اسم حقيقي في كل جواب."},
  when: {en:"In every template you will ever write. This is the alphabet — everything later is spelling.",
         ar:"في كل template هتكتبه في حياتك. دي الأبجدية، وأي حاجة بعد كده هي مجرد تهجّي."},
  one:  {en:"<code>{{ }}</code> prints a value, <code>[ ]</code> sets a property, <code>( )</code> listens for an event. Everything else is built on those three.",
         ar:"<code>{{ }}</code> بتطبع قيمة، و<code>[ ]</code> بتظبط property، و<code>( )</code> بتسمع event. أي حاجة تانية مبنية على التلاتة دول."},
  strip:[
    {i:'doc',   t:{en:"Plain HTML stays plain", ar:"الـ HTML العادي زي ما هو"},
                p:{en:"Ninety percent of a template is ordinary HTML that Angular does not touch at all.", ar:"تسعين في المية من الـ template هو HTML عادي أنجولار مش بيلمسه خالص."}},
    {i:'target',t:{en:"{{ }} prints a value",   ar:"{{ }} بتطبع قيمة"},
                p:{en:"Interpolation. Whatever is inside is read from the class and turned into text.", ar:"الـ interpolation. اللي جوه بيتقرا من الـ class ويتحوّل لنص."}},
    {i:'arrow', t:{en:"[ ] pushes data in",     ar:"[ ] بتدخّل داتا"},
                p:{en:"<code>[disabled]=&quot;busy()&quot;</code> sets a real DOM property, not a string. Booleans stay booleans.", ar:"<code>[disabled]=&quot;busy()&quot;</code> بتظبط property حقيقي في الـ DOM، مش نص. الـ boolean بيفضل boolean."}},
    {i:'click', t:{en:"( ) catches events out", ar:"( ) بتمسك الأحداث"},
                p:{en:"<code>(click)=&quot;save()&quot;</code> runs your method. <code>$event</code> is the real browser event.", ar:"<code>(click)=&quot;save()&quot;</code> بتشغّل الميثود بتاعتك. و<code>$event</code> هو الحدث الحقيقي من المتصفح."}},
  ],
},

'data-binding': {
  say:  {en:"Binding is a <b>live wire</b> between your class and your HTML, so you never touch the DOM with your own hands.",
         ar:"الـ binding هو <b>سلك حي</b> بين الـ class والـ HTML، عشان متلمسش الـ DOM بإيدك أبداً."},
  like: {en:"A thermostat taped to a thermometer. Change one and the other moves by itself. Nobody walks across the room to adjust anything.",
         ar:"ترموستات ملزوق في ترمومتر. تغيّر واحد يتحرّك التاني لوحده. محدش بيقوم من مكانه يظبط حاجة."},
  when: {en:"Every input box, every disabled button, every class that changes with state. Which is all day, every day.",
         ar:"كل خانة إدخال، وكل زرار بيتقفل، وكل class بيتغيّر مع الحالة. يعني طول اليوم."},
  one:  {en:"Data flows down with <code>[ ]</code>, events fly up with <code>( )</code>, and <code>[( )]</code> is only ever both at once.",
         ar:"الداتا بتنزل بـ <code>[ ]</code>، والأحداث بتطلع بـ <code>( )</code>، و<code>[( )]</code> مش أكتر من الاتنين مع بعض."},
  strip:[
    {i:'arrow', t:{en:"[prop] goes down",  ar:"[prop] بتنزل"},
                p:{en:"Class to DOM. Angular re-runs the expression whenever the value it reads changes.", ar:"من الـ class للـ DOM. أنجولار بيعيد حساب التعبير كل ما القيمة تتغيّر."}},
    {i:'click', t:{en:"(event) goes up",   ar:"(event) بتطلع"},
                p:{en:"DOM to class. The browser fires, your method runs, state changes, the screen catches up.", ar:"من الـ DOM للـ class. المتصفح بيطلق الحدث، الميثود بتشتغل، الحالة بتتغيّر، والشاشة بتلحق."}},
    {i:'swap',  t:{en:"[( )] is both",     ar:"[( )] الاتنين"},
                p:{en:"Banana in a box. <code>[(ngModel)]</code> is literally <code>[ngModel]</code> plus <code>(ngModelChange)</code>.", ar:"الموزة في الصندوق. <code>[(ngModel)]</code> حرفياً هي <code>[ngModel]</code> زائد <code>(ngModelChange)</code>."}},
    {i:'warn',  t:{en:"attr. for attributes", ar:"attr. للـ attributes"},
                p:{en:"Some things (<code>colspan</code>, <code>aria-*</code>) are HTML attributes, not DOM properties. Those need <code>[attr.x]</code>.", ar:"في حاجات زي <code>colspan</code> و<code>aria-*</code> دي attributes مش properties، فمحتاجة <code>[attr.x]</code>."}},
  ],
},

'signals': {
  say:  {en:"A signal is <b>a box with a value in it</b> that tells Angular the moment the value changes.",
         ar:"الـ signal هو <b>صندوق جواه قيمة</b>، وبيقول لأنجولار في نفس اللحظة اللي القيمة بتتغيّر فيها."},
  like: {en:"A doorbell on a box. Anyone who cares wires themselves to the bell, instead of opening the box every five seconds to check whether anything changed.",
         ar:"جرس على الصندوق. اللي مهتم بيوصّل نفسه بالجرس، بدل ما يفتح الصندوق كل خمس ثواني يشوف اتغيّر ولا لأ."},
  when: {en:"For any value that changes and is shown on screen. In a modern Angular app, that is nearly all of them.",
         ar:"لأي قيمة بتتغيّر وبتتعرض على الشاشة. في أنجولار الحديث، دي تقريباً كل القيم."},
  one:  {en:"Read it with <code>count()</code>, change it with <code>count.set(5)</code>. The brackets are not decoration — without them you get the box, not the value.",
         ar:"اقراه بـ <code>count()</code>، وغيّره بـ <code>count.set(5)</code>. الأقواس مش زينة — من غيرها بتاخد الصندوق نفسه مش القيمة."},
  strip:[
    {i:'box',    t:{en:"signal() makes the box", ar:"signal() بتعمل الصندوق"},
                 p:{en:"<code>const count = signal(0)</code>. One value, one place, one owner.", ar:"<code>const count = signal(0)</code>. قيمة واحدة، مكان واحد، مالك واحد."}},
    {i:'eye',    t:{en:"Reading registers you", ar:"القراية بتسجّلك"},
                 p:{en:"Calling <code>count()</code> inside a template quietly writes your name on the bell.", ar:"لما بتنادي <code>count()</code> جوه template، اسمك بيتكتب على الجرس من غير ما تحس."}},
    {i:'bell',   t:{en:"set() rings the bell",  ar:"set() بتدق الجرس"},
                 p:{en:"<code>set</code> replaces the value, <code>update</code> changes it based on the old one.", ar:"<code>set</code> بتستبدل القيمة، و<code>update</code> بتغيّرها بناءً على القديمة."}},
    {i:'refresh',t:{en:"Only listeners redraw", ar:"اللي سامع بس بيترسم"},
                 p:{en:"Not the page, not the component — just the exact pieces that read that signal.", ar:"مش الصفحة، ولا الـ component، الحتت اللي قرت الـ signal دي بس."}},
  ],
},

'control-flow': {
  say:  {en:"<code>@if</code>, <code>@for</code> and <code>@switch</code> are how you <b>show, hide and repeat</b> things in a template.",
         ar:"<code>@if</code> و<code>@for</code> و<code>@switch</code> هما إزاي <b>تظهر وتخفي وتكرّر</b> حاجات في الـ template."},
  like: {en:"Instructions to someone laying out a newspaper: <em>print this box only if there is a photo, and repeat this row once per story.</em>",
         ar:"تعليمات لواحد بيرصّ جريدة: <em>اطبع الصندوق ده بس لو في صورة، وكرّر الصف ده مرة لكل خبر.</em>"},
  when: {en:"Lists, empty states, loading spinners, tabs, permission checks. Constantly.",
         ar:"القوايم، وحالات الفراغ، وشاشات التحميل، والتابات، وفحص الصلاحيات. باستمرار."},
  one:  {en:"<code>@for</code> needs a <code>track</code>. Get it wrong and your whole list is destroyed and rebuilt on every keystroke.",
         ar:"<code>@for</code> محتاجة <code>track</code>. لو غلط، القايمة كلها بتتهد وتتبني من أول وجديد مع كل ضغطة زرار."},
  strip:[
    {i:'split', t:{en:"@if picks a branch", ar:"@if بتختار طريق"},
                p:{en:"True renders the block, false removes it from the DOM entirely — not just hides it.", ar:"لو صح بيرسم البلوك، ولو غلط بيشيله من الـ DOM خالص — مش بيخبّيه بس."}},
    {i:'list',  t:{en:"@for repeats a block", ar:"@for بتكرّر بلوك"},
                p:{en:"One copy per item, with <code>$index</code>, <code>$first</code> and <code>$last</code> handed to you free.", ar:"نسخة لكل عنصر، ومعاك <code>$index</code> و<code>$first</code> و<code>$last</code> ببلاش."}},
    {i:'target',t:{en:"track names each row", ar:"track بتسمّي كل صف"},
                p:{en:"It tells Angular which DOM row belongs to which item, so it moves rows instead of rebuilding them.", ar:"بتقول لأنجولار كل صف في الـ DOM بتاع أنهي عنصر، فيحرّك الصفوف بدل ما يعيد بناها."}},
    {i:'flag',  t:{en:"@empty covers zero",  ar:"@empty بتغطي الفاضي"},
                p:{en:"Attached right to the loop, so the empty state can never drift out of sync with the list.", ar:"ملزوقة باللوب نفسها، فحالة الفراغ مستحيل تختلف عن القايمة."}},
  ],
},

'built-in-directives': {
  say:  {en:"<code>ngClass</code> and <code>ngStyle</code> let you <b>turn CSS classes and styles on and off</b> from your data.",
         ar:"<code>ngClass</code> و<code>ngStyle</code> بيخلوك <b>تفتح وتقفل classes وستايلات</b> من الداتا بتاعتك."},
  like: {en:"A panel of light switches. Your data decides which switches are up and which are down.",
         ar:"لوحة مفاتيح نور. الداتا بتاعتك هي اللي بتقرر أنهي مفتاح فاتح وأنهي طافي."},
  when: {en:"Active tabs, invalid fields, sold-out badges — anything that changes appearance based on a condition.",
         ar:"التاب المفتوح، والخانة الغلط، وعلامة (خلص من المخزن) — أي حاجة شكلها بيتغيّر حسب شرط."},
  one:  {en:"For a single class, prefer <code>[class.active]</code>. Reach for <code>ngClass</code> only when several classes toggle together.",
         ar:"لو class واحد، استعمل <code>[class.active]</code>. ماتلجأش لـ <code>ngClass</code> غير لما كذا class يتغيّروا مع بعض."},
  strip:[
    {i:'swap',   t:{en:"[class.x] toggles one", ar:"[class.x] بتقلب واحد"},
                 p:{en:"Truthy adds the class, falsy removes it. Nothing else on the element is disturbed.", ar:"لو صح بيضيف الـ class، ولو غلط بيشيله. ومش بيلخبط أي حاجة تانية في العنصر."}},
    {i:'layers', t:{en:"ngClass toggles many", ar:"ngClass بتقلب كتير"},
                 p:{en:"Takes an object, an array or a string. The object form is the readable one.", ar:"بتاخد object أو array أو string. صيغة الـ object هي أوضحهم."}},
    {i:'wand',   t:{en:"[style.width.px]",     ar:"[style.width.px]"},
                 p:{en:"The unit goes in the binding name, so you pass a plain number and never build strings.", ar:"الوحدة بتتكتب في اسم الـ binding، فبتبعت رقم عادي ومش بتلزق نصوص."}},
    {i:'warn',   t:{en:"Inline styles win",    ar:"الستايل المباشر بيكسب"},
                 p:{en:"<code>ngStyle</code> writes inline styles, which beat your stylesheet. Use it sparingly.", ar:"<code>ngStyle</code> بيكتب inline styles، ودي بتغلب ملف الـ CSS بتاعك. استعملها بحساب."}},
  ],
},

'built-in-pipes': {
  say:  {en:"A pipe is a <b>small formatter</b> you put after a value with a <code>|</code> to change how it looks — never what it is.",
         ar:"الـ pipe هو <b>منسّق صغير</b> بتحطه بعد القيمة بـ <code>|</code> عشان يغيّر شكلها — مش قيمتها."},
  like: {en:"A filter on a photo. The photo on your phone is untouched; only what you are looking at changed.",
         ar:"فلتر على صورة. الصورة اللي في موبايلك زي ما هي؛ اللي إنت بتبصله هو اللي اتغيّر."},
  when: {en:"Dates, money, percentages, uppercase — and <code>async</code> for values that arrive later.",
         ar:"التواريخ، والفلوس، والنِسب، والحروف الكبيرة — و<code>async</code> للقيم اللي بتوصل متأخر."},
  one:  {en:"Pipes format for display only. Never store the piped result back into your data.",
         ar:"الـ pipes بتنسّق للعرض بس. متخزّنش النتيجة المنسّقة في الداتا بتاعتك أبداً."},
  strip:[
    {i:'clock', t:{en:"date formats time",   ar:"date بتنسّق الوقت"},
                p:{en:"<code>{{ d | date:'short' }}</code>. It respects the user's locale, which you should not hand-code.", ar:"<code>{{ d | date:'short' }}</code>. بتحترم لغة المستخدم، وده حاجة ماينفعش تكتبها بإيدك."}},
    {i:'scale', t:{en:"currency and number", ar:"currency و number"},
                p:{en:"Thousands separators, decimal places and currency symbols, all handled for you.", ar:"فواصل الآلاف والكسور ورموز العملة، كلها متظبطة من غيرك."}},
    {i:'filter',t:{en:"the text pipes",      ar:"pipes النصوص"},
                p:{en:"<code>uppercase</code>, <code>titlecase</code>, <code>slice</code>, <code>json</code> — the last one is a debugging friend.", ar:"<code>uppercase</code> و<code>titlecase</code> و<code>slice</code> و<code>json</code> — الأخيرة دي صاحبك في الـ debugging."}},
    {i:'plug',  t:{en:"async unwraps",       ar:"async بتفك التغليف"},
                p:{en:"Subscribes for you and unsubscribes when the component dies. No leak, no boilerplate.", ar:"بتعمل subscribe بدالك وبتلغيه لما الـ component يموت. مفيش تسريب ولا كود زيادة."}},
  ],
},

'inputs-outputs': {
  say:  {en:"<code>input()</code> takes data <b>from the parent</b>, <code>output()</code> sends events <b>back up</b>, and <code>model()</code> does both.",
         ar:"<code>input()</code> بتاخد داتا <b>من الأب</b>، و<code>output()</code> بتبعت أحداث <b>لفوق</b>، و<code>model()</code> بتعمل الاتنين."},
  like: {en:"A vending machine. Coins go in, a snack comes out. It never reaches into your pocket, and you never reach into its shelves.",
         ar:"ماكينة بيع. الفلوس بتدخل، والحاجة بتخرج. هي عمرها ما بتحط إيدها في جيبك، وإنت عمرك ما بتحط إيدك في رفوفها."},
  when: {en:"The moment you have two components and one needs to tell the other something.",
         ar:"أول ما يبقى عندك اتنين components وواحد محتاج يقول للتاني حاجة."},
  one:  {en:"Parent to child is an input. Child to parent is an output. If you need something else, you probably want a service.",
         ar:"من الأب للابن = input. من الابن للأب = output. لو محتاج حاجة تانية، غالباً إنت عايز service."},
  strip:[
    {i:'arrow', t:{en:"input() receives",  ar:"input() بتستقبل"},
                p:{en:"It is a signal, so <code>computed</code> and the template react to it automatically.", ar:"هي signal، يعني <code>computed</code> والـ template بيتفاعلوا معاها لوحدهم."}},
    {i:'bell',  t:{en:"output() emits",    ar:"output() بتطلق"},
                p:{en:"<code>saved.emit(value)</code>. The parent listens with <code>(saved)=&quot;...&quot;</code> like any DOM event.", ar:"<code>saved.emit(value)</code>. الأب بيسمع بـ <code>(saved)=&quot;...&quot;</code> زي أي حدث عادي."}},
    {i:'swap',  t:{en:"model() is two-way", ar:"model() في الاتجاهين"},
                p:{en:"One declaration gives the parent <code>[(value)]</code>. Use it for form-like controls only.", ar:"تعريف واحد بيدّي الأب <code>[(value)]</code>. استعملها بس في حاجات شبه الفورم."}},
    {i:'shield',t:{en:"required is enforced", ar:"required بتتفرض"},
                p:{en:"<code>input.required&lt;T&gt;()</code> makes forgetting it a compile error, not a runtime surprise.", ar:"<code>input.required&lt;T&gt;()</code> بتخلي نسيانها غلطة وقت البناء، مش مفاجأة وقت التشغيل."}},
  ],
},

'services-di': {
  say:  {en:"A service is <b>a plain class holding shared data or logic</b>, and Angular hands the same one to everybody who asks.",
         ar:"الـ service هو <b>class عادي شايل داتا أو منطق مشترك</b>، وأنجولار بيدّي نفس النسخة لأي حد يطلبها."},
  like: {en:"The office coffee machine. Nobody buys their own; everyone walks to the one in the corner. One machine, one pot of coffee, one truth.",
         ar:"ماكينة القهوة في الشركة. محدش بيجيب واحدة لنفسه؛ كله بيروح للي في الركن. ماكينة واحدة، قهوة واحدة، حقيقة واحدة."},
  when: {en:"Two components need the same fact, or you need to talk to an API, or a value must outlive one screen.",
         ar:"لما اتنين components يحتاجوا نفس المعلومة، أو تحتاج تكلّم API، أو قيمة لازم تعيش أطول من شاشة واحدة."},
  one:  {en:"<code>inject(CartService)</code> gives every component the <em>exact same instance</em> — as long as it is <code>providedIn: 'root'</code>.",
         ar:"<code>inject(CartService)</code> بتدّي كل component <em>نفس النسخة بالظبط</em> — طالما هي <code>providedIn: 'root'</code>."},
  strip:[
    {i:'box',  t:{en:"A class with a label", ar:"class عليه لافتة"},
               p:{en:"<code>@Injectable({ providedIn: 'root' })</code> — that is the entire registration.", ar:"<code>@Injectable({ providedIn: 'root' })</code> — دي عملية التسجيل كلها."}},
    {i:'net',  t:{en:"Angular keeps one",    ar:"أنجولار بيمسك نسخة"},
               p:{en:"It builds the instance the first time somebody asks, then keeps handing that one out.", ar:"بيعمل النسخة أول ما حد يطلبها، وبعدين بيفضل يدّي نفس النسخة."}},
    {i:'plug', t:{en:"inject() hands it over", ar:"inject() بتسلّمها"},
               p:{en:"A field, not a constructor argument. Shorter, and it works in functions too.", ar:"property مش parameter في الـ constructor. أقصر، وبتشتغل جوه الدوال كمان."}},
    {i:'user', t:{en:"Everyone shares",      ar:"الكل بيتشارك"},
               p:{en:"Change it in one component and every other component already sees the change.", ar:"غيّرها من component، وكل الـ components التانية شايفة التغيير على طول."}},
  ],
},

'lifecycle': {
  say:  {en:"Lifecycle hooks are <b>methods Angular calls for you</b> at fixed moments: created, drawn, updated, destroyed.",
         ar:"الـ lifecycle hooks هي <b>ميثودز أنجولار بيناديها بدالك</b> في لحظات ثابتة: اتعمل، اترسم، اتحدّث، اتمسح."},
  like: {en:"A shop's opening and closing routine. Unlock at nine, put the sign out, cash up at six, lock the door. Same order, every single day.",
         ar:"روتين فتح وقفل المحل. تفتح الساعة تسعة، تحط اللافتة، تحسب الساعة ستة، تقفل الباب. نفس الترتيب كل يوم."},
  when: {en:"Starting a timer, opening a socket, measuring an element — and above all, cleaning those up again.",
         ar:"لما تبدأ تايمر، أو تفتح socket، أو تقيس عنصر — وأهم من ده كله، لما تنضّفهم بعد كده."},
  one:  {en:"<code>ngOnInit</code> starts things, <code>ngOnDestroy</code> stops them. Skipping the second one is exactly what a memory leak is.",
         ar:"<code>ngOnInit</code> بتبدأ الحاجات، و<code>ngOnDestroy</code> بتوقّفها. إنك تنسى التانية ده بالظبط معنى تسريب الذاكرة."},
  strip:[
    {i:'bolt',  t:{en:"constructor — too early", ar:"constructor — بدري أوي"},
                p:{en:"Inputs are not set yet. Only use it for <code>inject()</code> and cheap field setup.", ar:"الـ inputs لسه ماتحطتش. استعمله بس للـ <code>inject()</code> والإعدادات البسيطة."}},
    {i:'check', t:{en:"ngOnInit — inputs ready", ar:"ngOnInit — الـ inputs جاهزة"},
                p:{en:"Runs once, after the first set of inputs. This is where fetching belongs.", ar:"بتشتغل مرة واحدة بعد أول inputs. هنا مكان جلب الداتا."}},
    {i:'eye',   t:{en:"ngAfterViewInit — DOM exists", ar:"ngAfterViewInit — الـ DOM موجود"},
                p:{en:"The only safe place to measure or reach a child element. Not before.", ar:"المكان الوحيد الآمن إنك تقيس أو توصل لعنصر ابن. مش قبل كده."}},
    {i:'cross', t:{en:"ngOnDestroy — clean up",  ar:"ngOnDestroy — نضّف"},
                p:{en:"Clear timers, close sockets, unsubscribe. Or use <code>DestroyRef</code> and let Angular do it.", ar:"امسح التايمرات، اقفل الـ sockets، الغِ الاشتراكات. أو استعمل <code>DestroyRef</code> وسيب أنجولار يعملها."}},
  ],
},

'basic-routing': {
  say:  {en:"The router <b>swaps components in and out of a hole</b> in your page whenever the URL changes.",
         ar:"الراوتر <b>بيبدّل الـ components جوه فتحة</b> في صفحتك كل ما الـ URL يتغيّر."},
  like: {en:"A picture frame with a stack of photos behind it. Changing the URL slides a different photo into the same frame — the frame never moves.",
         ar:"برواز وراه كومة صور. لما تغيّر الـ URL، صورة تانية بتدخل في نفس البرواز — والبرواز نفسه مابيتحركش."},
  when: {en:"As soon as your app has more than one screen. Which is basically immediately.",
         ar:"أول ما يبقى في تطبيقك أكتر من شاشة. يعني فوراً تقريباً."},
  one:  {en:"<code>routerLink</code> changes the page without reloading. <code>href</code> reloads everything and wipes every signal you had.",
         ar:"<code>routerLink</code> بتغيّر الصفحة من غير reload. و<code>href</code> بتعيد تحميل كل حاجة وبتمسح كل signal كان عندك."},
  strip:[
    {i:'list',  t:{en:"routes is just an array", ar:"routes مجرد array"},
                p:{en:"A list of <code>{ path, component }</code> objects. Plain data you can log and read.", ar:"لستة من <code>{ path, component }</code>. داتا عادية تقدر تطبعها وتقراها."}},
    {i:'route', t:{en:"routerLink changes the URL", ar:"routerLink بتغيّر الـ URL"},
                p:{en:"On an anchor tag. The browser does not reload; the router just notices.", ar:"على تاج anchor. المتصفح مابيعملش reload؛ الراوتر بس بياخد باله."}},
    {i:'box',   t:{en:"router-outlet is the hole", ar:"router-outlet هي الفتحة"},
                p:{en:"Whatever route matched gets rendered exactly here. Everything around it stays put.", ar:"الـ route اللي طابق بيترسم هنا بالظبط. وكل اللي حواليه بيفضل مكانه."}},
    {i:'warn',  t:{en:"** must be last",         ar:"** لازم تكون آخر واحدة"},
                p:{en:"The wildcard route matches everything, so anything after it is unreachable.", ar:"الـ wildcard بتطابق أي حاجة، فأي حاجة بعدها مش هتتنادى أبداً."}},
  ],
},

'template-driven-forms': {
  say:  {en:"You write <b>plain inputs with <code>ngModel</code></b> and Angular quietly builds the form object behind your back.",
         ar:"إنت بتكتب <b>خانات عادية فيها <code>ngModel</code></b> وأنجولار بيبني الفورم ورا ضهرك من غير ما تحس."},
  like: {en:"A paper form with carbon copy underneath. You write on the top sheet; the copy fills itself in.",
         ar:"ورقة فيها كربون تحتها. إنت بتكتب فوق، والنسخة بتتملي لوحدها."},
  when: {en:"Small forms — a login box, a search filter, a settings toggle. Nothing with dynamic fields.",
         ar:"الفورمات الصغيرة — تسجيل دخول، فلتر بحث، إعداد. مش أي حاجة فيها خانات بتتغيّر."},
  one:  {en:"Template-driven is fine until the form gets clever. Dynamic fields or cross-field rules mean it is time for reactive forms.",
         ar:"الطريقة دي كويسة لحد ما الفورم يبقى معقّد. خانات ديناميكية أو قواعد بين الخانات = وقت الـ reactive forms."},
  strip:[
    {i:'form',  t:{en:"ngModel on each input", ar:"ngModel على كل خانة"},
                p:{en:"Plus a <code>name</code> attribute — without it Angular cannot register the control.", ar:"وكمان <code>name</code> — من غيرها أنجولار مش هيقدر يسجّل الخانة."}},
    {i:'eye',   t:{en:"Angular watches state", ar:"أنجولار بيراقب الحالة"},
                p:{en:"<code>touched</code>, <code>dirty</code>, <code>valid</code> — all tracked for you, free.", ar:"<code>touched</code> و<code>dirty</code> و<code>valid</code> — كلها متتبّعة بدالك، ببلاش."}},
    {i:'check', t:{en:"Validators are attributes", ar:"الفاليديشن attributes"},
                p:{en:"<code>required</code>, <code>minlength</code>, <code>email</code> — the same words you already know from HTML.", ar:"<code>required</code> و<code>minlength</code> و<code>email</code> — نفس الكلمات اللي إنت عارفها من HTML."}},
    {i:'warn',  t:{en:"It outgrows fast",      ar:"بيكبر عليها بسرعة"},
                p:{en:"No types, no easy programmatic changes, awkward tests. Know when to move on.", ar:"مفيش أنواع، ومش سهل تغيّرها بالكود، والاختبار متعب. اعرف إمتى تسيبها."}},
  ],
},

'http-basics': {
  say:  {en:"<code>HttpClient</code> is <b>how your app asks a server for data</b>, or sends data to it.",
         ar:"<code>HttpClient</code> هو <b>إزاي تطبيقك يطلب داتا من السيرفر</b>، أو يبعتله داتا."},
  like: {en:"Ordering food by phone. You call, you ask, you hang up, and the food arrives later. You do not stand in the kitchen waiting for it.",
         ar:"لما تطلب أكل بالتليفون. بتتصل، وتطلب، وتقفل، والأكل بيجي بعدين. مش بتقف في المطبخ مستني."},
  when: {en:"Any time the data lives on a server, which is nearly always.",
         ar:"أي وقت الداتا بتكون على سيرفر، وده تقريباً دايماً."},
  one:  {en:"An <code>HttpClient</code> call does <b>nothing at all</b> until something subscribes. No subscribe, no request.",
         ar:"نداء <code>HttpClient</code> <b>مابيعملش أي حاجة</b> لحد ما حد يعمل subscribe. مفيش subscribe، مفيش طلب."},
  strip:[
    {i:'plug',  t:{en:"inject(HttpClient)",   ar:"inject(HttpClient)"},
                p:{en:"One line, once, and only after <code>provideHttpClient()</code> is in your app config.", ar:"سطر واحد، مرة واحدة، وبس بعد ما تحط <code>provideHttpClient()</code> في إعدادات التطبيق."}},
    {i:'arrow', t:{en:"get() returns a recipe", ar:"get() بترجّع وصفة"},
                p:{en:"Not the data — an Observable, which is a description of how to fetch it.", ar:"مش الداتا — بترجّع Observable، وده وصف لطريقة الجلب مش الجلب نفسه."}},
    {i:'clock', t:{en:"subscribe fires it",   ar:"subscribe بتشغّلها"},
                p:{en:"Now the request leaves your machine. Subscribe twice, send two requests.", ar:"دلوقتي الطلب بيخرج من جهازك. لو عملت subscribe مرتين، هتبعت طلبين."}},
    {i:'check', t:{en:"httpResource is easier", ar:"httpResource أسهل"},
                p:{en:"Give it a URL, get signals for value, loading and error. No subscribe to forget.", ar:"إداله URL، وياخد signals للقيمة والتحميل والخطأ. مفيش subscribe تنساه."}},
  ],
},

'forms': {
  say:  {en:"Reactive forms mean you <b>build the form in TypeScript first</b>, then point the HTML at it — instead of the other way round.",
         ar:"الـ reactive forms معناها إنك <b>تبني الفورم في TypeScript الأول</b>، وبعدين توجّه الـ HTML عليه — مش العكس."},
  like: {en:"A spreadsheet next to a paper form. The spreadsheet is the real thing; the paper is just a view of it that you can hand to someone.",
         ar:"شيت إكسيل جنب ورقة فورم. الشيت هو الحقيقة، والورقة مجرد عرض ليه تقدر تدّيه لحد."},
  when: {en:"Anything with dynamic fields, cross-field rules, or a test you actually want to write.",
         ar:"أي حاجة فيها خانات ديناميكية، أو قواعد بين الخانات، أو اختبار عايز تكتبه فعلاً."},
  one:  {en:"Use <code>nonNullable</code> or your <code>reset()</code> quietly turns every value into <code>null</code> and every type into a lie.",
         ar:"استعمل <code>nonNullable</code> وإلا الـ <code>reset()</code> هتحوّل كل القيم لـ <code>null</code> من غير ما تحس، وكل الأنواع تبقى كدب."},
  strip:[
    {i:'form',  t:{en:"FormGroup is an object", ar:"FormGroup عبارة عن object"},
                p:{en:"A named bag of controls. Nested groups mirror nested data exactly.", ar:"شنطة فيها خانات بأسماء. الـ groups المتداخلة بتطابق الداتا المتداخلة بالظبط."}},
    {i:'plug',  t:{en:"formControlName connects", ar:"formControlName بتوصّل"},
                p:{en:"The HTML never owns the value; it only points at a control that already exists.", ar:"الـ HTML عمره ما بيملك القيمة؛ هو بس بيشاور على خانة موجودة أصلاً."}},
    {i:'check', t:{en:"Validators are functions", ar:"الفاليديتورز دوال"},
                p:{en:"A function in, an error object or <code>null</code> out. You can write your own in four lines.", ar:"دالة داخلة، وobject فيه الغلط أو <code>null</code> خارج. تقدر تكتب واحدة في أربع سطور."}},
    {i:'scale', t:{en:"Cross-field rules go on the group", ar:"قواعد الخانات على الـ group"},
                p:{en:"Password vs confirm-password is a group validator, never a control validator.", ar:"مقارنة الباسورد بتأكيدها validator على الـ group، مش على الخانة."}},
  ],
},

'directives-and-pipes': {
  say:  {en:"A directive is <b>behaviour you can stick onto any element</b>. A pipe is a formatter you can reuse anywhere.",
         ar:"الـ directive هو <b>سلوك بتلزقه على أي عنصر</b>. والـ pipe منسّق تقدر تستعمله في أي مكان."},
  like: {en:"A directive is a bumper sticker with a rule on it. A pipe is a rubber stamp. Neither one owns the car or the paper.",
         ar:"الـ directive زي ستيكر عليه قاعدة بتلزقه على العربية. والـ pipe زي ختم. ولا واحد فيهم بيملك العربية ولا الورقة."},
  when: {en:"When the same behaviour or the same formatting shows up in a third component, stop copying and extract it.",
         ar:"لما نفس السلوك أو نفس التنسيق يظهر في تالت component، بطّل نسخ ولزق واعمله لوحده."},
  one:  {en:"A pure pipe runs only when its input changes. Marking one <code>pure: false</code> makes it run on every check — that is almost always a mistake.",
         ar:"الـ pure pipe بيشتغل بس لما مدخلاته تتغيّر. لما تخليه <code>pure: false</code> بيشتغل مع كل فحص — وده غلط في أغلب الحالات."},
  strip:[
    {i:'wand',   t:{en:"Attribute directive",  ar:"attribute directive"},
                 p:{en:"Adds behaviour to an existing element: a highlight, a tooltip, a click-outside listener.", ar:"بيضيف سلوك لعنصر موجود: تظليل، أو تلميح، أو استماع للضغط بره."}},
    {i:'boxes',  t:{en:"Structural directive", ar:"structural directive"},
                 p:{en:"Adds or removes elements. Rarer now that <code>@if</code> and <code>@for</code> exist built in.", ar:"بيضيف أو بيشيل عناصر. بقت أقل استخداماً بعد ما بقى في <code>@if</code> و<code>@for</code> جاهزين."}},
    {i:'filter', t:{en:"A pipe is one method", ar:"الـ pipe ميثود واحدة"},
                 p:{en:"<code>transform(value, ...args)</code>. That is genuinely the whole interface.", ar:"<code>transform(value, ...args)</code>. دي الواجهة كلها بجد."}},
    {i:'bolt',   t:{en:"Pure means cached",    ar:"pure يعني متخزّن"},
                 p:{en:"Same input, same output, no re-run. Impure pipes throw that away.", ar:"نفس المدخل، نفس المخرج، من غير إعادة تشغيل. الـ impure بترمي ده كله."}},
  ],
},

'component-styles': {
  say:  {en:"Your component's CSS is <b>locked inside that component</b>. It does not leak out, and it does not reach in.",
         ar:"الـ CSS بتاع الـ component <b>مقفول جواه</b>. مش بيتسرّب لبره، ومش بيوصل لجوه."},
  like: {en:"A hotel room. You can repaint your own room freely, and it never changes the room next door — that is the point of the walls.",
         ar:"أوضة في فندق. تقدر تدهن أوضتك زي ما إنت عايز، ومش هيتغيّر حاجة في الأوضة اللي جنبك — ودي فايدة الحيطان."},
  when: {en:"Every time you write CSS. And especially the first time you shout <em>why is my style not applying?</em>",
         ar:"في كل مرة تكتب CSS. وخصوصاً أول مرة تزعّق <em>ليه الستايل مش شغال؟</em>"},
  one:  {en:"Angular adds a hidden attribute to your elements and rewrites your selectors to match it. That is the whole trick.",
         ar:"أنجولار بيضيف attribute مخفي لعناصرك وبيعيد كتابة الـ selectors عشان تطابقه. دي الحيلة كلها."},
  strip:[
    {i:'lock',   t:{en:"Emulated by default",  ar:"Emulated افتراضياً"},
                 p:{en:"Not real Shadow DOM — a rewritten selector. Cheaper, and DevTools stays readable.", ar:"مش Shadow DOM حقيقي — selector متعاد كتابته. أرخص، والـ DevTools بيفضل مقروء."}},
    {i:'shield', t:{en:"Children are protected", ar:"الأبناء محميين"},
                 p:{en:"Your CSS stops at the child's tag. Its insides belong to it, not to you.", ar:"الـ CSS بتاعك بيقف عند تاج الابن. جواه ملكه هو، مش ملكك."}},
    {i:'key',    t:{en:"::ng-deep breaks in",  ar:"::ng-deep بتخترق"},
                 p:{en:"It works, it is deprecated, and it is global. Always pair it with <code>:host</code>.", ar:"بتشتغل، وبتتشال قريب، وعامة على المشروع كله. دايماً حطها مع <code>:host</code>."}},
    {i:'wand',   t:{en:"Custom properties pass", ar:"الـ custom properties بتعدّي"},
                 p:{en:"CSS variables cross the boundary by design. This is the clean way to theme a child.", ar:"متغيرات الـ CSS بتعدّي الحدود بتصميمها. دي الطريقة النضيفة إنك تنسّق ابن."}},
  ],
},

'content-projection': {
  say:  {en:"<code>&lt;ng-content&gt;</code> is <b>a hole you leave in your component</b> so the parent can drop its own markup into it.",
         ar:"<code>&lt;ng-content&gt;</code> هي <b>فتحة بتسيبها في الـ component</b> عشان الأب يحط فيها الـ markup بتاعه."},
  like: {en:"A picture frame you sell empty. You made the frame; the buyer decides what photo goes in it.",
         ar:"برواز بتبيعه فاضي. إنت عملت البرواز، والزبون هو اللي بيقرر الصورة اللي هتتحط فيه."},
  when: {en:"Cards, dialogs, panels, layouts — any component whose <em>shape</em> is fixed but whose <em>contents</em> vary.",
         ar:"الكروت والديالوجات واللوحات والتخطيطات — أي component <em>شكله</em> ثابت و<em>محتواه</em> بيتغيّر."},
  one:  {en:"Projected content belongs to the <b>parent</b>, not to you. Its bindings, its styles and its lifecycle are all the parent's.",
         ar:"المحتوى المُمرّر ملك <b>الأب</b>، مش ملكك. الـ bindings والستايلات ودورة الحياة كلها بتاعته."},
  strip:[
    {i:'box',    t:{en:"Leave a hole",       ar:"سيب فتحة"},
                 p:{en:"One bare <code>&lt;ng-content /&gt;</code> catches everything the parent wrote inside your tag.", ar:"<code>&lt;ng-content /&gt;</code> واحدة بتمسك كل اللي الأب كتبه جوه التاج بتاعك."}},
    {i:'split',  t:{en:"Or several, by selector", ar:"أو كذا واحدة بـ selector"},
                 p:{en:"<code>select=&quot;[header]&quot;</code> routes matching elements to that slot only.", ar:"<code>select=&quot;[header]&quot;</code> بتوجّه العناصر المطابقة للفتحة دي بس."}},
    {i:'user',   t:{en:"The parent still owns it", ar:"الأب لسه بيملكه"},
                 p:{en:"Its expressions read the parent's data. Your component never sees those values.", ar:"تعبيراته بتقرا داتا الأب. الـ component بتاعك عمره ما هيشوف القيم دي."}},
    {i:'warn',   t:{en:"It renders even if hidden", ar:"بيترسم حتى لو مخفي"},
                 p:{en:"Projected content is built by the parent regardless. Use <code>ng-template</code> if that is expensive.", ar:"المحتوى بيتبني عند الأب على أي حال. لو ده مكلّف، استعمل <code>ng-template</code>."}},
  ],
},

'queries': {
  say:  {en:"Queries are how a component <b>gets a handle on an element or a child component</b> inside its own template.",
         ar:"الـ queries هي إزاي الـ component <b>يمسك عنصر أو component ابن</b> جوه الـ template بتاعه."},
  like: {en:"Sticking a numbered tag on one box in your warehouse so you can find it again without walking every aisle.",
         ar:"تلزق تيكيت بنمرة على صندوق في المخزن عشان تلاقيه تاني من غير ما تمشي كل الممرات."},
  when: {en:"Focusing an input, measuring a div, calling a method on a child, wiring up a chart library.",
         ar:"لما تعمل focus لخانة، أو تقيس div، أو تنادي ميثود في ابن، أو توصّل مكتبة رسوم بيانية."},
  one:  {en:"<code>viewChild</code> looks in <em>your</em> template. <code>contentChild</code> looks at what the <em>parent</em> projected into you. Mixing them up costs an hour.",
         ar:"<code>viewChild</code> بتدوّر في الـ template <em>بتاعك</em>. و<code>contentChild</code> بتدوّر في اللي <em>الأب</em> حطه جواك. لخبطتهم بتضيّع ساعة."},
  strip:[
    {i:'pin',    t:{en:"#ref names an element", ar:"#ref بتسمّي عنصر"},
                 p:{en:"A template reference variable. It is just a label, visible only in that template.", ar:"متغير مرجعي في الـ template. مجرد اسم، مش ظاهر غير في الـ template ده."}},
    {i:'eye',    t:{en:"viewChild finds it",    ar:"viewChild بتلاقيه"},
                 p:{en:"Returns a signal, so it updates itself when <code>@if</code> puts the element back.", ar:"بترجّع signal، فبتحدّث نفسها لما <code>@if</code> ترجّع العنصر تاني."}},
    {i:'boxes',  t:{en:"contentChild sees projections", ar:"contentChild بتشوف المُمرّر"},
                 p:{en:"For elements the parent passed in through <code>&lt;ng-content&gt;</code>, not ones you wrote.", ar:"للعناصر اللي الأب بعتها عن طريق <code>&lt;ng-content&gt;</code>، مش اللي إنت كتبتها."}},
    {i:'clock',  t:{en:"Timing matters",        ar:"الوقت مهم"},
                 p:{en:"In the constructor the DOM does not exist yet. Signal queries make this far less painful.", ar:"في الـ constructor الـ DOM لسه مش موجود. الـ signal queries بتخفّف الوجع ده كتير."}},
  ],
},

'routing': {
  say:  {en:"Routes are <b>just an array of objects</b>, and guards are <b>just functions that return true or false</b>. There is no magic here.",
         ar:"الـ routes مجرد <b>array من الـ objects</b>، والـ guards مجرد <b>دوال بترجّع true أو false</b>. مفيش سحر هنا."},
  like: {en:"A building directory plus a security guard at the lift. The list says which floor; the guard decides whether you get on.",
         ar:"دليل مبنى وحارس أمن عند الأسانسير. اللستة بتقول أنهي دور، والحارس بيقرر تركب ولا لأ."},
  when: {en:"Login-only pages, admin areas, unsaved-changes warnings, and screens that need data before they draw.",
         ar:"الصفحات اللي للمسجّلين بس، ومناطق الأدمن، وتحذير التغييرات غير المحفوظة، والشاشات المحتاجة داتا قبل ما ترسم."},
  one:  {en:"A guard is a function you can unit-test in isolation. If yours is hard to test, it is doing too much.",
         ar:"الـ guard دالة تقدر تختبرها لوحدها. لو بتاعك صعب تختبره، يبقى بيعمل حاجات كتير أوي."},
  strip:[
    {i:'tree',   t:{en:"Children nest routes", ar:"children بتعشّش الـ routes"},
                 p:{en:"A child route renders into the <em>parent's</em> outlet, so shared chrome stays on screen.", ar:"الـ route الابن بيترسم في outlet <em>الأب</em>، فالإطار المشترك بيفضل على الشاشة."}},
    {i:'key',    t:{en:"Params come from the URL", ar:"الـ params من الـ URL"},
                 p:{en:"<code>:id</code> in the path, and with input binding it lands straight in an <code>input()</code>.", ar:"<code>:id</code> في المسار، ومع الـ input binding بتوصل مباشرة لـ <code>input()</code>."}},
    {i:'shield', t:{en:"canActivate says yes or no", ar:"canActivate بتقول أيوة أو لأ"},
                 p:{en:"Return <code>true</code>, <code>false</code>, or a <code>UrlTree</code> to redirect somewhere else.", ar:"رجّع <code>true</code> أو <code>false</code> أو <code>UrlTree</code> عشان تحوّله لمكان تاني."}},
    {i:'db',     t:{en:"resolve pre-loads data", ar:"resolve بتجيب الداتا الأول"},
                 p:{en:"Data arrives before the component does. Costs you a slower click, buys you no flicker.", ar:"الداتا بتوصل قبل الـ component. بتكلّفك ضغطة أبطأ، وبتوفّرلك رعشة الشاشة."}},
  ],
},

'http': {
  say:  {en:"Interceptors are <b>a checkpoint every request passes through</b>, so auth headers and error handling live in one file instead of forty.",
         ar:"الـ interceptors هي <b>نقطة تفتيش كل طلب بيعدّي منها</b>، فالـ auth headers ومعالجة الأخطاء بتبقى في ملف واحد بدل أربعين."},
  like: {en:"Airport security. Every passenger goes through the same gate, and the rules are written once at the gate — not once per passenger.",
         ar:"أمن المطار. كل مسافر بيعدّي من نفس البوابة، والقواعد مكتوبة مرة واحدة عند البوابة — مش مرة لكل مسافر."},
  when: {en:"Attaching tokens, logging, retrying, showing a global spinner, translating server errors into human sentences.",
         ar:"لما تلزق tokens، أو تسجّل، أو تعيد المحاولة، أو تعرض spinner عام، أو تترجم أخطاء السيرفر لجُمل مفهومة."},
  one:  {en:"An interceptor must return the chain: <code>return next(req)</code>. Forget that line and every request in your app hangs forever.",
         ar:"الـ interceptor لازم يرجّع السلسلة: <code>return next(req)</code>. تنسى السطر ده، وكل طلب في تطبيقك هيعلّق للأبد."},
  strip:[
    {i:'net',    t:{en:"A request leaves",   ar:"الطلب بيخرج"},
                 p:{en:"Your service calls <code>http.get()</code> and knows nothing about tokens or retries.", ar:"الـ service بينادي <code>http.get()</code> ومش عارف حاجة عن الـ tokens ولا إعادة المحاولة."}},
    {i:'shield', t:{en:"The interceptor edits it", ar:"الـ interceptor بيعدّله"},
                 p:{en:"Requests are immutable — you <code>clone()</code> with the header added, then pass it on.", ar:"الطلبات ثابتة — بتعمل <code>clone()</code> وتضيف الـ header، وبعدين تمرّره."}},
    {i:'merge',  t:{en:"They chain in order", ar:"بيتسلسلوا بالترتيب"},
                 p:{en:"The array order is the execution order. Auth before logging, or your logs miss the header.", ar:"ترتيب الـ array هو ترتيب التنفيذ. الـ auth قبل الـ logging، وإلا السجل هيفوّت الـ header."}},
    {i:'warn',   t:{en:"Errors come back through", ar:"الأخطاء بترجع من نفس الطريق"},
                 p:{en:"A 401 can be caught here, refreshed, and retried without a single component knowing.", ar:"خطأ 401 ممكن يتمسك هنا، ويتجدّد التوكن، وتتعاد المحاولة من غير ما أي component يعرف."}},
  ],
},

'error-handling': {
  say:  {en:"Failing well means <b>the app stays usable when the network does not</b>, and the user is told something true.",
         ar:"الفشل المحترم معناه إن <b>التطبيق يفضل شغال لما النت مايبقاش شغال</b>، والمستخدم يتقاله حاجة صح."},
  like: {en:"A restaurant that is out of fish. The good waiter says so and offers the chicken. The bad one disappears into the kitchen forever.",
         ar:"مطعم خلص عنده السمك. الجرسون الشاطر بيقولك ويعرض عليك الفراخ. والوحش بيختفي في المطبخ للأبد."},
  when: {en:"Every network call, without exception. The happy path is the easy half of the job.",
         ar:"في كل نداء شبكة، من غير استثناء. المسار السليم هو النص السهل من الشغل."},
  one:  {en:"<code>catchError</code> must return an Observable. Returning nothing kills the stream and the screen freezes with no clue why.",
         ar:"<code>catchError</code> لازم ترجّع Observable. لو مارجّعتش حاجة، الستريم بيموت والشاشة بتتجمّد من غير أي سبب واضح."},
  strip:[
    {i:'warn',   t:{en:"Something fails",     ar:"حاجة بتفشل"},
                 p:{en:"Timeout, 500, offline, or a payload that does not match what you expected.", ar:"انتهاء وقت، أو 500، أو نت مقطوع، أو رد مش زي ما إنت متوقع."}},
    {i:'refresh',t:{en:"retry buys a second chance", ar:"retry بتدي فرصة تانية"},
                 p:{en:"With a delay, and only for network errors. Retrying a 400 just annoys the server.", ar:"بمهلة، ولأخطاء الشبكة بس. إعادة المحاولة على 400 بتزهّق السيرفر."}},
    {i:'swap',   t:{en:"catchError substitutes", ar:"catchError بتستبدل"},
                 p:{en:"Return a cached value, an empty list, or rethrow. Just return <em>something</em>.", ar:"رجّع قيمة محفوظة، أو لستة فاضية، أو ارمي الخطأ تاني. المهم ترجّع <em>حاجة</em>."}},
    {i:'bell',   t:{en:"Tell the human",      ar:"قول للمستخدم"},
                 p:{en:"A message they can act on. <em>Something went wrong</em> is not a message.", ar:"رسالة يقدر يتصرف بناءً عليها. <em>حصل خطأ ما</em> دي مش رسالة."}},
  ],
},

'rxjs-fundamentals': {
  say:  {en:"An Observable is <b>a stream of values over time</b> — like an array, except the items arrive whenever they feel like it.",
         ar:"الـ Observable هو <b>مجرى قيم على مدار الوقت</b> — زي الـ array، بس العناصر بتوصل لما تحب هي."},
  like: {en:"A water pipe. Nothing flows until you open a tap, and if two people open two taps, water is pumped twice.",
         ar:"ماسورة مياه. مفيش حاجة بتجري لحد ما تفتح حنفية، ولو اتنين فتحوا حنفيتين، المياه بتتضخ مرتين."},
  when: {en:"Anything that arrives over time: HTTP responses, keystrokes, websocket messages, router events.",
         ar:"أي حاجة بتوصل مع الوقت: ردود HTTP، وضغطات الكيبورد، ورسايل الـ websocket، وأحداث الراوتر."},
  one:  {en:"A plain <code>Observable</code> is cold — each subscriber gets its own private run. A <code>Subject</code> is hot — everyone shares one.",
         ar:"الـ <code>Observable</code> العادي بارد — كل مشترك بياخد تشغيل خاص بيه. والـ <code>Subject</code> ساخن — الكل بيتشارك واحد."},
  strip:[
    {i:'clock',  t:{en:"Nothing until subscribe", ar:"مفيش حاجة قبل subscribe"},
                 p:{en:"An Observable is a recipe, not a meal. Subscribing is what turns the stove on.", ar:"الـ Observable وصفة، مش أكلة. الـ subscribe هو اللي بيولّع البوتاجاز."}},
    {i:'split',  t:{en:"Cold means private",     ar:"بارد يعني خاص"},
                 p:{en:"Two subscribers to one HTTP observable means two real network requests.", ar:"اتنين subscribe على نفس الـ HTTP observable معناها طلبين شبكة حقيقيين."}},
    {i:'merge',  t:{en:"Subject means shared",   ar:"Subject يعني مشترك"},
                 p:{en:"One run, many listeners. You can also push into it yourself with <code>next()</code>.", ar:"تشغيل واحد وسامعين كتير. وتقدر تدفع فيه بنفسك بـ <code>next()</code>."}},
    {i:'db',     t:{en:"BehaviorSubject remembers", ar:"BehaviorSubject بيفتكر"},
                 p:{en:"It holds the last value, so a late subscriber is not left staring at nothing.", ar:"بيمسك آخر قيمة، فاللي اشترك متأخر مايفضلش قاعد يبص في الفاضي."}},
  ],
},

'effects-vs-computed': {
  say:  {en:"<code>computed()</code> <b>makes a new value</b> from other signals. <code>effect()</code> <b>makes something happen</b> outside Angular.",
         ar:"<code>computed()</code> <b>بتعمل قيمة جديدة</b> من signals تانية. و<code>effect()</code> <b>بتخلي حاجة تحصل</b> بره أنجولار."},
  like: {en:"A calculator versus a doorman. The calculator gives you a number when you ask. The doorman opens the door when someone arrives.",
         ar:"آلة حاسبة مقابل بواب. الآلة بتدّيك رقم لما تسأل. والبواب بيفتح الباب لما حد يوصل."},
  when: {en:"Deriving a total, a filtered list, a label — <code>computed</code>. Logging, localStorage, a chart library — <code>effect</code>.",
         ar:"لما تحسب إجمالي أو لستة مفلترة أو عنوان — <code>computed</code>. للتسجيل أو localStorage أو مكتبة رسوم — <code>effect</code>."},
  one:  {en:"If you are writing to a signal inside an <code>effect</code>, ninety percent of the time it should have been a <code>computed</code>.",
         ar:"لو بتكتب في signal جوه <code>effect</code>، تسعين في المية إنها كان المفروض تكون <code>computed</code>."},
  strip:[
    {i:'scale',  t:{en:"computed is a value",  ar:"computed قيمة"},
                 p:{en:"Lazy and cached. If nobody reads it, it never runs. Read it twice, it computes once.", ar:"كسولة ومتخزّنة. لو محدش قراها، عمرها ما هتشتغل. اقراها مرتين، بتتحسب مرة."}},
    {i:'bolt',   t:{en:"effect is an action",  ar:"effect فعل"},
                 p:{en:"Runs after the fact, every time any signal it read has changed.", ar:"بتشتغل بعد الحدث، كل ما أي signal قرتها تتغيّر."}},
    {i:'target', t:{en:"Tracking is automatic", ar:"التتبّع أوتوماتيك"},
                 p:{en:"Whatever you read while it runs becomes a dependency. Nothing to declare.", ar:"أي حاجة بتقراها وهي شغالة بتبقى dependency. مفيش حاجة تعلنها."}},
    {i:'warn',   t:{en:"Effects can loop",     ar:"الـ effects ممكن تلف"},
                 p:{en:"Write to a signal you also read and you have built an infinite loop by hand.", ar:"اكتب في signal إنت بتقراها، وتبقى عملت لوب لا نهائية بإيدك."}},
  ],
},

'di-host-directives': {
  say:  {en:"An injection token lets you <b>inject things that are not classes</b> — a URL, a config object, a flag.",
         ar:"الـ injection token بيخليك <b>تحقن حاجات مش classes</b> — زي URL أو object إعدادات أو flag."},
  like: {en:"A named hook on the wall. Anyone can hang something on it, and anyone can take what is hanging there — as long as they know the name.",
         ar:"شمّاعة عليها اسم. أي حد يقدر يعلّق عليها حاجة، وأي حد ياخد اللي معلّق — طالما عارف الاسم."},
  when: {en:"API base URLs, feature flags, per-environment config, and swapping a real service for a fake one in tests.",
         ar:"عناوين الـ API، وflags المزايا، وإعدادات كل بيئة، وتبديل service حقيقي بواحد مزيف في الاختبارات."},
  one:  {en:"Host directives let a component <b>wear another directive's behaviour</b> without the template having to know.",
         ar:"الـ host directives بتخلي الـ component <b>يلبس سلوك directive تاني</b> من غير ما الـ template يعرف."},
  strip:[
    {i:'key',    t:{en:"A token is a key",    ar:"الـ token مفتاح"},
                 p:{en:"<code>new InjectionToken&lt;string&gt;('apiUrl')</code>. Unique, typed, and impossible to collide.", ar:"<code>new InjectionToken&lt;string&gt;('apiUrl')</code>. فريد، وله نوع، ومستحيل يتضارب."}},
    {i:'plug',   t:{en:"Provide a value",     ar:"وفّر قيمة"},
                 p:{en:"<code>{ provide: API_URL, useValue: '...' }</code> in the app config, once.", ar:"<code>{ provide: API_URL, useValue: '...' }</code> في إعدادات التطبيق، مرة واحدة."}},
    {i:'tree',   t:{en:"Injectors nest",      ar:"الـ injectors متداخلة"},
                 p:{en:"A component-level provider shadows the root one for that subtree only.", ar:"provider على مستوى الـ component بيغطي على بتاع الـ root في الفرع ده بس."}},
    {i:'layers', t:{en:"hostDirectives compose", ar:"hostDirectives بتركّب"},
                 p:{en:"Reuse behaviour by declaration instead of by inheritance. Much easier to unpick later.", ar:"إعادة استخدام السلوك بالإعلان بدل الوراثة. أسهل بكتير إنك تفكّها بعدين."}},
  ],
},

'ui-libraries': {
  say:  {en:"Angular Material is <b>ready-made components</b>. The CDK is <b>the machinery underneath them</b>, with no styling at all.",
         ar:"Angular Material هو <b>components جاهزة</b>. والـ CDK هو <b>الميكانيكا اللي تحتيها</b>، من غير أي تنسيق."},
  like: {en:"Material is furniture from a shop. The CDK is the hinges, rails and casters — so you can build furniture nobody sells.",
         ar:"Material زي أثاث من محل. والـ CDK هو المفصلات والسكك والعجل — عشان تعمل أثاث محدش بيبيعه."},
  when: {en:"Material when you want a working app this week. The CDK when the design does not match anybody's component library.",
         ar:"Material لما تعوز تطبيق شغال الأسبوع ده. والـ CDK لما التصميم مايطابقش أي مكتبة components."},
  one:  {en:"Reach for the CDK before you hand-roll an overlay, a drag handle or a virtual scroller. Accessibility is the part you will get wrong.",
         ar:"استعمل الـ CDK قبل ما تعمل overlay أو drag أو virtual scroll بإيدك. الـ accessibility هي الحتة اللي هتغلط فيها."},
  strip:[
    {i:'boxes',  t:{en:"Material gives components", ar:"Material بيدّي components"},
                 p:{en:"Buttons, dialogs, tables, date pickers — themed, tested and accessible out of the box.", ar:"أزرار وديالوجات وجداول ومنتقيات تواريخ — منسّقة ومختبرة ومتاحة للجميع من أول لحظة."}},
    {i:'gear',   t:{en:"The CDK gives behaviour", ar:"الـ CDK بيدّي سلوك"},
                 p:{en:"Overlay, drag-drop, focus trapping, virtual scroll — with zero opinions about looks.", ar:"overlay وسحب وإفلات وحصر الـ focus وvirtual scroll — من غير أي رأي في الشكل."}},
    {i:'wand',   t:{en:"Theme with tokens",     ar:"نسّق بالـ tokens"},
                 p:{en:"Material 3 themes are CSS custom properties. Override the tokens, not the components.", ar:"ثيمات Material 3 عبارة عن CSS custom properties. غيّر الـ tokens، مش الـ components."}},
    {i:'scale',  t:{en:"Weigh the bundle",      ar:"احسب حجم الحزمة"},
                 p:{en:"Import only the components you use. Importing the whole library is a real cost.", ar:"استورد الـ components اللي بتستعملها بس. استيراد المكتبة كلها تكلفة حقيقية."}},
  ],
},

'change-detection': {
  say:  {en:"Change detection is Angular <b>walking the component tree asking &quot;did anything change?&quot;</b> and updating the DOM where it did.",
         ar:"الـ change detection هو أنجولار وهو <b>بيلف على شجرة الـ components ويسأل «في حاجة اتغيّرت؟»</b> ويحدّث الـ DOM في اللي اتغيّر."},
  like: {en:"A night watchman doing rounds. The old way was checking every door on every round. Signals hand him a list of exactly which doors moved.",
         ar:"غفير بيعمل جولة. الطريقة القديمة إنه يفحص كل باب في كل جولة. الـ signals بتدّيله لستة بالأبواب اللي اتحركت بالظبط."},
  when: {en:"You do not call it. You feel it — as a slow list, a jumpy scroll, or a value on screen that refuses to update.",
         ar:"إنت مش بتناديه. إنت بتحسّه — في لستة بطيئة، أو scroll بينطط، أو قيمة على الشاشة رافضة تتحدّث."},
  one:  {en:"<code>OnPush</code> plus signals means Angular checks only the components that actually read something that changed.",
         ar:"<code>OnPush</code> مع الـ signals معناها إن أنجولار بيفحص بس الـ components اللي قرت حاجة اتغيّرت فعلاً."},
  strip:[
    {i:'bell',   t:{en:"Something happens",  ar:"حاجة بتحصل"},
                 p:{en:"A click, a timer, a response. Historically Zone.js noticed all of these for you.", ar:"ضغطة، أو تايمر، أو رد. زمان Zone.js كان بياخد باله من دول كلهم."}},
    {i:'tree',   t:{en:"Angular walks the tree", ar:"أنجولار بيلف على الشجرة"},
                 p:{en:"Top to bottom, comparing each binding's current value against its last one.", ar:"من فوق لتحت، بيقارن قيمة كل binding دلوقتي بآخر قيمة ليها."}},
    {i:'filter', t:{en:"OnPush prunes branches", ar:"OnPush بتقص فروع"},
                 p:{en:"A component is skipped entirely unless an input changed or an event fired inside it.", ar:"الـ component بيتساب خالص إلا لو input اتغيّر أو حدث اتطلق جواه."}},
    {i:'target', t:{en:"Signals go straight there", ar:"الـ signals بتروح على طول"},
                 p:{en:"No walking at all — the signal already knows exactly which views read it.", ar:"مفيش لفّان خالص — الـ signal عارفة بالظبط أنهي views قرتها."}},
  ],
},

'zoneless': {
  say:  {en:"Zoneless means <b>deleting the library that used to guess when to re-render</b>, because signals now tell Angular directly.",
         ar:"الـ zoneless معناها <b>إنك تشيل المكتبة اللي كانت بتخمّن إمتى تعيد الرسم</b>، لأن الـ signals بقت بتقول لأنجولار على طول."},
  like: {en:"Removing a smoke detector that beeped at every piece of toast, because every appliance now has its own alarm wired in.",
         ar:"تشيل حساس دخان كان بيزعّق مع كل توست، لأن كل جهاز بقى فيه إنذار خاص بيه."},
  when: {en:"New apps: turn it on from day one. Existing apps: after your state is on signals, not before.",
         ar:"التطبيقات الجديدة: شغّلها من أول يوم. القديمة: بعد ما حالتك تبقى على signals، مش قبل."},
  one:  {en:"Zoneless is a smaller bundle and fewer surprise re-renders — but only if your state actually lives in signals.",
         ar:"الـ zoneless معناها حزمة أصغر وإعادة رسم أقل مفاجآت — بس بشرط إن حالتك تكون فعلاً في signals."},
  strip:[
    {i:'cross',  t:{en:"Zone.js goes away",  ar:"Zone.js بيمشي"},
                 p:{en:"It patched every browser API to notice activity. That patching had a real cost.", ar:"كان بيعدّل كل APIs المتصفح عشان ياخد باله من أي نشاط. والتعديل ده كان بيكلّف فعلاً."}},
    {i:'sig',    t:{en:"Signals notify instead", ar:"الـ signals بتبلّغ بدله"},
                 p:{en:"A precise notification beats a global guess, every single time.", ar:"إشعار دقيق أحسن من تخمين عام، في كل مرة."}},
    {i:'warn',   t:{en:"Untracked state breaks", ar:"الحالة غير المتتبَّعة بتقع"},
                 p:{en:"A plain class field mutated in a callback will simply not appear on screen.", ar:"property عادية بتتغيّر في callback مش هتظهر على الشاشة أصلاً."}},
    {i:'check',  t:{en:"Migrate gradually",   ar:"انقل بالتدريج"},
                 p:{en:"Run the hybrid scheduler first, fix what breaks, then drop the polyfill.", ar:"شغّل الـ hybrid scheduler الأول، صلّح اللي بيقع، وبعدين شيل الـ polyfill."}},
  ],
},

'rxjs-operators': {
  say:  {en:"These four operators answer one question: <b>a new request arrived while the old one is still running — what do I do?</b>",
         ar:"الأربع operators دول بيجاوبوا على سؤال واحد: <b>جه طلب جديد والقديم لسه شغال — أعمل إيه؟</b>"},
  like: {en:"A drive-through with one window. Cancel the old order, queue it, serve both at once, or refuse the new car until you are done. Four policies, four operators.",
         ar:"دريف ثرو بشباك واحد. تلغي الطلب القديم، أو تحطه في الدور، أو تخدم الاتنين مع بعض، أو ترفض العربية الجديدة لحد ما تخلّص. أربع سياسات، أربع operators."},
  when: {en:"Search-as-you-type, save buttons, file uploads, autocomplete — anywhere a user can trigger the same thing twice.",
         ar:"البحث أثناء الكتابة، وأزرار الحفظ، ورفع الملفات، والإكمال التلقائي — أي مكان المستخدم يقدر يشغّل نفس الحاجة مرتين."},
  one:  {en:"Typeahead is <code>switchMap</code>. A save button is <code>exhaustMap</code>. Getting this pair right removes most double-submit bugs.",
         ar:"البحث أثناء الكتابة = <code>switchMap</code>. وزرار الحفظ = <code>exhaustMap</code>. لما تظبط الاتنين دول، أغلب مشاكل الإرسال المزدوج بتختفي."},
  strip:[
    {i:'cross',  t:{en:"switchMap cancels",  ar:"switchMap بتلغي"},
                 p:{en:"New value in, old request aborted. Only the latest result can ever arrive.", ar:"قيمة جديدة دخلت، الطلب القديم اتلغى. النتيجة الأخيرة بس هي اللي بتوصل."}},
    {i:'list',   t:{en:"concatMap queues",   ar:"concatMap بتصفّ"},
                 p:{en:"Strict order, one at a time. Slower, but nothing overtakes anything else.", ar:"ترتيب صارم، واحد ورا التاني. أبطأ، بس محدش بيسبق حد."}},
    {i:'merge',  t:{en:"mergeMap overlaps",  ar:"mergeMap بتتداخل"},
                 p:{en:"All in flight together. Fastest, and the results can come back in any order.", ar:"كلهم شغالين مع بعض. الأسرع، والنتايج ممكن ترجع بأي ترتيب."}},
    {i:'shield', t:{en:"exhaustMap ignores", ar:"exhaustMap بتتجاهل"},
                 p:{en:"While one is running, new triggers are dropped. This is the anti-double-click.", ar:"طول ما في واحد شغال، أي طلب جديد بيتترمي. دي مضادة الضغط المزدوج."}},
  ],
},

'rxjs-combination': {
  say:  {en:"Combination operators are how you <b>wait for several streams and get one answer</b> out of them.",
         ar:"الـ combination operators هي إزاي <b>تستنى كذا مجرى وتطلع منهم إجابة واحدة</b>."},
  like: {en:"Three cooks and one plate. Do you wait until all three are finished, or plate up again every time any of them adds something?",
         ar:"تلات طباخين وطبق واحد. هتستنى لحد ما التلاتة يخلّصوا، ولا تعيد التقديم كل ما واحد فيهم يضيف حاجة؟"},
  when: {en:"Loading a screen that needs three endpoints, or a filter panel where any control changing should refetch.",
         ar:"لما تحمّل شاشة محتاجة تلات endpoints، أو لوحة فلاتر أي عنصر فيها يتغيّر يعيد الجلب."},
  one:  {en:"<code>forkJoin</code> waits for everyone to finish. <code>combineLatest</code> fires again every time <em>anyone</em> speaks.",
         ar:"<code>forkJoin</code> بتستنى الكل يخلّص. و<code>combineLatest</code> بتشتغل تاني كل ما <em>أي حد</em> يتكلم."},
  strip:[
    {i:'check',  t:{en:"forkJoin waits for all", ar:"forkJoin بتستنى الكل"},
                 p:{en:"One emission at the end. If any stream never completes, you wait forever.", ar:"إطلاق واحد في الآخر. ولو مجرى مخلّصش أبداً، هتستنى للأبد."}},
    {i:'refresh',t:{en:"combineLatest is live",  ar:"combineLatest حيّة"},
                 p:{en:"Emits on every change, but only after every source has produced at least one value.", ar:"بتطلق مع كل تغيير، بس بعد ما كل مصدر يطلع قيمة واحدة على الأقل."}},
    {i:'pin',    t:{en:"withLatestFrom peeks",   ar:"withLatestFrom بتسترق النظر"},
                 p:{en:"One stream is the trigger; the others are just looked at. Great for click-plus-current-state.", ar:"مجرى واحد هو المشغّل، والباقي بتتفرج عليهم بس. ممتازة لضغطة + الحالة الحالية."}},
    {i:'merge',  t:{en:"startWith unblocks",     ar:"startWith بتفك الحصار"},
                 p:{en:"Give a silent stream an initial value so <code>combineLatest</code> can get going.", ar:"إدّي المجرى الساكت قيمة أولية عشان <code>combineLatest</code> تعرف تبدأ."}},
  ],
},

'rxjs-interop': {
  say:  {en:"Interop is <b>two small bridges</b>: turn an Observable into a signal, or a signal into an Observable.",
         ar:"الـ interop عبارة عن <b>كوبرين صغيرين</b>: تحوّل Observable لـ signal، أو signal لـ Observable."},
  like: {en:"A power adapter. Both sides carry electricity; they just have different plugs.",
         ar:"محوّل كهربا. الطرفين فيهم كهربا، بس كل واحد بفيشة مختلفة."},
  when: {en:"Any real app. Templates want signals; HTTP, websockets and router events arrive as Observables.",
         ar:"في أي تطبيق حقيقي. الـ templates عايزة signals، والـ HTTP والـ websockets وأحداث الراوتر بتيجي Observables."},
  one:  {en:"<code>toSignal</code> subscribes and cleans up for you. That alone removes most of the unsubscribe bugs you would have written.",
         ar:"<code>toSignal</code> بتعمل subscribe وبتنضّف بدالك. ودي لوحدها بتشيل أغلب مشاكل الـ unsubscribe."},
  strip:[
    {i:'arrow',  t:{en:"toSignal comes in",   ar:"toSignal بتدخّل"},
                 p:{en:"Observable to signal. Give it an <code>initialValue</code> or handle <code>undefined</code>.", ar:"من Observable لـ signal. إدّيها <code>initialValue</code> أو اتعامل مع <code>undefined</code>."}},
    {i:'swap',   t:{en:"toObservable goes out", ar:"toObservable بتطلّع"},
                 p:{en:"Signal to Observable, so you can use <code>debounceTime</code> and <code>switchMap</code> on it.", ar:"من signal لـ Observable، عشان تستعمل <code>debounceTime</code> و<code>switchMap</code>."}},
    {i:'shield', t:{en:"takeUntilDestroyed",  ar:"takeUntilDestroyed"},
                 p:{en:"When you must subscribe by hand, this is the line that stops the leak.", ar:"لما تضطر تعمل subscribe بإيدك، ده السطر اللي بيمنع التسريب."}},
    {i:'net',    t:{en:"rxResource joins both", ar:"rxResource بتجمع الاتنين"},
                 p:{en:"A signal request in, an Observable fetch in the middle, signals for value and error out.", ar:"طلب signal داخل، وجلب Observable في النص، وsignals للقيمة والخطأ خارجة."}},
  ],
},

'signal-state': {
  say:  {en:"Signal-based state is <b>keeping your app's data in signals inside a service</b>, with methods as the only way to change it.",
         ar:"الـ signal state معناها <b>إنك تحط داتا التطبيق في signals جوه service</b>، والميثودز هي الطريقة الوحيدة لتغييرها."},
  like: {en:"A bank account. The balance is not a public variable anyone can edit — you deposit and withdraw through the counter.",
         ar:"حساب بنكي. الرصيد مش متغيّر عام أي حد يعدّله — بتودّع وتسحب من الشباك."},
  when: {en:"The moment a third component needs the same data, or a value must survive navigation.",
         ar:"أول ما تالت component يحتاج نفس الداتا، أو قيمة لازم تعيش بعد التنقّل."},
  one:  {en:"Expose signals as <b>read-only</b> and change them only through methods. Then every possible mutation is a name you can search for.",
         ar:"اعرض الـ signals <b>للقراءة بس</b> وغيّرها بالميثودز بس. وساعتها كل تغيير ممكن هيبقى اسم تقدر تدوّر عليه."},
  strip:[
    {i:'lock',   t:{en:"Private writable",     ar:"قابلة للكتابة وخاصة"},
                 p:{en:"<code>#items = signal([])</code> stays inside the service. Nobody outside can touch it.", ar:"<code>#items = signal([])</code> بتفضل جوه الـ service. محدش بره يقدر يلمسها."}},
    {i:'eye',    t:{en:"Public read-only",     ar:"للقراءة بس للعامة"},
                 p:{en:"<code>items = this.#items.asReadonly()</code>. Components can read but never write.", ar:"<code>items = this.#items.asReadonly()</code>. الـ components تقرا بس مش تكتب."}},
    {i:'scale',  t:{en:"computed derives",     ar:"computed بتشتق"},
                 p:{en:"Totals, counts and filters are computed, never stored. Stored copies drift apart.", ar:"الإجماليات والأعداد والفلاتر بتتحسب، مابتتخزّنش. النسخ المخزّنة بتختلف مع الوقت."}},
    {i:'wrench', t:{en:"Methods are the API",  ar:"الميثودز هي الواجهة"},
                 p:{en:"<code>add()</code>, <code>remove()</code>, <code>clear()</code>. Every change has a name and a place.", ar:"<code>add()</code> و<code>remove()</code> و<code>clear()</code>. كل تغيير ليه اسم ومكان."}},
  ],
},

'global-state': {
  say:  {en:"State libraries add <b>rules about how data may change</b> — actions, reducers, devtools — on top of what a service already does.",
         ar:"مكتبات الحالة بتضيف <b>قواعد لطريقة تغيير الداتا</b> — actions وreducers وdevtools — فوق اللي الـ service بيعمله أصلاً."},
  like: {en:"A ledger instead of a notebook. Slower to write in, but you can prove exactly who changed what and when.",
         ar:"دفتر حسابات بدل نوتة. أبطأ في الكتابة، بس تقدر تثبت مين غيّر إيه وإمتى بالظبط."},
  when: {en:"Large teams, complex flows, or when you genuinely need time-travel debugging. Not for a to-do list.",
         ar:"الفرق الكبيرة، والتدفقات المعقّدة، أو لما تحتاج فعلاً debugging بالرجوع في الزمن. مش لتطبيق مهام."},
  one:  {en:"Start with a signal service. Move to a library when you can name the specific pain it removes — not before.",
         ar:"ابدأ بـ service فيه signals. وانتقل لمكتبة لما تقدر تسمّي الوجع اللي هتشيله بالظبط — مش قبل كده."},
  strip:[
    {i:'bell',   t:{en:"An action describes", ar:"الـ action بيوصف"},
                 p:{en:"Just a named event: <em>product added to cart</em>. It changes nothing by itself.", ar:"مجرد حدث ليه اسم: <em>منتج اتضاف للعربة</em>. مش بيغيّر حاجة بنفسه."}},
    {i:'gear',   t:{en:"A reducer decides",   ar:"الـ reducer بيقرر"},
                 p:{en:"Old state plus action equals new state. A pure function, trivially testable.", ar:"الحالة القديمة + الحدث = حالة جديدة. دالة نقية، اختبارها سهل جداً."}},
    {i:'eye',    t:{en:"A selector reads",    ar:"الـ selector بيقرا"},
                 p:{en:"Components subscribe to slices, so they never see the shape of the whole store.", ar:"الـ components بتشترك في أجزاء، فمابتشوفش شكل المخزن كله."}},
    {i:'bug',    t:{en:"Devtools replay",     ar:"الـ devtools بتعيد"},
                 p:{en:"Step backwards through every action. This is the feature people actually pay for.", ar:"ارجع خطوة بخطوة في كل حدث. دي الميزة اللي الناس بتدفع عشانها فعلاً."}},
  ],
},

'dynamic-components': {
  say:  {en:"Dynamic components are <b>components you create in code</b>, when the template cannot know in advance which one it needs.",
         ar:"الـ dynamic components هي <b>components بتعملها بالكود</b>، لما الـ template مايقدرش يعرف مقدّماً أنهي واحد محتاجه."},
  like: {en:"A theatre with an empty stage. The script decides at showtime which actor walks on.",
         ar:"مسرح بخشبة فاضية. النص بيقرر وقت العرض مين الممثل اللي هيطلع."},
  when: {en:"Modals, toasts, dashboard widgets chosen by config, a form built from a server-sent schema.",
         ar:"المودالات والتنبيهات وودجت الداشبورد المختارة من إعدادات، وفورم متبني من schema جاية من السيرفر."},
  one:  {en:"If a plain <code>@if</code> or <code>@switch</code> can do it, use that instead. Dynamic creation costs you type safety.",
         ar:"لو <code>@if</code> أو <code>@switch</code> عادية تقدر تعمل اللي إنت عايزه، استعملها. الإنشاء الديناميكي بيكلّفك أمان الأنواع."},
  strip:[
    {i:'box',    t:{en:"NgComponentOutlet first", ar:"NgComponentOutlet الأول"},
                 p:{en:"A template directive that takes a component class. Covers most real cases.", ar:"directive بياخد class الـ component. بتغطي أغلب الحالات الحقيقية."}},
    {i:'pin',    t:{en:"ViewContainerRef is the spot", ar:"ViewContainerRef هي البقعة"},
                 p:{en:"An anchor in the DOM that says: new components get inserted right here.", ar:"مرساة في الـ DOM بتقول: الـ components الجديدة بتتحط هنا بالظبط."}},
    {i:'wand',   t:{en:"createComponent builds it", ar:"createComponent بتبنيه"},
                 p:{en:"Returns a ref. Set inputs with <code>setInput</code>, and the ref is your only handle.", ar:"بترجّع ref. اظبط الـ inputs بـ <code>setInput</code>، والـ ref ده مقبضك الوحيد."}},
    {i:'cross',  t:{en:"You must destroy it",  ar:"لازم تمسحه بإيدك"},
                 p:{en:"Nothing cleans up a hand-made component for you. Call <code>destroy()</code>.", ar:"مفيش حاجة بتنضّف component عملته بإيدك. نادي <code>destroy()</code>."}},
  ],
},

'control-value-accessor': {
  say:  {en:"<code>ControlValueAccessor</code> is the interface that makes <b>your own component work inside a form</b> like a native input.",
         ar:"<code>ControlValueAccessor</code> هي الواجهة اللي بتخلي <b>الـ component بتاعك يشتغل جوه فورم</b> زي أي input عادي."},
  like: {en:"A universal plug adapter. Your device is unusual; the adapter makes the socket believe it is normal.",
         ar:"محوّل فيشة عالمي. جهازك غريب، والمحوّل بيخلي الفيشة تفتكره عادي."},
  when: {en:"A star rating, a colour picker, a tag input — anything you want to use with <code>formControlName</code>.",
         ar:"تقييم بالنجوم، أو منتقي ألوان، أو خانة وسوم — أي حاجة عايز تستعملها مع <code>formControlName</code>."},
  one:  {en:"Four methods, and the one everybody forgets is <code>setDisabledState</code>. Without it your control ignores <code>disable()</code> entirely.",
         ar:"أربع ميثودز، واللي الكل بينساها هي <code>setDisabledState</code>. من غيرها الخانة بتاعتك بتتجاهل <code>disable()</code> خالص."},
  strip:[
    {i:'arrow',  t:{en:"writeValue: form to you", ar:"writeValue: من الفورم ليك"},
                 p:{en:"The form pushes a value in. Store it; do not emit anything back.", ar:"الفورم بيدفع قيمة جواك. خزّنها، وماتطلقش أي حاجة للخارج."}},
    {i:'bell',   t:{en:"onChange: you to form",  ar:"onChange: منك للفورم"},
                 p:{en:"Call the callback they registered whenever the user changes something.", ar:"نادي الـ callback اللي سجّلوها كل ما المستخدم يغيّر حاجة."}},
    {i:'hand',   t:{en:"onTouched: on blur",     ar:"onTouched: عند الخروج"},
                 p:{en:"This is what makes <em>required</em> errors appear at the right moment.", ar:"دي اللي بتخلي أخطاء <em>مطلوب</em> تظهر في اللحظة الصح."}},
    {i:'lock',   t:{en:"setDisabledState",       ar:"setDisabledState"},
                 p:{en:"Grey yourself out and stop accepting input. Skipping this is the classic bug.", ar:"طفّي نفسك ووقّف استقبال الإدخال. نسيان دي هي الغلطة الكلاسيكية."}},
  ],
},

'renderer2': {
  say:  {en:"<code>Renderer2</code> is <b>a safe way to touch the DOM</b> that still works on a server, in a worker, or with hydration.",
         ar:"<code>Renderer2</code> هو <b>طريقة آمنة تلمس بيها الـ DOM</b> وبتفضل شغالة على السيرفر أو في worker أو مع الـ hydration."},
  like: {en:"Talking through an interpreter instead of shouting. Slightly slower, but understood everywhere you go.",
         ar:"تتكلم عن طريق مترجم بدل ما تزعّق. أبطأ شوية، بس مفهوم في أي مكان تروحه."},
  when: {en:"When binding genuinely cannot do it: a third-party library, a measured position, a focus trap.",
         ar:"لما الـ binding مايقدرش فعلاً: مكتبة خارجية، أو موضع محسوب، أو حصر focus."},
  one:  {en:"Ninety-nine times out of a hundred a binding is the answer. <code>Renderer2</code> is the hundredth.",
         ar:"تسعة وتسعين مرة من مية، الـ binding هو الحل. و<code>Renderer2</code> هو المرة المية."},
  strip:[
    {i:'warn',   t:{en:"document is not always there", ar:"document مش موجود دايماً"},
                 p:{en:"During SSR there is no browser. Direct DOM access crashes the render.", ar:"وقت الـ SSR مفيش متصفح. الوصول المباشر للـ DOM بيوقّع الرسم."}},
    {i:'plug',   t:{en:"inject(Renderer2)",           ar:"inject(Renderer2)"},
                 p:{en:"An abstraction over whatever host you are running on, browser or not.", ar:"طبقة تجريد فوق أي بيئة إنت شغال فيها، متصفح أو لأ."}},
    {i:'wrench', t:{en:"Small, boring methods",       ar:"ميثودز صغيرة مملة"},
                 p:{en:"<code>addClass</code>, <code>setStyle</code>, <code>listen</code>. Verbose on purpose.", ar:"<code>addClass</code> و<code>setStyle</code> و<code>listen</code>. طويلة بشكل مقصود."}},
    {i:'check',  t:{en:"listen returns a remover",    ar:"listen بترجّع مزيل"},
                 p:{en:"Keep the returned function and call it in <code>ngOnDestroy</code>.", ar:"امسك الدالة الراجعة وناديها في <code>ngOnDestroy</code>."}},
  ],
},

'lazy-loading': {
  say:  {en:"Lazy loading means <b>not downloading a screen until somebody actually goes to it</b>.",
         ar:"الـ lazy loading معناه <b>إنك ماتحمّلش شاشة لحد ما حد يروحلها فعلاً</b>."},
  like: {en:"A restaurant that cooks per order instead of cooking the entire menu before opening.",
         ar:"مطعم بيطبخ حسب الطلب بدل ما يطبخ المنيو كله قبل ما يفتح."},
  when: {en:"Every route beyond the first two. Especially admin panels, which most users never open.",
         ar:"كل route بعد أول اتنين. وخصوصاً لوحات الأدمن، اللي أغلب المستخدمين عمرهم ما بيفتحوها."},
  one:  {en:"<code>loadComponent</code> on a route is the whole feature. Preloading then fetches it quietly in the background before it is needed.",
         ar:"<code>loadComponent</code> على الـ route هي الميزة كلها. والـ preloading بيجيبها بهدوء في الخلفية قبل ما تحتاجها."},
  strip:[
    {i:'scale',  t:{en:"One bundle is too big", ar:"حزمة واحدة كبيرة أوي"},
                 p:{en:"Every screen shipped to every user on first paint, whether they visit it or not.", ar:"كل شاشة بتتشحن لكل مستخدم من أول رسمة، سواء زارها أو لأ."}},
    {i:'split',  t:{en:"loadComponent splits",  ar:"loadComponent بتقسّم"},
                 p:{en:"A dynamic <code>import()</code> tells the build tool where to cut the file.", ar:"<code>import()</code> ديناميكي بيقول لأداة البناء تقص الملف فين."}},
    {i:'clock',  t:{en:"The click pays the cost", ar:"الضغطة بتدفع التكلفة"},
                 p:{en:"On a slow connection that is a visible wait, right after the user clicks.", ar:"على نت بطيء ده انتظار ظاهر، بعد ما المستخدم يدوس على طول."}},
    {i:'bolt',   t:{en:"Preloading hides it",   ar:"الـ preloading بيخبّيها"},
                 p:{en:"Fetch during idle time, or on link hover, so the click feels instant.", ar:"جيبها وقت الخمول، أو لما الماوس يعدّي على اللينك، فالضغطة تحس إنها فورية."}},
  ],
},

