/* names for the basic routing topic. Format: see inputs-outputs.mjs. */
export default {
'basic-routing': {
  note: {
    en: 'A route path is a name you invent, but it is typed in many places: the route table, every <code>routerLink</code> and every <code>navigate()</code>. Rename it in one place only and the link lands on the <code>**</code> page. Nothing warns you.',
    ar: 'مسار الـ route اسم انت بتخترعه، بس بيتكتب في أماكن كتير: جدول الـ routes، وكل <code>routerLink</code>، وكل <code>navigate()</code>. لو غيّرته في مكان واحد بس اللينك هيوديك على صفحة الـ <code>**</code>. ومحدش هيحذّرك.'
  },
  names: [
    { n:'Routes', k:'ng', w:{ en:'Angular’s type for a route table.', ar:'الـ type بتاع أنجولار لجدول الـ routes.' } },
    { n:'path', k:'ng', w:{ en:'A route option key Angular reads. The string you give it is yours.', ar:'مفتاح إعداد في الـ route أنجولار بيقراه. النص اللي بتديهوله بتاعك.' } },
    { n:'pathMatch', k:'ng', w:{ en:'A route option key Angular reads.', ar:'مفتاح إعداد في الـ route أنجولار بيقراه.' } },
    { n:'full', k:'ng', w:{ en:'One of the two values <code>pathMatch</code> accepts (the other is <code>prefix</code>).', ar:'واحدة من القيمتين اللي <code>pathMatch</code> بيقبلهم (التانية <code>prefix</code>).' } },
    { n:'redirectTo', k:'ng', w:{ en:'A route option key Angular reads.', ar:'مفتاح إعداد في الـ route أنجولار بيقراه.' } },
    { n:'title', k:'ng', w:{ en:'A route option key: Angular puts its value in the browser tab.', ar:'مفتاح إعداد في الـ route: أنجولار بيحط قيمته في تاب المتصفح.' } },
    { n:'loadComponent', k:'ng', w:{ en:'A route option key for a lazily loaded component.', ar:'مفتاح إعداد في الـ route لـ component بيتحمّل وقت ما يتطلب.' } },
    { n:'**', k:'ng', w:{ en:'The router’s wildcard: matches any URL nothing above it matched.', ar:'الـ wildcard بتاع الـ router: بيطابق أي URL محدش فوقه طابقه.' } },
    { n:'routerLink', k:'ng', w:{ en:'Angular’s directive that navigates without reloading the page.', ar:'الـ directive بتاع أنجولار اللي بيتنقل من غير ما يعمل reload للصفحة.' } },
    { n:'routerLinkActive', k:'ng',
      w:{ en:'Angular’s directive that adds a CSS class while the link is the current page. The class name you give it is yours.',
          ar:'الـ directive بتاع أنجولار اللي بيحط CSS class طول ما اللينك هو الصفحة الحالية. اسم الـ class اللي بتديهوله بتاعك.' } },
    { n:'routerLinkActiveOptions', k:'ng', w:{ en:'An input of Angular’s <code>routerLinkActive</code>.', ar:'input في <code>routerLinkActive</code> بتاع أنجولار.' } },
    { n:'exact', k:'ng', re:'(?<![\\w$-])(?<!<!-- )exact(?![\\w$-])', w:{ en:'An option key <code>routerLinkActive</code> reads.', ar:'مفتاح إعداد <code>routerLinkActive</code> بيقراه.' } },
    { n:'queryParams', k:'ng',
      w:{ en:'Angular’s name for the <code>?key=value</code> part, both on <code>routerLink</code> and in <code>navigate()</code>. The keys inside are yours.',
          ar:'اسم أنجولار لجزء <code>?key=value</code>، في <code>routerLink</code> وفي <code>navigate()</code>. المفاتيح اللي جواه بتاعتك.' } },
    { n:'router-outlet', k:'ng', w:{ en:'Angular’s tag: the hole the matched page is drawn into.', ar:'تاج أنجولار: الفتحة اللي الصفحة المطابقة بتترسم فيها.' } },
    { n:'input', k:'ng', w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'withComponentInputBinding', k:'ng',
      w:{ en:'Angular’s router feature that fills inputs from the URL, matching them by name.',
          ar:'ميزة في الـ router بتاع أنجولار بتملا الـ inputs من الـ URL، وبتطابقهم بالاسم.' } },
    { n:'provideRouter', k:'ng', w:{ en:'Angular’s function that switches the router on.', ar:'الـ function بتاعة أنجولار اللي بتشغّل الـ router.' } },
    { n:'Router', k:'ng', w:{ en:'Angular’s router service.', ar:'الـ service بتاعة الـ router في أنجولار.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتديك service.' } },
    { n:'navigate', k:'ng', w:{ en:'A <code>Router</code> method that takes the URL in parts.', ar:'ميثود في الـ <code>Router</code> بتاخد الـ URL أجزاء.' } },
    { n:'navigateByUrl', k:'ng', w:{ en:'A <code>Router</code> method that takes the whole URL as one string.', ar:'ميثود في الـ <code>Router</code> بتاخد الـ URL كله نص واحد.' } },
    { n:'replaceUrl', k:'ng', w:{ en:'A navigation option key Angular reads.', ar:'مفتاح إعداد في التنقل أنجولار بيقراه.' } },

    { n:'routes', k:'pub',
      w:{ en:'Your route table. <code>app.config.ts</code> imports it by this name.',
          ar:'جدول الـ routes بتاعك. <code>app.config.ts</code> بيعمله import بالاسم ده.' } },
    { n:'products', k:'pub', re:'(?<=[\'"]\\/?)products(?=[\\/\'"])',
      w:{ en:'A URL segment you invented. The route path, every <code>routerLink</code> and every <code>navigate()</code> must spell it the same. The <code>products()</code> signal and the <code>./pages/products</code> file are different things.',
          ar:'جزء من الـ URL انت اخترعته. مسار الـ route وكل <code>routerLink</code> وكل <code>navigate()</code> لازم يكتبوه زي بعض. والـ signal <code>products()</code> والملف <code>./pages/products</code> حاجات تانية.' } },
    { n:'about', k:'pub', re:'(?<=[\'"]\\/?)about(?=[\\/\'"])',
      w:{ en:'A URL segment: the route path and the link must match.', ar:'جزء من الـ URL: مسار الـ route واللينك لازم يطابقوا بعض.' } },
    { n:'id', k:'pub', only:['routes','page'],
      w:{ en:'The route parameter. With <code>withComponentInputBinding()</code> the input must be named exactly like <code>:id</code> in the path.',
          ar:'الـ parameter بتاع الـ route. مع <code>withComponentInputBinding()</code> الـ input لازم اسمه يبقى زي <code>:id</code> في المسار بالظبط.' } },
    { n:'sort', k:'pub',
      w:{ en:'A query parameter. Whoever builds the link and the page that reads it with <code>input()</code> must use the same key.',
          ar:'query parameter. اللي بيبني اللينك والصفحة اللي بتقراه بـ <code>input()</code> لازم يستخدموا نفس المفتاح.' } },
    { n:'active', k:'pub',
      w:{ en:'Your CSS class name. The stylesheet must style the same name.', ar:'اسم الـ CSS class بتاعك. الـ stylesheet لازم يستايل نفس الاسم.' } },
    { n:'Products', k:'pub', re:'(?<=\\.)Products(?![\\w$-])',
      w:{ en:'The page’s class name. The <code>m.Products</code> in the lazy import must match its export.',
          ar:'اسم كلاس الصفحة. الـ <code>m.Products</code> في الـ lazy import لازم يطابق الـ export بتاعه.' } },
    { n:'ProductDetail', k:'pub',
      w:{ en:'The detail page’s class name, picked out of the lazy import by name.', ar:'اسم كلاس صفحة التفاصيل، بيتاخد من الـ lazy import بالاسم.' } },
    { n:'product', k:'mine', only:['page','md2'], re:'(?<![\\w$.-])product(?=\\s*[(=])',
      w:{ en:'The detail page’s own computed, read by its own template.', ar:'الـ computed بتاع صفحة التفاصيل، والتمبلت بتاعها بيقراه.' } },
    { n:'lookup', k:'mine', w:{ en:'The page’s own method.', ar:'ميثود الصفحة نفسها.' } },
    { n:'router', k:'mine', re:'(?<![\\w$\\/-])router(?![\\w$-])', w:{ en:'The field you store the injected <code>Router</code> in.', ar:'الـ field اللي بتحط فيه الـ <code>Router</code> اللي اتعمله inject.' } },
  ]
}
};
