/* names for the component styles topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'component-styles': {
  note: {
    en: 'In a stylesheet, anything that starts with <code>:</code> or <code>::</code> is CSS’s or Angular’s. Class names and <code>--variables</code> are yours, but a stylesheet is always read by another file: the template that puts the class on, or the component that sets the variable. Rename both sides.',
    ar: 'في الـ stylesheet، أي حاجة بتبدأ بـ <code>:</code> أو <code>::</code> دي بتاعة CSS أو أنجولار. أسماء الـ class والـ <code>--variables</code> بتاعتك، بس الـ stylesheet دايماً فيه ملف تاني بيقراه: التمبلت اللي بيحط الـ class، أو الـ component اللي بيحط قيمة الـ variable. غيّر الناحيتين.'
  },
  names: [
    { n:'@Component', k:'ng',
      w:{ en:'Angular’s decorator that turns the class into a component.',
          ar:'الـ decorator بتاع أنجولار اللي بيحوّل الكلاس لـ component.' } },
    { n:'selector', k:'ng', only:['ts'],
      w:{ en:'An option key Angular reads. The tag name you put in it is yours.',
          ar:'مفتاح إعداد أنجولار بيقراه. اسم التاج اللي بتحطه فيه بتاعك.' } },
    { n:'templateUrl', k:'ng',
      w:{ en:'An option key Angular reads: the path to the HTML file.',
          ar:'مفتاح إعداد أنجولار بيقراه: مسار ملف الـ HTML.' } },
    { n:'styleUrl', k:'ng',
      w:{ en:'An option key Angular reads: the path to this component’s own CSS file. Only styles in here get scoped.',
          ar:'مفتاح إعداد أنجولار بيقراه: مسار ملف الـ CSS الخاص بالـ component ده. الستايلات اللي هنا بس هي اللي بتتقفل عليه.' } },
    { n:'input', k:'ng', re:'(?<![\\w$<(-])input(?=[.(<,])',
      w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'required', k:'ng',
      w:{ en:'Part of Angular’s API: <code>input.required</code>.', ar:'جزء من API أنجولار: <code>input.required</code>.' } },
    { n:'computed', k:'ng',
      w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'class', k:'ng', only:['tpl'], re:'(?<=\\[)class(?=[.\\]])',
      w:{ en:'Angular’s class binding: <code>[class.x]</code> for one class, <code>[class]</code> for many. The class names after the dot or inside the object are yours.',
          ar:'الـ binding بتاع أنجولار للـ class: <code>[class.x]</code> لـ class واحدة، و<code>[class]</code> لكذا واحدة. أسماء الـ class اللي بعد النقطة أو جوه الـ object بتاعتك.' } },
    { n:'style', k:'ng', only:['tpl'], re:'(?<=\\[)style(?=\\.)',
      w:{ en:'Angular’s style binding. The CSS property after it (<code>width</code>, <code>color</code>) is CSS’s, and <code>.%</code> is the unit.',
          ar:'الـ binding بتاع أنجولار للـ style. الـ property اللي بعده (<code>width</code>، <code>color</code>) بتاعة CSS، و<code>.%</code> هي الوحدة.' } },
    { n:':host', k:'ng', re:'(?<=^\\s*):host(?![\\w$-])',
      w:{ en:'Angular’s selector for the component’s own tag (<code>&lt;app-card&gt;</code>). Type it exactly.',
          ar:'الـ selector بتاع أنجولار للتاج بتاع الـ component نفسه (<code>&lt;app-card&gt;</code>). اكتبه زي ما هو.' } },
    { n:':host-context', k:'ng',
      w:{ en:'Angular’s selector for “when something above me has this class”.',
          ar:'الـ selector بتاع أنجولار لـ “لما حاجة فوقي في الصفحة يبقى عليها الـ class ده”.' } },
    { n:'::ng-deep', k:'ng', re:'(?<=^\\s*)::ng-deep(?![\\w$-])',
      w:{ en:'Angular’s (deprecated) escape hatch that switches scoping off for the rest of the rule.',
          ar:'مخرج الطوارئ بتاع أنجولار (وهو deprecated) اللي بيقفل الـ scoping لباقي الـ rule.' } },
    { n:':root', k:'ng',
      w:{ en:'CSS’s own selector for the <code>&lt;html&gt;</code> element: the usual home for global variables.',
          ar:'selector بتاع CSS نفسها لعنصر <code>&lt;html&gt;</code>: المكان المعتاد للـ variables العامة.' } },
    { n:'var', k:'ng',
      w:{ en:'CSS’s function that reads a custom property. The second value is the fallback.',
          ar:'الـ function بتاعة CSS اللي بتقرا custom property. القيمة التانية هي الـ fallback.' } },
    { n:'_nghost-abc123', k:'ng',
      w:{ en:'An attribute Angular generates and stamps on the host tag. You never type it.',
          ar:'attribute أنجولار بيعمله لوحده وبيختمه على تاج الـ host. انت عمرك ما بتكتبه.' } },
    { n:'_ngcontent-abc123', k:'ng',
      w:{ en:'An attribute Angular stamps on every element in the template, and adds to every selector in your CSS. That is the whole scoping trick.',
          ar:'attribute أنجولار بيختمه على كل عنصر في التمبلت، وبيضيفه لكل selector في الـ CSS بتاعك. ده السر كله بتاع الـ scoping.' } },
    { n:'third-party-widget', k:'ng',
      w:{ en:'A class from someone else’s library. Their HTML uses it, so you cannot rename it.',
          ar:'class من library حد تاني. الـ HTML بتاعهم هو اللي بيستخدمها، فمينفعش تغيّرها.' } },

    { n:'Card', k:'pub',
      w:{ en:'The component’s class name. Whoever lists it in <code>imports</code> follows a rename.',
          ar:'اسم كلاس الـ component. أي حد كاتبه في <code>imports</code> بيتغير معاه.' } },
    { n:'app-card', k:'pub', only:['ts','out'],
      w:{ en:'The selector: the tag every parent template types. <code>:host</code> styles this tag without naming it.',
          ar:'الـ selector: التاج اللي أي تمبلت أب بيكتبه. و<code>:host</code> بيستايل التاج ده من غير ما يكتب اسمه.' } },
    { n:'product', k:'pub',
      w:{ en:'An input. The parent sets it with <code>[product]</code>, so both files change together.',
          ar:'input. الأب بيحطه بـ <code>[product]</code>، فالملفين بيتغيروا مع بعض.' } },
    { n:'Product', k:'pub',
      w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'stock', k:'pub',
      w:{ en:'A field on your <code>Product</code> type, so it changes with the type.',
          ar:'field في نوع الـ <code>Product</code> بتاعك، فبيتغير مع النوع.' } },
    { n:'soldOut', k:'mine',
      w:{ en:'A computed the component uses in its own template. Nobody outside reads it.',
          ar:'computed الـ component بيستخدمه في التمبلت بتاعه. محدش برّه بيقراه.' } },
    { n:'title', k:'pub', re:'(?<=\\.|")title(?= \\{|\\[|")',
      w:{ en:'A CSS class: <code>class="title"</code> in the template and <code>.title</code> in the stylesheet must match. (<code>product().title</code> is a data field, a different thing.)',
          ar:'CSS class: <code>class="title"</code> في التمبلت و<code>.title</code> في الـ stylesheet لازم يبقوا زي بعض. (و<code>product().title</code> field في الداتا، حاجة تانية.)' } },
    { n:'sold-out', k:'pub',
      w:{ en:'A CSS class the template toggles. The <code>.sold-out</code> rule in the stylesheet must use the same spelling.',
          ar:'CSS class التمبلت بيشغّلها ويطفيها. الـ rule بتاعة <code>.sold-out</code> في الـ stylesheet لازم تتكتب بنفس الطريقة.' } },
    { n:'featured', k:'pub', only:['css'],
      w:{ en:'A class the <em>parent</em> puts on <code>&lt;app-card class="featured"&gt;</code>. Rename it here and in every parent.',
          ar:'class الـ <em>أب</em> بيحطها على <code>&lt;app-card class="featured"&gt;</code>. غيّرها هنا وفي كل أب.' } },
    { n:'dark-theme', k:'pub',
      w:{ en:'A class some ancestor (usually the app shell) puts on the page. Both files must spell it the same.',
          ar:'class حاجة فوق في الصفحة (غالباً الـ app shell) بتحطها. الملفين لازم يكتبوها بنفس الطريقة.' } },
    { n:'--brand', k:'pub', as:'--koshary',
      w:{ en:'Your CSS variable, defined in <code>styles.css</code> and read by the button. Rename it in both.',
          ar:'الـ CSS variable بتاعتك، متعرّفة في <code>styles.css</code> والزرار بيقراها. غيّرها في الاتنين.' } },
    { n:'--radius', k:'pub', as:'--feteer',
      w:{ en:'Your CSS variable, defined globally and read by the button.',
          ar:'الـ CSS variable بتاعتك، متعرّفة global والزرار بيقراها.' } },
    { n:'--btn-bg', k:'pub', as:'--basbousa',
      w:{ en:'The button’s theming knob. The checkout overrides it by name, so both files change together.',
          ar:'زرار التحكم في شكل الزرار. الـ checkout بيغيّر قيمته بالاسم، فالملفين بيتغيروا مع بعض.' } },
    { n:'--btn-radius', k:'pub', as:'--falafel',
      w:{ en:'Another theming knob the checkout overrides by name.',
          ar:'زرار تحكم تاني الـ checkout بيغيّر قيمته بالاسم.' } },
    { n:'danger-zone', k:'pub', re:'(?<=^\\.)danger-zone(?![\\w$-])',
      w:{ en:'A CSS class the checkout template puts on a wrapper. The template and the stylesheet must match.',
          ar:'CSS class تمبلت الـ checkout بيحطها على wrapper. التمبلت والـ stylesheet لازم يبقوا زي بعض.' } },
  ]
}
};
