/* names for the components topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'components': {
  note: {
    en: 'A component has two public faces: its <b>class name</b> (which a parent lists in <code>imports</code>) and its <b>selector</b> (which a parent types as a tag). Its inputs are public too. Everything else inside it is yours alone.',
    ar: 'الـ component ليه وشّين عموميين: <b>اسم الكلاس</b> (اللي الأب بيحطه في <code>imports</code>) و<b>الـ selector</b> (اللي الأب بيكتبه كتاج). والـ inputs بتاعته عمومية برضه. أي حاجة تانية جواه بتاعتك انت لوحدك.'
  },
  names: [
    { n:'@Component', k:'ng',
      w:{ en:'Angular’s decorator: the label that turns a class into a component.',
          ar:'الـ decorator بتاع أنجولار: اللافتة اللي بتحوّل الكلاس لـ component.' } },
    { n:'selector', k:'ng',
      w:{ en:'An option key Angular reads. The tag name you give it is yours.',
          ar:'مفتاح إعداد أنجولار بيقراه. اسم التاج اللي بتحطه فيه بتاعك.' } },
    { n:'imports', k:'ng',
      w:{ en:'An option key Angular reads: the components this template may use. The class names inside it are yours.',
          ar:'مفتاح إعداد أنجولار بيقراه: الـ components اللي التمبلت ده مسموح له يستخدمها. أسماء الكلاسات اللي جواه بتاعتك.' } },
    { n:'templateUrl', k:'ng',
      w:{ en:'An option key Angular reads. The path you give it must match the real file name.',
          ar:'مفتاح إعداد أنجولار بيقراه. المسار اللي بتحطه لازم يبقى زي اسم الملف الحقيقي.' } },
    { n:'template', k:'ng',
      w:{ en:'An option key Angular reads: the HTML written inline instead of in a separate file.',
          ar:'مفتاح إعداد أنجولار بيقراه: الـ HTML مكتوب في نفس الملف بدل ملف لوحده.' } },
    { n:'styleUrl', k:'ng',
      w:{ en:'An option key Angular reads, for the component’s CSS file.',
          ar:'مفتاح إعداد أنجولار بيقراه، لملف الـ CSS بتاع الـ component.' } },
    { n:'input', k:'ng',
      w:{ en:'Angular’s function that creates an input. Only the property name on its left is yours.',
          ar:'الـ function بتاعة أنجولار اللي بتعمل input. اسم الـ property اللي على شمالها بس هو اللي بتاعك.' } },
    { n:'required', k:'ng',
      w:{ en:'Part of Angular’s API: <code>input.required</code> means the parent must set it.',
          ar:'جزء من API أنجولار: <code>input.required</code> معناها إن الأب لازم يحطه.' } },
    { n:'@for', k:'ng',
      w:{ en:'Angular’s loop in the template.', ar:'الـ loop بتاع أنجولار في التمبلت.' } },
    { n:'track', k:'ng',
      w:{ en:'Angular’s word inside <code>@for</code>: how to tell the items apart. The expression after it is yours.',
          ar:'كلمة أنجولار جوه <code>@for</code>: إزاي يفرّق بين العناصر. اللي بعدها بتاعك.' } },

    { n:'UserCard', k:'pub',
      w:{ en:'The card’s class name. The page imports it and lists it in <code>imports</code>, so both files change together.',
          ar:'اسم كلاس الكارت. الصفحة بتعمله import وبتحطه في <code>imports</code>، فالملفين بيتغيروا مع بعض.' } },
    { n:'app-user-card', k:'pub',
      w:{ en:'The card’s selector: the <code>selector</code> string and the tag in the page template must match.',
          ar:'الـ selector بتاع الكارت: النص في <code>selector</code> والتاج في تمبلت الصفحة لازم يبقوا زي بعض.' } },
    { n:'name', k:'pub', only:['cts','chtml','phtml'], re:'(?<![\\w$.-])name(?![\\w$-])',
      w:{ en:'The card’s input. The page sets it with <code>[name]</code>, so both files change together. The <code>p.name</code> on the right is a different thing: a field in your <code>people</code> data.',
          ar:'الـ input بتاع الكارت. الصفحة بتحطه بـ <code>[name]</code>، فالملفين بيتغيروا مع بعض. و<code>p.name</code> اللي على اليمين حاجة تانية: field في داتا <code>people</code> بتاعتك.' } },
    { n:'email', k:'pub', only:['cts','chtml','phtml'], re:'(?<![\\w$.-])email(?![\\w$-])',
      w:{ en:'The card’s second input, set with <code>[email]</code>. <code>p.email</code> is the data field, not this.',
          ar:'الـ input التاني بتاع الكارت، بيتحط بـ <code>[email]</code>. و<code>p.email</code> هو الـ field بتاع الداتا، مش ده.' } },
    { n:'Page', k:'pub',
      w:{ en:'The page’s class name. Whatever shows this page (a route or a parent) imports it by this name.',
          ar:'اسم كلاس الصفحة. أي حاجة بتعرض الصفحة دي (route أو أب) بتعملها import بالاسم ده.' } },
    { n:'app-page', k:'pub',
      w:{ en:'The page’s selector. Any parent that uses it as a tag must match.',
          ar:'الـ selector بتاع الصفحة. أي أب بيستخدمه كتاج لازم يبقى زيه.' } },
    { n:'people', k:'mine',
      w:{ en:'The page’s own data, read by its own template.', ar:'الداتا بتاعة الصفحة، والتمبلت بتاعها بيقراها.' } },
    { n:'p', k:'mine', only:['phtml'],
      w:{ en:'The loop variable: the name you give each item inside <code>@for</code>.',
          ar:'متغير الـ loop: الاسم اللي بتدّيه لكل عنصر جوه <code>@for</code>.' } },

    { n:'StatTile', k:'pub',
      w:{ en:'The tile’s class name. Both dashboards list it in <code>imports</code>.',
          ar:'اسم كلاس التايل. الداشبوردين الاتنين بيحطوه في <code>imports</code>.' } },
    { n:'app-stat-tile', k:'pub',
      w:{ en:'The tile’s selector, typed as a tag in both dashboards.', ar:'الـ selector بتاع التايل، ومكتوب كتاج في الداشبوردين.' } },
    { n:'label', k:'pub', re:'(?<![\\w$.\\"-])label(?![\\w$-])',
      w:{ en:'An input. Both dashboards set it with <code>label="…"</code>. The CSS class <code>"label"</code> in the tile’s template is a separate name.',
          ar:'input. الداشبوردين بيحطوه بـ <code>label="…"</code>. والـ CSS class <code>"label"</code> اللي في تمبلت التايل اسم تاني منفصل.' } },
    { n:'value', k:'pub', only:['x1','x2','x3'],
      w:{ en:'An input, set with <code>[value]</code> or plain <code>value="…"</code>.',
          ar:'input، بيتحط بـ <code>[value]</code> أو بـ <code>value="…"</code> عادي.' } },
    { n:'delta', k:'pub',
      w:{ en:'An input with a default, set with <code>[delta]</code>.', ar:'input ليه قيمة افتراضية، بيتحط بـ <code>[delta]</code>.' } },
    { n:'revenue', k:'mine',
      w:{ en:'The sales dashboard’s own signal.', ar:'الـ signal بتاعة داشبورد المبيعات نفسه.' } },
    { n:'orders', k:'mine',
      w:{ en:'The sales dashboard’s own signal. The text <code>"Orders"</code> is just a label.',
          ar:'الـ signal بتاعة داشبورد المبيعات نفسه. والنص <code>"Orders"</code> مجرد كلام.' } },
  ]
}
};
