/* names for the data-binding topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'data-binding': {
  note: {
    en: 'Read a binding as <b>target = source</b>. The target inside <code>[ ]</code> or <code>( )</code> belongs to whoever owns the element: the browser for <code>&lt;input&gt;</code> and <code>&lt;button&gt;</code>, the child component for <code>&lt;app-rating&gt;</code>. The source in the quotes is your own component’s name.',
    ar: 'اقرا أي binding كده: <b>الهدف = المصدر</b>. الهدف اللي جوه <code>[ ]</code> أو <code>( )</code> بتاع اللي يملك العنصر: المتصفح في <code>&lt;input&gt;</code> و<code>&lt;button&gt;</code>، والـ component الابن في <code>&lt;app-rating&gt;</code>. والمصدر اللي بين العلامات هو اسم من الـ component بتاعك.'
  },
  names: [
    { n:'value', k:'ng',
      w:{ en:'The DOM property of an <code>&lt;input&gt;</code>: the text in the box. The browser owns the name.',
          ar:'الـ property بتاعة الـ <code>&lt;input&gt;</code> في الـ DOM: الكلام اللي في الخانة. الاسم بتاع المتصفح.' } },
    { n:'disabled', k:'ng',
      w:{ en:'The DOM property of a <code>&lt;button&gt;</code>. The browser owns the name.',
          ar:'الـ property بتاعة الـ <code>&lt;button&gt;</code> في الـ DOM. الاسم بتاع المتصفح.' } },
    { n:'attr', k:'ng', re:'(?<![\\w$-])attr(?=\\.(?!X\\]))',
      w:{ en:'Angular’s prefix: bind an HTML attribute instead of a DOM property.',
          ar:'البادئة بتاعة أنجولار: اربط attribute في الـ HTML بدل property في الـ DOM.' } },
    { n:'aria-label', k:'ng',
      w:{ en:'An HTML attribute name, read by screen readers. The browser owns it.',
          ar:'اسم attribute في الـ HTML، بتقراه برامج قراءة الشاشة. بتاع المتصفح.' } },
    { n:'colspan', k:'ng',
      w:{ en:'An HTML attribute of <code>&lt;td&gt;</code>. It has no matching DOM property, which is why it needs <code>attr.</code>.',
          ar:'attribute في الـ HTML بتاع <code>&lt;td&gt;</code>. ملوش property مقابلها في الـ DOM، عشان كده محتاج <code>attr.</code>.' } },
    { n:'click', k:'ng',
      w:{ en:'The browser’s own event name.', ar:'اسم الـ event بتاع المتصفح نفسه.' } },
    { n:'input', k:'ng', re:'(?<=\\()input(?=\\))',
      w:{ en:'Here, the browser’s event that fires on every keystroke. Not Angular’s <code>input()</code> function.',
          ar:'هنا ده الـ event بتاع المتصفح اللي بيشتغل مع كل حرف بتكتبه. مش الـ function <code>input()</code> بتاعة أنجولار.' } },
    { n:'submit', k:'ng',
      w:{ en:'The browser’s event when a form is sent.', ar:'الـ event بتاع المتصفح لما الفورم بيتبعت.' } },
    { n:'keydown.escape', k:'ng',
      w:{ en:'The browser’s <code>keydown</code> event plus Angular’s key filter: only the Escape key.',
          ar:'الـ event <code>keydown</code> بتاع المتصفح زائد فلتر أنجولار للزراير: زرار Escape بس.' } },
    { n:'$event', k:'ng',
      w:{ en:'Angular’s fixed name, in an event binding only, for whatever the event carried.',
          ar:'اسم ثابت من أنجولار، جوه الـ event binding بس، لأي حاجة الـ event جايبها معاه.' } },
    { n:'$any', k:'ng',
      w:{ en:'Angular’s template helper that switches off type checking for one value.',
          ar:'مساعد في التمبلت من أنجولار بيقفل الـ type checking لقيمة واحدة.' } },
    { n:'target', k:'ng',
      w:{ en:'The DOM event’s property: the element the event happened on.',
          ar:'property في الـ event بتاع الـ DOM: العنصر اللي الـ event حصل عليه.' } },
    { n:'stopPropagation', k:'ng',
      w:{ en:'A DOM event method: do not let the click reach the parent elements.',
          ar:'ميثود في الـ event بتاع الـ DOM: متخلّيش الكليك يوصل للعناصر اللي فوق.' } },
    { n:'preventDefault', k:'ng',
      w:{ en:'A DOM event method: stop the browser’s own reaction (here, reloading the page).',
          ar:'ميثود في الـ event بتاع الـ DOM: وقّف رد فعل المتصفح نفسه (هنا، إنه يعمل reload للصفحة).' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'computed', k:'ng', w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'set', k:'ng', w:{ en:'A signal method: replace the value.', ar:'ميثود بتاعة الـ signal: بتستبدل القيمة.' } },
    { n:'input()', k:'ng', only:['sb2'], re:'(?<![\\w$<(-])input(?=\\()',
      w:{ en:'Angular’s function that creates an input. Same spelling as the <code>(input)</code> event, completely different thing.',
          ar:'الـ function بتاعة أنجولار اللي بتعمل input. نفس كتابة الـ event <code>(input)</code>، بس حاجة تانية خالص.' } },

    { n:'stars', k:'pub', re:'(?<![\\w$-])(?<!called\\s+)stars(?![\\w$-])', as:'apricot',
      w:{ en:'The rating component’s <code>model()</code> (or its input). The child declares it; this parent types it inside <code>[( )]</code>. Rename both sides.',
          ar:'الـ <code>model()</code> بتاع الـ rating component (أو الـ input بتاعه). الابن بيعلنه والأب ده بيكتبه جوه <code>[( )]</code>. غيّر الناحيتين.' } },
    { n:'starsChange', k:'pub', re:'(?<![\\w$-])(?<!called\\s+)starsChange(?![\\w$-])', as:'apricotChange',
      w:{ en:'The matching output. The <code>Change</code> ending is Angular’s rule and must stay; the part before it must equal the input’s name.',
          ar:'الـ output اللي معاه. النهاية <code>Change</code> قاعدة من أنجولار ولازم تفضل؛ والجزء اللي قبلها لازم يبقى زي اسم الـ input بالظبط.' } },
    { n:'app-rating', k:'pub',
      w:{ en:'The rating component’s selector. Its <code>selector</code> string and this tag must match.',
          ar:'الـ selector بتاع الـ rating component. النص في <code>selector</code> والتاج ده لازم يبقوا زي بعض.' } },
    { n:'section', k:'pub',
      w:{ en:'The search box’s input. A parent may set it with <code>[section]</code>.',
          ar:'الـ input بتاع خانة البحث. أي أب يقدر يحطه بـ <code>[section]</code>.' } },
    { n:'term', k:'mine', re:'(?<![\\w$.-])(?<!\\svalue=")term(?![\\w$-])',
      w:{ en:'The component’s own signal. In <code>value="term()"</code> (no brackets) it is not coloured: there it is just text, not your name.',
          ar:'الـ signal بتاعة الـ component. في <code>value="term()"</code> (من غير أقواس) مش متلوّنة: هناك دي مجرد كلام، مش الاسم بتاعك.' } },
    { n:'score', k:'mine', w:{ en:'The parent’s own signal, handed to the rating two-way.', ar:'الـ signal بتاعة الأب، متسلّمة للـ rating في الاتجاهين.' } },
    { n:'busy', k:'mine', w:{ en:'The component’s own signal.', ar:'الـ signal بتاعة الـ component.' } },
    { n:'canSubmit', k:'mine', w:{ en:'A computed in the component.', ar:'computed في الـ component.' } },
    { n:'save', k:'mine', w:{ en:'The component’s own method.', ar:'الميثود بتاعة الـ component.' } },
    { n:'onSubmit', k:'mine',
      w:{ en:'The component’s own method. The <code>on</code> is a habit, not a rule.',
          ar:'الميثود بتاعة الـ component. الـ <code>on</code> عادة مش قاعدة.' } },
    { n:'results', k:'mine', re:'(?<![\\w$-])results(?=\\(| =)', w:{ en:'A computed in the component.', ar:'computed في الـ component.' } },
  ]
}
};
