/* names for the reactive forms topic. Format: see inputs-outputs.mjs. */
export default {
'forms': {
  note: {
    en: 'Control names are the <b>orange</b> glue of reactive forms. The key in <code>group({ … })</code>, the <code>formControlName</code> in the template, <code>controls.x</code> and any string like <code>\'password\'</code> must all be the same word. A typo in the template throws at runtime, not at compile time.',
    ar: 'أسماء الـ controls هي الصمغ <b>البرتقاني</b> في الـ reactive forms. المفتاح في <code>group({ … })</code>، والـ <code>formControlName</code> في التمبلت، و<code>controls.x</code>، وأي نص زي <code>\'password\'</code>، لازم كلهم يبقوا نفس الكلمة. غلطة في التمبلت بتضرب وقت التشغيل، مش وقت الـ compile.'
  },
  names: [
    { n:'FormBuilder', k:'ng', w:{ en:'Angular’s service that builds forms with less typing.', ar:'الـ service بتاعة أنجولار اللي بتبني الفورمز بكتابة أقل.' } },
    { n:'Validators', k:'ng', w:{ en:'Angular’s ready-made validators: <code>required</code>, <code>email</code>, <code>minLength</code>…', ar:'الـ validators الجاهزة بتاعة أنجولار: <code>required</code>، <code>email</code>، <code>minLength</code>…' } },
    { n:'nonNullable', k:'ng', w:{ en:'A <code>FormBuilder</code> property: reset goes back to the initial value, not <code>null</code>.', ar:'property في <code>FormBuilder</code>: الـ reset بيرجع للقيمة الأولانية، مش <code>null</code>.' } },
    { n:'group', k:'ng', re:'(?<=\\.)group(?=\\()',
      w:{ en:'The <code>FormBuilder</code> method that makes a <code>FormGroup</code>. The parameter called <code>group</code> in <code>matchFields</code> is yours and is left alone.',
          ar:'الميثود في <code>FormBuilder</code> اللي بتعمل <code>FormGroup</code>. والـ parameter اللي اسمه <code>group</code> في <code>matchFields</code> بتاعك ومش بيتلمس.' } },
    { n:'required', k:'ng', re:'(?<=\\.|\')required(?![\\w$-])', w:{ en:'Angular’s validator, and the fixed error key it sets: <code>e[\'required\']</code>.', ar:'الـ validator بتاع أنجولار، ومفتاح الـ error الثابت اللي بيحطه: <code>e[\'required\']</code>.' } },
    { n:'minLength', k:'ng', w:{ en:'Angular’s validator. Note the capital <code>L</code> here, unlike the HTML attribute.', ar:'الـ validator بتاع أنجولار. خد بالك من الـ <code>L</code> الكابيتال هنا، عكس الـ attribute بتاع HTML.' } },
    { n:'validators', k:'ng', w:{ en:'An option key Angular reads: validators for the whole group.', ar:'مفتاح إعداد أنجولار بيقراه: validators للـ group كله.' } },
    { n:'getRawValue', k:'ng', w:{ en:'A form method from Angular.', ar:'ميثود في الفورم من أنجولار.' } },
    { n:'ValidatorFn', k:'ng', w:{ en:'Angular’s type for a validator function.', ar:'الـ type بتاع أنجولار لـ function الـ validator.' } },
    { n:'AbstractControl', k:'ng', w:{ en:'Angular’s base type for any control or group.', ar:'الـ type الأساسي في أنجولار لأي control أو group.' } },
    { n:'value', k:'ng', re:'(?<=\\.)(?<!this\\.)value(?![\\w$-])',
      w:{ en:'The property every control has. Your own <code>value</code> signal, read as <code>this.value()</code>, is a different thing.',
          ar:'الـ property اللي موجودة في أي control. والـ signal <code>value</code> بتاعتك، اللي بتتقري <code>this.value()</code>، حاجة تانية.' } },
    { n:'formGroup', k:'ng', w:{ en:'Angular’s directive that connects a <code>&lt;form&gt;</code> to your group.', ar:'الـ directive بتاع أنجولار اللي بيوصل <code>&lt;form&gt;</code> بالـ group بتاعك.' } },
    { n:'ngSubmit', k:'ng', w:{ en:'Angular’s form event.', ar:'الـ event بتاع أنجولار للفورم.' } },
    { n:'formControlName', k:'ng', w:{ en:'Angular’s directive. The string you give it is yours and must match a key in the group.', ar:'الـ directive بتاع أنجولار. النص اللي بتديهوله بتاعك ولازم يطابق مفتاح في الـ group.' } },
    { n:'controls', k:'ng', w:{ en:'The property that holds a group’s controls by name.', ar:'الـ property اللي شايلة الـ controls بتاعة الـ group بأساميها.' } },
    { n:'@let', k:'ng', w:{ en:'Angular’s template syntax for a local variable. The name after it is yours.', ar:'الـ syntax بتاع أنجولار لمتغير محلي في التمبلت. الاسم اللي بعده بتاعك.' } },
    { n:'touched', k:'ng', w:{ en:'A state every control has.', ar:'حالة موجودة في أي control.' } },
    { n:'invalid', k:'ng', w:{ en:'A state every control and group has.', ar:'حالة موجودة في أي control وأي group.' } },
    { n:'errors', k:'ng', w:{ en:'The object where each failing validator puts its key.', ar:'الـ object اللي كل validator فاشل بيحط فيه مفتاحه.' } },
    { n:'valueChanges', k:'ng', w:{ en:'An observable every control has.', ar:'observable موجود في أي control.' } },
    { n:'setValidators', k:'ng', w:{ en:'A control method from Angular.', ar:'ميثود في الـ control من أنجولار.' } },
    { n:'updateValueAndValidity', k:'ng', w:{ en:'A control method from Angular: re-check now.', ar:'ميثود في الـ control من أنجولار: اعمل check تاني دلوقتي.' } },

    { n:'form', k:'mine', re:'(?<![\\w$<\\/-])form(?![\\w$-])',
      w:{ en:'The component’s own property holding the group. The <code>&lt;form&gt;</code> tag is the browser’s and is left alone.',
          ar:'الـ property بتاعة الـ component اللي شايلة الـ group. وتاج <code>&lt;form&gt;</code> بتاع المتصفح ومش بيتلمس.' } },
    { n:'fb', k:'mine', w:{ en:'The field you store <code>FormBuilder</code> in.', ar:'الـ field اللي بتحط فيه <code>FormBuilder</code>.' } },
    { n:'name', k:'pub', only:['ts'],
      w:{ en:'A control name. Its template would use <code>formControlName="name"</code>, so both change together.',
          ar:'اسم control. التمبلت بتاعه هيستخدم <code>formControlName="name"</code>، فالاتنين بيتغيروا مع بعض.' } },
    { n:'email', k:'pub', only:['ts','tpl'],
      re:'(?<=^\\s*)email(?=\\s*:)|(?<=formControlName=")email(?=")|(?<=controls\\.)email(?![\\w$-])',
      w:{ en:'A control name: the key in the group, <code>formControlName="email"</code> and <code>controls.email</code>. The other <code>email</code>s (<code>Validators.email</code>, <code>type="email"</code>, the <code>e[\'email\']</code> error key) are Angular’s or the browser’s. <code>@let email</code> is a separate template variable of your own that happens to share the word.',
          ar:'اسم control: المفتاح في الـ group، و<code>formControlName="email"</code>، و<code>controls.email</code>. وباقي الـ <code>email</code> (<code>Validators.email</code>، <code>type="email"</code>، مفتاح الـ error <code>e[\'email\']</code>) بتوع أنجولار أو المتصفح. و<code>@let email</code> متغير تمبلت تاني بتاعك صدفة واخد نفس الكلمة.' } },
    { n:'password', k:'pub',
      w:{ en:'A control name. The string <code>\'password\'</code> passed to <code>matchFields</code> must match it, and nothing checks that.',
          ar:'اسم control. النص <code>\'password\'</code> اللي بيتبعت لـ <code>matchFields</code> لازم يطابقه، ومحدش بيتأكد من ده.' } },
    { n:'confirm', k:'pub', w:{ en:'A control name, also passed as a string to <code>matchFields</code>.', ar:'اسم control، وبيتبعت كنص لـ <code>matchFields</code> كمان.' } },
    { n:'plan', k:'pub', w:{ en:'A control name, read back as <code>value().plan</code>.', ar:'اسم control، وبيتقري تاني كـ <code>value().plan</code>.' } },
    { n:'country', k:'pub', re:'(?<=^\\s*)country(?=\\s*:)|(?<=formControlName=")country|(?<=\\.)country(?![\\w$-])',
      w:{ en:'A control name used in both files. The <code>country</code> parameter of <code>applyCountryRules</code> is a separate local name and is left alone.',
          ar:'اسم control مستخدم في الملفين. والـ parameter <code>country</code> بتاع <code>applyCountryRules</code> اسم محلي تاني ومش بيتلمس.' } },
    { n:'governorate', k:'pub', w:{ en:'A control name: the group key, <code>controls.governorate</code> and <code>formControlName</code>.', ar:'اسم control: مفتاح الـ group، و<code>controls.governorate</code>، و<code>formControlName</code>.' } },
    { n:'postcode', k:'pub', w:{ en:'A control name used in both files.', ar:'اسم control مستخدم في الملفين.' } },
    { n:'mismatch', k:'pub',
      w:{ en:'An error key you invented in your validator. The template must ask for the same key.',
          ar:'مفتاح error انت اخترعته في الـ validator بتاعك. التمبلت لازم يسأل على نفس المفتاح.' } },
    { n:'matchFields', k:'pub', w:{ en:'Your exported validator. Every file that imports it follows a rename.', ar:'الـ validator بتاعك اللي بتعمله export. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'submit', k:'mine', w:{ en:'The component’s method, called from its own template.', ar:'ميثود الـ component، بتتنادى من التمبلت بتاعه.' } },
    { n:'applyCountryRules', k:'mine', w:{ en:'A private method of the component.', ar:'ميثود خاصة في الـ component.' } },
  ]
}
};
