/* names for the global state topic (plain signals, NgRx SignalStore, classic NgRx).
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'global-state': {
  note: {
    en: 'Every function that starts with <code>with</code>, <code>create</code> or <code>patch</code> belongs to NgRx. The names <i>inside</i> them (the state keys, computed names, method names, action names) are yours, but components read them, so they are <b>orange</b>: rename them in the store and in every component together.',
    ar: 'أي function بتبدأ بـ <code>with</code> أو <code>create</code> أو <code>patch</code> دي بتاعة NgRx. الأسماء اللي <i>جواها</i> (مفاتيح الـ state، أسماء الـ computed، أسماء الميثودز، أسماء الـ actions) بتاعتك، بس الـ components بتقراها، فهي <b>برتقاني</b>: غيّرها في الـ store وفي كل component مع بعض.'
  },
  names: [
    { n:'signalStore', k:'ng',
      w:{ en:'NgRx’s function that builds a store class out of the <code>with…</code> pieces you pass it.',
          ar:'الـ function بتاعة NgRx اللي بتبني كلاس store من حتت الـ <code>with…</code> اللي بتديهاله.' } },
    { n:'withState', k:'ng',
      w:{ en:'NgRx’s piece for the starting state. The keys inside it are yours; each one becomes a signal on the store.',
          ar:'الحتة بتاعة NgRx للـ state الأولانية. المفاتيح اللي جواها بتاعتك؛ وكل مفتاح بيبقى signal على الـ store.' } },
    { n:'withComputed', k:'ng',
      w:{ en:'NgRx’s piece for derived values. The names on the left of each <code>computed</code> are yours.',
          ar:'الحتة بتاعة NgRx للقيم المشتقة. الأسماء اللي على شمال كل <code>computed</code> بتاعتك.' } },
    { n:'withMethods', k:'ng',
      w:{ en:'NgRx’s piece for the methods components call. The method names inside are yours.',
          ar:'الحتة بتاعة NgRx للميثودز اللي الـ components بتناديها. أسماء الميثودز اللي جواها بتاعتك.' } },
    { n:'patchState', k:'ng',
      w:{ en:'NgRx’s only way to change SignalStore state: pass the store and the keys that changed.',
          ar:'الطريقة الوحيدة في NgRx إنك تغيّر state الـ SignalStore: تديها الـ store والمفاتيح اللي اتغيرت.' } },
    { n:'@Injectable', k:'ng',
      w:{ en:'Angular’s decorator that makes a class a service you can <code>inject</code>.',
          ar:'الـ decorator بتاع أنجولار اللي بيخلي الكلاس service تقدر تعملها <code>inject</code>.' } },
    { n:'providedIn', k:'ng',
      w:{ en:'An option key Angular reads. <code>\'root\'</code> means one shared copy for the whole app.',
          ar:'مفتاح إعداد أنجولار بيقراه. <code>\'root\'</code> معناها نسخة واحدة متشاركة للتطبيق كله.' } },
    { n:'computed', k:'ng', w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'asReadonly', k:'ng',
      w:{ en:'A signal method: hands out a read-only view so only the service can write.',
          ar:'ميثود بتاعة الـ signal: بتطلّع نسخة للقراية بس، عشان الـ service بس هي اللي تكتب.' } },
    { n:'set', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتجيبلك service.' } },
    { n:'firstValueFrom', k:'ng',
      w:{ en:'RxJS’s helper that turns an Observable into a Promise you can <code>await</code>.',
          ar:'helper من RxJS بيحوّل الـ Observable لـ Promise تقدر تعمله <code>await</code>.' } },
    { n:'createAction', k:'ng', w:{ en:'Classic NgRx: declares an action. The string and the constant name are yours.', ar:'NgRx الكلاسيك: بتعلن action. النص واسم الثابت بتوعك.' } },
    { n:'props', k:'ng', w:{ en:'Classic NgRx: describes the data an action carries.', ar:'NgRx الكلاسيك: بتوصف الداتا اللي الـ action شايلها.' } },
    { n:'createReducer', k:'ng', w:{ en:'Classic NgRx: builds the pure function that turns (state, action) into new state.', ar:'NgRx الكلاسيك: بتبني الـ function اللي بتحوّل (state, action) لـ state جديدة.' } },
    { n:'on', k:'ng', only:['ngrx'],
      w:{ en:'Classic NgRx: inside a reducer, “when this action happens, do this”.', ar:'NgRx الكلاسيك: جوه الـ reducer، معناها “لما الـ action ده يحصل، اعمل كده”.' } },
    { n:'createSelector', k:'ng', w:{ en:'Classic NgRx: a memoised read from the store.', ar:'NgRx الكلاسيك: قراية من الـ store بتتحفظ نتيجتها.' } },
    { n:'createEffect', k:'ng', w:{ en:'Classic NgRx: where side effects such as HTTP calls live.', ar:'NgRx الكلاسيك: المكان اللي الـ side effects زي طلبات الـ HTTP بتعيش فيه.' } },
    { n:'functional', k:'ng', w:{ en:'An option key NgRx reads: this effect is a plain function, not a class.', ar:'مفتاح إعداد NgRx بيقراه: الـ effect ده function عادية مش كلاس.' } },
    { n:'Actions', k:'ng', w:{ en:'NgRx’s stream of every action dispatched in the app.', ar:'الـ stream بتاع NgRx اللي فيه كل action اتبعت في التطبيق.' } },
    { n:'ofType', k:'ng', w:{ en:'An NgRx operator: lets only the named actions through.', ar:'operator من NgRx: بيعدّي الـ actions اللي انت سميتها بس.' } },
    { n:'switchMap', k:'ng', w:{ en:'An RxJS operator.', ar:'operator من RxJS.' } },
    { n:'map', k:'ng', only:['ngrx'], w:{ en:'The RxJS operator, not the array method.', ar:'الـ operator بتاع RxJS، مش ميثود الـ array.' } },
    { n:'Store', k:'ng', w:{ en:'Classic NgRx’s store service. The capital <code>S</code> matters: your field <code>store</code> is a different name.', ar:'الـ service بتاعة الـ store في NgRx الكلاسيك. حرف <code>S</code> الكابيتال مهم: الـ field بتاعك <code>store</code> اسم تاني خالص.' } },
    { n:'selectSignal', k:'ng', w:{ en:'Classic NgRx: reads a selector as a signal.', ar:'NgRx الكلاسيك: بتقرا selector على هيئة signal.' } },
    { n:'dispatch', k:'ng', w:{ en:'Classic NgRx: sends an action to the store.', ar:'NgRx الكلاسيك: بتبعت action للـ store.' } },
    { n:'ngOnInit', k:'ng', w:{ en:'Angular’s lifecycle hook. Spell it exactly or it never runs.', ar:'lifecycle hook بتاع أنجولار. اكتبه بالظبط وإلا مش هيشتغل خالص.' } },

    { n:'TodosStore', k:'pub',
      w:{ en:'Your store’s class name. Every component that does <code>inject(TodosStore)</code> follows a rename.',
          ar:'اسم كلاس الـ store بتاعك. أي component بيعمل <code>inject(TodosStore)</code> بيتغير معاه.' } },
    { n:'todos', k:'pub', only:['sig','ngrx','x1','x2'],
      w:{ en:'A state key. The store turns it into <code>store.todos()</code> and components read it, so they change together. In classic NgRx it is also the key inside the action’s <code>props</code>.',
          ar:'مفتاح في الـ state. الـ store بيحوّله لـ <code>store.todos()</code> والـ components بتقراه، فبيتغيروا مع بعض. وفي NgRx الكلاسيك هو كمان المفتاح اللي جوه <code>props</code> بتاعة الـ action.' } },
    { n:'filter', k:'pub', re:'(?<![\\w$.-])filter(?![\\w$-])',
      w:{ en:'A state key, read as <code>filter()</code>. The <code>.filter(</code> on arrays is JavaScript’s and is not touched.',
          ar:'مفتاح في الـ state، بيتقري كـ <code>filter()</code>. و<code>.filter(</code> بتاعة الـ arrays دي بتاعة JavaScript ومش بتتلمس.' } },
    { n:'busy', k:'pub', w:{ en:'A state key. Components read <code>store.busy()</code>.', ar:'مفتاح في الـ state. الـ components بتقرا <code>store.busy()</code>.' } },
    { n:'visible', k:'pub', w:{ en:'Your computed. Components read <code>store.visible()</code>, so rename it there too.', ar:'الـ computed بتاعك. الـ components بتقرا <code>store.visible()</code>، فغيّره هناك كمان.' } },
    { n:'openCount', k:'pub', w:{ en:'Your computed. Every template that shows <code>store.openCount()</code> follows a rename.', ar:'الـ computed بتاعك. أي تمبلت بيعرض <code>store.openCount()</code> بيتغير معاه.' } },
    { n:'setFilter', k:'pub', w:{ en:'Your method. Components call <code>store.setFilter(…)</code>.', ar:'الميثود بتاعتك. الـ components بتنادي <code>store.setFilter(…)</code>.' } },
    { n:'load', k:'pub', w:{ en:'Your method. Components call <code>store.load()</code>.', ar:'الميثود بتاعتك. الـ components بتنادي <code>store.load()</code>.' } },
    { n:'_todos', k:'mine',
      w:{ en:'The private writable signal. Nothing outside the service sees it; the underscore is just a habit.',
          ar:'الـ signal الخاصة اللي بتتكتب. محدش برّه الـ service بيشوفها؛ والـ underscore دي مجرد عادة.' } },
    { n:'store', k:'mine',
      w:{ en:'Two local names: the parameter NgRx hands to <code>withMethods</code>, and the component’s own field. Both are yours to rename.',
          ar:'اسمين محليين: الـ parameter اللي NgRx بيديه لـ <code>withMethods</code>، والـ field بتاع الـ component نفسه. الاتنين تقدر تغيّرهم.' } },
    { n:'api', k:'mine', w:{ en:'A local name for the injected <code>TodoApi</code>.', ar:'اسم محلي للـ <code>TodoApi</code> اللي اتعمله inject.' } },
    { n:'TodoApi', k:'pub', w:{ en:'Your HTTP service class, written in another file.', ar:'كلاس الـ service بتاعك للـ HTTP، مكتوب في ملف تاني.' } },
    { n:'getAll', k:'pub', w:{ en:'A method on your <code>TodoApi</code>. Rename it there and here together.', ar:'ميثود في الـ <code>TodoApi</code> بتاعك. غيّرها هناك وهنا مع بعض.' } },
    { n:'Todo', k:'pub', w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'Filter', k:'pub', w:{ en:'Your type for the filter values.', ar:'النوع بتاعك لقيم الفلتر.' } },
    { n:'loadTodos', k:'pub', w:{ en:'An action. The reducer, the effect and the component that dispatches it all type this name.', ar:'action. الـ reducer والـ effect والـ component اللي بيبعته كلهم كاتبين الاسم ده.' } },
    { n:'loadTodosSuccess', k:'pub', w:{ en:'An action, created by the effect and handled by the reducer.', ar:'action، الـ effect بيعمله والـ reducer بيتعامل معاه.' } },
    { n:'selectTodos', k:'pub', w:{ en:'A selector. Components pass it to <code>selectSignal</code>.', ar:'selector. الـ components بتديه لـ <code>selectSignal</code>.' } },
    { n:'selectOpenCount', k:'pub', w:{ en:'A selector. Components pass it to <code>selectSignal</code>.', ar:'selector. الـ components بتديه لـ <code>selectSignal</code>.' } },
    { n:'todosReducer', k:'pub', w:{ en:'Your reducer, registered by name in the app config.', ar:'الـ reducer بتاعك، بيتسجل باسمه في إعدادات التطبيق.' } },
    { n:'loadEffect', k:'pub', w:{ en:'Your effect, registered by name with <code>provideEffects</code>.', ar:'الـ effect بتاعك، بيتسجل باسمه مع <code>provideEffects</code>.' } },
    { n:'actions$', k:'mine', w:{ en:'A local name for the injected <code>Actions</code> stream. The <code>$</code> is only a habit.', ar:'اسم محلي للـ stream بتاع <code>Actions</code>. والـ <code>$</code> مجرد عادة.' } },
  ]
}
};
