/* names for the HTTP topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'http': {
  note: {
    en: 'An interceptor is just a function Angular calls with two arguments. <code>req</code> and <code>next</code> are only the usual parameter names: Angular passes them by position, so you could call them anything. The methods you call on them (<code>clone</code>, <code>pipe</code>) are fixed.',
    ar: 'الـ interceptor ما هو إلا function أنجولار بيناديها بـ argumentين. <code>req</code> و<code>next</code> دول بس الأسامي المعتادة للـ parameters: أنجولار بيبعتهم بالترتيب، فتقدر تسميهم أي حاجة. أما الميثودز اللي بتناديها عليهم (<code>clone</code>، <code>pipe</code>) فثابتة.'
  },
  names: [
    { n:'provideHttpClient', k:'ng',
      w:{ en:'Angular’s function that switches HTTP on for the app.', ar:'الـ function بتاعة أنجولار اللي بتشغّل الـ HTTP في التطبيق.' } },
    { n:'withFetch', k:'ng', w:{ en:'Angular’s HTTP feature: use the browser’s <code>fetch</code>.', ar:'feature في الـ HTTP بتاع أنجولار: استخدم <code>fetch</code> بتاع المتصفح.' } },
    { n:'withInterceptors', k:'ng',
      w:{ en:'Angular’s HTTP feature that registers your interceptor functions, in order.',
          ar:'feature في الـ HTTP بتاع أنجولار بتسجّل الـ interceptor functions بتاعتك، بالترتيب.' } },
    { n:'HttpInterceptorFn', k:'ng',
      w:{ en:'Angular’s type for an interceptor function.', ar:'النوع بتاع أنجولار لـ interceptor function.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a dependency.', ar:'الـ function بتاعة أنجولار اللي بتديك dependency.' } },
    { n:'clone', k:'ng',
      w:{ en:'A method on Angular’s <code>HttpRequest</code>: make a changed copy.', ar:'ميثود في <code>HttpRequest</code> بتاع أنجولار: اعمل نسخة متعدلة.' } },
    { n:'setHeaders', k:'ng', w:{ en:'An option key <code>clone()</code> reads.', ar:'مفتاح إعداد <code>clone()</code> بيقراه.' } },
    { n:'Authorization', k:'ng',
      w:{ en:'The standard HTTP header name servers look for. Not Angular’s, but not yours either.',
          ar:'اسم الـ HTTP header القياسي اللي السيرفرات بتدوّر عليه. مش بتاع أنجولار، بس برضه مش بتاعك.' } },
    { n:'httpResource', k:'ng',
      w:{ en:'Angular’s signal-based HTTP fetch.', ar:'الـ HTTP fetch بتاع أنجولار اللي مبني على signals.' } },
    { n:'isLoading', k:'ng', w:{ en:'A signal every resource has.', ar:'signal موجودة في أي resource.' } },
    { n:'error', k:'ng', w:{ en:'A signal every resource has.', ar:'signal موجودة في أي resource.' } },
    { n:'value', k:'ng', w:{ en:'A signal every resource has: the loaded data.', ar:'signal موجودة في أي resource: الداتا اللي اتحمّلت.' } },
    { n:'reload', k:'ng', w:{ en:'A method every resource has.', ar:'ميثود موجودة في أي resource.' } },
    { n:'input', k:'ng', re:'(?<![\\w$<(-])input(?=[.(<,])',
      w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'@if', k:'ng', w:{ en:'Angular’s template control flow.', ar:'الـ control flow بتاع أنجولار في التمبلت.' } },
    { n:'@else', k:'ng', w:{ en:'Angular’s template control flow.', ar:'الـ control flow بتاع أنجولار في التمبلت.' } },
    { n:'toSignal', k:'ng', w:{ en:'Angular’s bridge from an Observable to a signal.', ar:'الكوبري بتاع أنجولار من Observable لـ signal.' } },
    { n:'toObservable', k:'ng', w:{ en:'Angular’s bridge from a signal to an Observable.', ar:'الكوبري بتاع أنجولار من signal لـ Observable.' } },
    { n:'initialValue', k:'ng', w:{ en:'An option key <code>toSignal</code> reads.', ar:'مفتاح إعداد <code>toSignal</code> بيقراه.' } },
    { n:'pipe', k:'ng', w:{ en:'RxJS’s method for chaining operators.', ar:'ميثود RxJS لتوصيل الـ operators ورا بعض.' } },
    { n:'switchMap', k:'ng',
      w:{ en:'An RxJS operator: switch to a new request and cancel the old one.', ar:'operator من RxJS: روح للـ request الجديد والغي القديم.' } },
    { n:'debounceTime', k:'ng', w:{ en:'An RxJS operator: wait until the typing stops.', ar:'operator من RxJS: استنى لحد ما الكتابة تقف.' } },
    { n:'distinctUntilChanged', k:'ng', w:{ en:'An RxJS operator: skip repeats.', ar:'operator من RxJS: فوّت التكرار.' } },
    { n:'firstValueFrom', k:'ng', w:{ en:'RxJS’s function that turns an Observable into a Promise.', ar:'الـ function بتاعة RxJS اللي بتحوّل Observable لـ Promise.' } },
    { n:'get', k:'ng', w:{ en:'An <code>HttpClient</code> method.', ar:'ميثود في <code>HttpClient</code>.' } },
    { n:'post', k:'ng', w:{ en:'An <code>HttpClient</code> method.', ar:'ميثود في <code>HttpClient</code>.' } },

    { n:'authInterceptor', k:'pub',
      w:{ en:'Your interceptor, exported from its file and listed in <code>withInterceptors</code>.',
          ar:'الـ interceptor بتاعك، متعمله export من الملف بتاعه ومكتوب في <code>withInterceptors</code>.' } },
    { n:'errorInterceptor', k:'pub',
      w:{ en:'Another interceptor of yours, defined in its own file.', ar:'interceptor تاني بتاعك، متعرّف في ملفه.' } },
    { n:'req', k:'mine',
      w:{ en:'The first parameter. Angular passes it by position, so the name is yours.',
          ar:'أول parameter. أنجولار بيبعته بالترتيب، فالاسم بتاعك.' } },
    { n:'next', k:'mine',
      w:{ en:'The second parameter: “hand the request on”. A convention, not a rule; rename it and every call inside follows.',
          ar:'تاني parameter: “عدّي الـ request للي بعده”. ده عُرف مش قاعدة؛ غيّره وكل النداءات جوه تتغير معاه.' } },
    { n:'token', k:'mine', re:'(?<![\\w$.-])token(?![\\w$-])',
      w:{ en:'A local variable. (<code>.token()</code> on <code>Session</code> is the service’s method, a different name.)',
          ar:'variable محلي. (و<code>.token()</code> اللي في <code>Session</code> ميثود الـ service، اسم تاني.)' } },
    { n:'Session', k:'pub', w:{ en:'Your service class.', ar:'كلاس الـ service بتاعك.' } },
    { n:'UserPage', k:'pub', w:{ en:'Your component class.', ar:'كلاس الـ component بتاعك.' } },
    { n:'id', k:'pub', re:'(?<=readonly |this\\.)id(?![\\w$-])',
      w:{ en:'An input filled by the route’s <code>:id</code>, so the route path follows a rename. The <code>id</code> inside <code>switchMap(id =&gt; …)</code> is a separate parameter.',
          ar:'input بيتملي من <code>:id</code> بتاع الـ route، فالـ path بيتغير معاه. و<code>id</code> اللي جوه <code>switchMap(id =&gt; …)</code> parameter تاني منفصل.' } },
    { n:'user', k:'mine', re:'(?<![\\w$-])(?<!this )user(?![\\w$-])',
      w:{ en:'The component’s resource, read only by its own template.', ar:'الـ resource بتاع الـ component، والتمبلت بتاعه بس اللي بيقراه.' } },
    { n:'User', k:'pub', w:{ en:'Your data type.', ar:'نوع الداتا بتاعك.' } },
    { n:'http', k:'mine', re:'(?<=this\\.)http(?![\\w$-])',
      w:{ en:'Your property holding the injected <code>HttpClient</code>. Any name works.',
          ar:'الـ property بتاعتك اللي شايلة الـ <code>HttpClient</code> المتعمله inject. أي اسم ينفع.' } },
    { n:'ProductSearch', k:'pub', w:{ en:'Your component class.', ar:'كلاس الـ component بتاعك.' } },
    { n:'Product', k:'pub', w:{ en:'Your data type.', ar:'نوع الداتا بتاعك.' } },
    { n:'term', k:'mine', w:{ en:'The component’s own signal.', ar:'الـ signal بتاعة الـ component نفسه.' } },
    { n:'settled', k:'mine', w:{ en:'The component’s own debounced value.', ar:'القيمة الـ debounced بتاعة الـ component نفسه.' } },
    { n:'results', k:'mine', w:{ en:'The component’s resource.', ar:'الـ resource بتاع الـ component.' } },
    { n:'save', k:'mine', w:{ en:'The component’s own method.', ar:'ميثود الـ component نفسه.' } },
  ]
}
};
