/* names for the HTTP basics topic. Format: see inputs-outputs.mjs. */
export default {
'http-basics': {
  note: {
    en: '<code>get</code>, <code>post</code>, <code>patch</code> and <code>delete</code> are <code>HttpClient</code>’s. The methods you wrap them in (<code>getAll</code>, <code>create</code>, <code>remove</code>) are yours, and <b>orange</b>, because every component that calls the service types them.',
    ar: '<code>get</code> و<code>post</code> و<code>patch</code> و<code>delete</code> بتوع <code>HttpClient</code>. الميثودز اللي بتلفّهم فيها (<code>getAll</code>، <code>create</code>، <code>remove</code>) بتاعتك، و<b>برتقاني</b>، عشان أي component بينادي الـ service بيكتبها.'
  },
  names: [
    { n:'provideHttpClient', k:'ng', w:{ en:'Angular’s function that makes <code>HttpClient</code> available. Forget it and you get NG0201.', ar:'الـ function بتاعة أنجولار اللي بتخلّي <code>HttpClient</code> موجود. لو نسيتها هيطلعلك NG0201.' } },
    { n:'withFetch', k:'ng', w:{ en:'Angular’s option: send requests with the browser’s <code>fetch</code>.', ar:'إعداد من أنجولار: ابعت الطلبات بـ <code>fetch</code> بتاع المتصفح.' } },
    { n:'HttpClient', k:'ng', w:{ en:'Angular’s HTTP service.', ar:'الـ service بتاعة أنجولار للـ HTTP.' } },
    { n:'HttpParams', k:'ng', w:{ en:'Angular’s class for building a query string safely.', ar:'الكلاس بتاع أنجولار لبناء الـ query string بأمان.' } },
    { n:'get', k:'ng', w:{ en:'An <code>HttpClient</code> method: an HTTP GET.', ar:'ميثود في <code>HttpClient</code>: طلب HTTP GET.' } },
    { n:'post', k:'ng', w:{ en:'An <code>HttpClient</code> method: an HTTP POST.', ar:'ميثود في <code>HttpClient</code>: طلب HTTP POST.' } },
    { n:'patch', k:'ng', re:'(?<=\\.)patch(?![\\w$-])',
      w:{ en:'An <code>HttpClient</code> method. The parameter called <code>patch</code> next to it is yours and is left alone.',
          ar:'ميثود في <code>HttpClient</code>. والـ parameter اللي اسمه <code>patch</code> جنبها بتاعك ومش بيتلمس.' } },
    { n:'delete', k:'ng', w:{ en:'An <code>HttpClient</code> method: an HTTP DELETE.', ar:'ميثود في <code>HttpClient</code>: طلب HTTP DELETE.' } },
    { n:'set', k:'ng', w:{ en:'A method of <code>HttpParams</code>, and of signals. Either way, not yours.', ar:'ميثود في <code>HttpParams</code>، وفي الـ signals كمان. في الحالتين مش بتاعتك.' } },
    { n:'params', k:'ng',
      w:{ en:'The option key <code>HttpClient</code> reads. <code>{ params }</code> is shorthand for <code>{ params: params }</code>, so the variable has to share the name. Rename the variable and write <code>{ params: yours }</code>.',
          ar:'مفتاح الإعداد اللي <code>HttpClient</code> بيقراه. <code>{ params }</code> اختصار لـ <code>{ params: params }</code>، فالمتغير لازم ياخد نفس الاسم. لو غيّرت المتغير اكتب <code>{ params: yours }</code>.' } },
    { n:'subscribe', k:'ng', w:{ en:'RxJS’s method. Nothing is sent until something subscribes.', ar:'ميثود RxJS. مفيش حاجة بتتبعت لحد ما حد يعمل subscribe.' } },
    { n:'next', k:'ng',
      w:{ en:'A key RxJS reads in the object you pass to <code>subscribe</code>. So are <code>error</code> and <code>complete</code>.',
          ar:'مفتاح RxJS بيقراه في الـ object اللي بتبعته لـ <code>subscribe</code>. وكمان <code>error</code> و<code>complete</code>.' } },
    { n:'complete', k:'ng', w:{ en:'An observer key RxJS reads: runs when the request finishes.', ar:'مفتاح observer بيقراه RxJS: بيشتغل لما الطلب يخلص.' } },
    { n:'toSignal', k:'ng', w:{ en:'Angular’s function that subscribes for you and gives back a signal.', ar:'الـ function بتاعة أنجولار اللي بتعمل subscribe بدالك وترجعلك signal.' } },
    { n:'initialValue', k:'ng', w:{ en:'An option key <code>toSignal</code> reads.', ar:'مفتاح إعداد <code>toSignal</code> بيقراه.' } },
    { n:'firstValueFrom', k:'ng', w:{ en:'RxJS’s function that turns an observable into a Promise.', ar:'function من RxJS بتحوّل الـ observable لـ Promise.' } },

    { n:'ProductService', k:'pub', w:{ en:'The service’s class name. Every file that injects it follows a rename.', ar:'اسم كلاس الـ service. أي ملف بيعمله inject بيتغير معاه.' } },
    { n:'Product', k:'pub', re:'(?<![\\w$\'-])Product(?![\\w$-])', w:{ en:'Your data type. It must describe what the server really sends.', ar:'نوع الداتا بتاعك. لازم يوصف اللي السيرفر بيبعته فعلاً.' } },
    { n:'NewProduct', k:'pub', w:{ en:'Your data type for a product that has no id yet.', ar:'نوع الداتا بتاعك لمنتج لسه مالوش id.' } },
    { n:'getAll', k:'pub', w:{ en:'Your service method. Every component that calls it follows a rename.', ar:'ميثود الـ service بتاعتك. أي component بيناديها بيتغير معاها.' } },
    { n:'getOne', k:'pub', w:{ en:'Your service method.', ar:'ميثود الـ service بتاعتك.' } },
    { n:'create', k:'pub', w:{ en:'Your service method. It wraps <code>http.post</code>; the name is free.', ar:'ميثود الـ service بتاعتك. بتلف <code>http.post</code>؛ والاسم حر.' } },
    { n:'update', k:'pub', only:['svc'],
      w:{ en:'Your service method. (The <code>.update</code> on a signal in the components is Angular’s and is left alone.)',
          ar:'ميثود الـ service بتاعتك. (والـ <code>.update</code> بتاعة الـ signal في الـ components بتاعة أنجولار ومش بتتلمس.)' } },
    { n:'remove', k:'pub',
      w:{ en:'Your service method. The second <code>Products</code> also names its own method <code>remove</code>, which calls it; the two are separate and only share a name.',
          ar:'ميثود الـ service بتاعتك. و<code>Products</code> التانية سمّت ميثود عندها <code>remove</code> برضه، وهي اللي بتناديها؛ الاتنين منفصلين وبس ليهم نفس الاسم.' } },
    { n:'http', k:'mine', re:'(?<![\\w$\\/-])http(?![\\w$-])',
      w:{ en:'The field you store <code>HttpClient</code> in.', ar:'الـ field اللي بتحط فيه <code>HttpClient</code>.' } },
    { n:'base', k:'mine', w:{ en:'The service’s own private field.', ar:'الـ field الخاص بتاع الـ service.' } },
    { n:'api', k:'mine', re:'(?<![\\w$\\/-])api(?![\\w$\\/-])',
      w:{ en:'The field each component stores <code>ProductService</code> in. <code>/api/</code> in the URLs is the server’s path, not this.',
          ar:'الـ field اللي كل component بيحط فيه <code>ProductService</code>. و<code>/api/</code> في الـ URLs ده مسار السيرفر، مش ده.' } },
    { n:'products', k:'mine', only:['cmp'],
      w:{ en:'The component’s own signal.', ar:'الـ signal بتاعة الـ component نفسه.' } },
    { n:'products$', k:'mine', w:{ en:'The component’s own observable. The <code>$</code> is a habit, not a rule.', ar:'الـ observable بتاع الـ component نفسه. الـ <code>$</code> عادة، مش قاعدة.' } },
    { n:'list', k:'mine', w:{ en:'The component’s own signal, read by its own template.', ar:'الـ signal بتاعة الـ component، والتمبلت بتاعه بيقراها.' } },
    { n:'loading', k:'mine', w:{ en:'The component’s own signal.', ar:'الـ signal بتاعة الـ component نفسه.' } },
    { n:'error', k:'mine', re:'(?<![\\w$\'-])error(?!\\s*:)(?![\\w$\'-])',
      w:{ en:'The component’s own signal. The <code>error:</code> key in <code>subscribe({...})</code> is RxJS’s and is left alone.',
          ar:'الـ signal بتاعة الـ component نفسه. ومفتاح <code>error:</code> في <code>subscribe({...})</code> بتاع RxJS ومش بيتلمس.' } },
  ]
}
};
