/* names for the input() / output() / model() topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'inputs-outputs': {
  note: {
    en: 'Every <b>orange</b> name is a promise between two files: the child declares it and the parent types it. Rename one side only and the binding silently stops working. Every <b>green</b> name lives inside one component, so rename it as you like.',
    ar: 'كل اسم <b>برتقاني</b> ده وعد بين ملفين: الابن بيعلنه والأب بيكتبه. لو غيّرت ناحية واحدة بس الربط هيبطل يشتغل من غير ما حد يقولك. وكل اسم <b>أخضر</b> عايش جوه component واحد، فغيّره براحتك.'
  },
  names: [
    { n:'input', k:'ng', re:'(?<![\\w$<(-])input(?=[.(<,])',
      w:{ en:'Angular’s function that creates an input. Only the property name on its left is yours.',
          ar:'الـ function بتاعة أنجولار اللي بتعمل input. اسم الـ property اللي على شمالها بس هو اللي بتاعك.' } },
    { n:'output', k:'ng', re:'(?<![\\w$<\\/-])output(?![\\w$-])',
      w:{ en:'Angular’s function that creates an event the parent can listen to.',
          ar:'الـ function بتاعة أنجولار اللي بتعمل event الأب يقدر يسمعه.' } },
    { n:'model', k:'ng',
      w:{ en:'Angular’s function for a two-way value: an input and an output in one.',
          ar:'الـ function بتاعة أنجولار لقيمة في الاتجاهين: input وoutput في واحدة.' } },
    { n:'required', k:'ng',
      w:{ en:'Part of Angular’s API: <code>input.required</code> and <code>model.required</code>.',
          ar:'جزء من API أنجولار: <code>input.required</code> و<code>model.required</code>.' } },
    { n:'alias', k:'ng',
      w:{ en:'An option key Angular reads. The value you give it is yours.',
          ar:'مفتاح إعداد أنجولار بيقراه. القيمة اللي بتحطها فيه بتاعتك.' } },
    { n:'transform', k:'ng',
      w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'booleanAttribute', k:'ng',
      w:{ en:'A ready-made function from Angular that turns <code>""</code> into <code>true</code>.',
          ar:'function جاهزة من أنجولار بتحوّل <code>""</code> لـ <code>true</code>.' } },
    { n:'computed', k:'ng',
      w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'emit', k:'ng',
      w:{ en:'The method every output has. Only the child calls it.',
          ar:'الميثود اللي موجودة في أي output. الابن بس هو اللي بيناديها.' } },
    { n:'$event', k:'ng',
      w:{ en:'Angular’s fixed name, in the parent’s template only, for the value the child passed to <code>emit()</code>.',
          ar:'اسم ثابت من أنجولار، في تمبلت الأب بس، للقيمة اللي الابن بعتها في <code>emit()</code>.' } },
    { n:'set', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'update', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'click', k:'ng',
      w:{ en:'The browser’s own event name. You cannot rename it; it is how the button reports a click.',
          ar:'اسم الـ event بتاع المتصفح نفسه. مينفعش تغيّره؛ ده الطريقة اللي الزرار بيقول بيها إنه اتداس.' } },

    { n:'remove', k:'pub',
      w:{ en:'The output’s name. The child declares it and calls <code>remove.emit()</code>. The parent listens with <code>(remove)</code>. Rename it in both files or the parent hears nothing.',
          ar:'اسم الـ output. الابن بيعلنه وبينادي <code>remove.emit()</code>. والأب بيسمعه بـ <code>(remove)</code>. غيّره في الملفين وإلا الأب مش هيسمع حاجة.' } },
    { n:'line', k:'pub',
      w:{ en:'An input. The parent sets it with <code>[line]</code>, so both files change together.',
          ar:'input. الأب بيحطه بـ <code>[line]</code>، فالملفين بيتغيروا مع بعض.' } },
    { n:'qty', k:'pub', only:['cts','ctpl','ptpl'], re:'(?<![\\w$-])(?<!\\bl\\.)qty(?![\\w$-])',
      w:{ en:'A <code>model()</code>. The parent binds it with <code>[(qty)]</code>. The <code>l.qty</code> on the right is a different thing: a field on your <code>Line</code> data.',
          ar:'<code>model()</code>. الأب بيربطه بـ <code>[(qty)]</code>. و<code>l.qty</code> اللي على اليمين حاجة تانية: field في داتا الـ <code>Line</code> بتاعتك.' } },
    { n:'currency', k:'pub',
      w:{ en:'An optional input. No parent sets it here, but any parent could with <code>[currency]</code>.',
          ar:'input اختياري. مفيش أب بيحطه هنا، بس أي أب يقدر بـ <code>[currency]</code>.' } },
    { n:'compact', k:'mine',
      w:{ en:'The class property behind an alias. Because of <code>alias: \'dense\'</code>, the outside world never sees this name, so it is private.',
          ar:'الـ property اللي ورا الـ alias. عشان <code>alias: \'dense\'</code>، محدش برّه بيشوف الاسم ده، فهو خاص.' } },
    { n:'dense', k:'pub',
      w:{ en:'The alias: the name the parent types. Rename it in the alias string and in the parent template.',
          ar:'الـ alias: الاسم اللي الأب بيكتبه. غيّره في النص بتاع الـ alias وفي تمبلت الأب.' } },
    { n:'label', k:'mine',
      w:{ en:'A computed the child uses in its own template. Nobody outside reads it.',
          ar:'computed الابن بيستخدمه في التمبلت بتاعه. محدش برّه بيقراه.' } },
    { n:'drop', k:'mine',
      w:{ en:'Two different methods that happen to share a name: one in the child, one in the parent. Each is private to its own component.',
          ar:'ميثودين مختلفين صدفة ليهم نفس الاسم: واحدة في الابن وواحدة في الأب. كل واحدة خاصة بالـ component بتاعها.' } },
    { n:'lines', k:'mine',
      w:{ en:'The parent’s own signal, read by its own template.', ar:'الـ signal بتاعة الأب، والتمبلت بتاعه بيقراها.' } },
    { n:'Line', k:'pub',
      w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'InvoiceRow', k:'pub',
      w:{ en:'The child’s class name. Whoever lists it in <code>imports</code> follows a rename.',
          ar:'اسم كلاس الابن. أي حد كاتبه في <code>imports</code> بيتغير معاه.' } },
    { n:'app-invoice-row', k:'pub',
      w:{ en:'The child’s selector: its <code>selector</code> string and the tag in the parent template must match.',
          ar:'الـ selector بتاع الابن: النص في <code>selector</code> والتاج في تمبلت الأب لازم يبقوا زي بعض.' } },
    { n:'id', k:'pub', only:['route'],
      w:{ en:'With <code>withComponentInputBinding()</code> this input must be named exactly like the <code>:id</code> in the route path.',
          ar:'مع <code>withComponentInputBinding()</code> الـ input ده لازم اسمه يبقى زي <code>:id</code> في مسار الـ route بالظبط.' } },
    { n:'tab', k:'pub', only:['route'],
      w:{ en:'Filled from <code>?tab=</code> in the URL, so the query parameter and the input share the name.',
          ar:'بيتملي من <code>?tab=</code> في الـ URL، فالـ query parameter والـ input ليهم نفس الاسم.' } },
    { n:'value', k:'pub', only:['q1','q2'],
      w:{ en:'The stepper’s <code>model()</code>. The cart row binds <code>[(value)]</code>, so both change together.',
          ar:'الـ <code>model()</code> بتاع الستيبر. صف الكارت بيربط <code>[(value)]</code>، فالاتنين بيتغيروا مع بعض.' } },
    { n:'max', k:'pub', only:['q1','q2'],
      w:{ en:'An input the cart row sets with <code>[max]</code>. <code>Math.max</code> is JavaScript’s and is not touched.',
          ar:'input صف الكارت بيحطه بـ <code>[max]</code>. و<code>Math.max</code> بتاعة JavaScript ومش بتتلمس.' },
      re:'(?<![\\w$.-])max(?![\\w$-])' },
    { n:'min', k:'pub', only:['q1','q2'], re:'(?<![\\w$.-])min(?![\\w$-])',
      w:{ en:'An input with a default. Any parent could set it with <code>[min]</code>.',
          ar:'input ليه قيمة افتراضية. أي أب يقدر يحطه بـ <code>[min]</code>.' } },
    { n:'step', k:'mine', only:['q1'],
      w:{ en:'The stepper’s own method, called from its own template.', ar:'ميثود الستيبر نفسه، بيناديها من التمبلت بتاعه.' } },
    { n:'app-qty-stepper', k:'pub',
      w:{ en:'Selector: the string in the child and the tag in the cart row.', ar:'الـ selector: النص في الابن والتاج في صف الكارت.' } },
  ]
}
};
