/* names for the lazy loading topic (loadComponent, loadChildren, preloading).
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'lazy-loading': {
  note: {
    en: 'In <code>import(\'./about\').then(m => m.About)</code> only the path and the export name are yours, and they are promises to another file: the path must point at a real file and <code>m.About</code> must match what that file exports. The route keys (<code>path</code>, <code>loadComponent</code>, <code>loadChildren</code>, <code>canMatch</code>) are Angular’s.',
    ar: 'في <code>import(\'./about\').then(m => m.About)</code> المسار واسم الـ export بس هما اللي بتوعك، وهما وعد لملف تاني: المسار لازم يشاور على ملف موجود فعلاً، و<code>m.About</code> لازم يطابق اللي الملف ده بيعمله export. مفاتيح الـ route (<code>path</code> و<code>loadComponent</code> و<code>loadChildren</code> و<code>canMatch</code>) بتاعة أنجولار.'
  },
  names: [
    { n:'Routes', k:'ng', w:{ en:'Angular’s type for a list of routes.', ar:'النوع بتاع أنجولار لليستة routes.' } },
    { n:'path', k:'ng', w:{ en:'A route key Angular reads. The URL text you give it is yours.', ar:'مفتاح route أنجولار بيقراه. نص الـ URL اللي بتديهوله بتاعك.' } },
    { n:'loadComponent', k:'ng', w:{ en:'A route key: download this one component only when the route is visited.', ar:'مفتاح route: نزّل الـ component ده بس لما حد يزور الـ route.' } },
    { n:'loadChildren', k:'ng', w:{ en:'A route key: download a whole list of child routes only when needed.', ar:'مفتاح route: نزّل ليستة routes كاملة بس لما تحتاجها.' } },
    { n:'component', k:'ng', w:{ en:'A route key for an eager component that ships in the main bundle.', ar:'مفتاح route لـ component بيتحمّل على طول وبيبقى في الـ bundle الرئيسي.' } },
    { n:'canMatch', k:'ng', w:{ en:'A route key for guards that run before the chunk is even downloaded.', ar:'مفتاح route للـ guards اللي بتشتغل قبل ما الـ chunk يتنزّل أصلاً.' } },
    { n:'data', k:'ng', only:['routes','custom'], w:{ en:'A route key for any extra information you want to attach. The keys inside it are yours.', ar:'مفتاح route لأي معلومات زيادة عايز تلزقها. المفاتيح اللي جواه بتاعتك.' } },
    { n:'then', k:'ng', w:{ en:'The Promise method that runs once the file has downloaded.', ar:'ميثود الـ Promise اللي بتشتغل أول ما الملف يخلص تحميل.' } },
    { n:'provideRouter', k:'ng', w:{ en:'Angular’s function that switches the router on.', ar:'الـ function بتاعة أنجولار اللي بتشغّل الـ router.' } },
    { n:'withPreloading', k:'ng', w:{ en:'Angular’s router feature that picks a preloading strategy.', ar:'ميزة في الـ router بتاع أنجولار بتختار استراتيجية الـ preloading.' } },
    { n:'NoPreloading', k:'ng', w:{ en:'Angular’s built-in strategy: never preload.', ar:'استراتيجية جاهزة من أنجولار: متعملش preload أبداً.' } },
    { n:'PreloadAllModules', k:'ng', w:{ en:'Angular’s built-in strategy: preload everything once the app is idle.', ar:'استراتيجية جاهزة من أنجولار: اعمل preload لكل حاجة أول ما التطبيق يفضى.' } },
    { n:'@Injectable', k:'ng', w:{ en:'Angular’s decorator that makes a class a service.', ar:'الـ decorator بتاع أنجولار اللي بيخلي الكلاس service.' } },
    { n:'providedIn', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'PreloadingStrategy', k:'ng', w:{ en:'Angular’s interface for a custom preloading strategy.', ar:'الـ interface بتاع أنجولار لاستراتيجية preloading بتاعتك.' } },
    { n:'preload', k:'ng', re:'(?<![\\w$.\'-])preload(?=\\()',
      w:{ en:'The one method <code>PreloadingStrategy</code> requires. The router calls it by this exact name.', ar:'الميثود الوحيدة اللي <code>PreloadingStrategy</code> بيطلبها. الـ router بيناديها بالاسم ده بالظبط.' } },
    { n:'Route', k:'ng', w:{ en:'Angular’s type for one route object.', ar:'النوع بتاع أنجولار لـ route واحد.' } },
    { n:'Observable', k:'ng', w:{ en:'RxJS’s stream type.', ar:'نوع الـ stream بتاع RxJS.' } },
    { n:'EMPTY', k:'ng', w:{ en:'RxJS’s ready-made stream that ends straight away: “do not preload”.', ar:'stream جاهزة من RxJS بتخلص على طول: يعني “متعملش preload”.' } },
    { n:'timer', k:'ng', w:{ en:'An RxJS function that waits, then emits once.', ar:'function من RxJS بتستنى وبعدين تطلّع قيمة مرة واحدة.' } },
    { n:'switchMap', k:'ng', w:{ en:'An RxJS operator.', ar:'operator من RxJS.' } },
    { n:'navigator', k:'ng', w:{ en:'The browser’s global object about the device and connection.', ar:'الأوبجكت العام بتاع المتصفح اللي فيه معلومات الجهاز والاتصال.' } },
    { n:'saveData', k:'ng', w:{ en:'A browser flag: the user turned on data saver.', ar:'علامة من المتصفح: اليوزر مشغّل توفير الداتا.' } },
    { n:'effectiveType', k:'ng', w:{ en:'A browser property: the connection speed, like <code>\'4g\'</code>.', ar:'property من المتصفح: سرعة الاتصال، زي <code>\'4g\'</code>.' } },
    { n:'@Directive', k:'ng', w:{ en:'Angular’s decorator for a directive.', ar:'الـ decorator بتاع أنجولار للـ directive.' } },
    { n:'host:', k:'ng', re:'(?<![\\w$.-])host(?=:)', w:{ en:'Angular’s metadata key for listeners on the element the directive sits on.', ar:'مفتاح الـ metadata بتاع أنجولار للـ listeners على الـ element اللي الـ directive قاعد عليه.' } },
    { n:'mouseenter', k:'ng', w:{ en:'The browser’s own event name.', ar:'اسم الـ event بتاع المتصفح نفسه.' } },
    { n:'focus', k:'ng', w:{ en:'The browser’s own event name.', ar:'اسم الـ event بتاع المتصفح نفسه.' } },
    { n:'touchstart', k:'ng', w:{ en:'The browser’s own event name.', ar:'اسم الـ event بتاع المتصفح نفسه.' } },
    { n:'routerLink', k:'ng', w:{ en:'Angular’s link directive. The selector only matches links that already have it.', ar:'الـ directive بتاع أنجولار للينكات. الـ selector بيمسك اللينكات اللي عليها ده بس.' } },
    { n:'Router', k:'ng', w:{ en:'Angular’s router service.', ar:'الـ service بتاعة الـ router في أنجولار.' } },
    { n:'RouterLink', k:'ng', w:{ en:'The class behind <code>routerLink</code>, injected to read its URL.', ar:'الكلاس اللي ورا <code>routerLink</code>، بنعمله inject عشان نقرا الـ URL بتاعه.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتجيبلك service.' } },
    { n:'urlTree', k:'ng', w:{ en:'<code>RouterLink</code>’s property: where the link points.', ar:'property في <code>RouterLink</code>: اللينك بيشاور على فين.' } },
    { n:'parseUrl', k:'ng', w:{ en:'A <code>Router</code> method.', ar:'ميثود في <code>Router</code>.' } },
    { n:'navigateByUrl', k:'ng', w:{ en:'A <code>Router</code> method.', ar:'ميثود في <code>Router</code>.' } },
    { n:'skipLocationChange', k:'ng', w:{ en:'A navigation option: do not change the address bar.', ar:'اختيار في التنقل: متغيّرش شريط العنوان.' } },

    { n:'routes', k:'pub', re:'(?<![\\w$./-])routes(?![\\w$-])',
      w:{ en:'Your exported route list. <code>app.config.ts</code> imports it by this name for <code>provideRouter(routes)</code>.', ar:'ليستة الـ routes بتاعتك اللي بتتعمل export. <code>app.config.ts</code> بيعملها import بالاسم ده عشان <code>provideRouter(routes)</code>.' } },
    { n:'About', k:'pub', w:{ en:'Must match the class that <code>./about</code> exports. Rename the class and <code>m.About</code> together.', ar:'لازم يطابق الكلاس اللي <code>./about</code> بيعمله export. غيّر الكلاس و<code>m.About</code> مع بعض.' } },
    { n:'ADMIN_ROUTES', k:'pub', w:{ en:'Must match the constant that <code>admin.routes.ts</code> exports.', ar:'لازم يطابق الثابت اللي <code>admin.routes.ts</code> بيعمله export.' } },
    { n:'ADMIN', k:'pub', w:{ en:'Must match the constant that <code>./admin/routes</code> exports.', ar:'لازم يطابق الثابت اللي <code>./admin/routes</code> بيعمله export.' } },
    { n:'isAdmin', k:'pub', w:{ en:'Your guard function, exported from its own file.', ar:'الـ guard function بتاعتك، بيتعملها export من ملفها.' } },
    { n:'Home', k:'pub', w:{ en:'Your home page class, imported at the top of the routes file.', ar:'كلاس الصفحة الرئيسية بتاعك، بيتعمله import فوق في ملف الـ routes.' } },
    { n:'\'preload\'', k:'pub', re:'(?<=\')preload(?=\')|(?<![\\w$.\'-])preload(?=:)',
      w:{ en:'A key you invented inside <code>data</code>. The routes file writes it and your strategy reads it, so both change together. The method <code>preload(…)</code> is Angular’s and stays.',
          ar:'مفتاح انت اخترعته جوه <code>data</code>. ملف الـ routes بيكتبه والاستراتيجية بتاعتك بتقراه، فالاتنين بيتغيروا مع بعض. والميثود <code>preload(…)</code> بتاعة أنجولار وبتفضل زي ما هي.' } },
    { n:'SelectivePreload', k:'pub', w:{ en:'Your strategy class, passed to <code>withPreloading</code> in the config.', ar:'كلاس الاستراتيجية بتاعك، بيتبعت لـ <code>withPreloading</code> في الإعدادات.' } },
    { n:'route', k:'mine', w:{ en:'A parameter or local name. The position matters, not the name.', ar:'اسم parameter أو متغير محلي. المهم مكانه، مش اسمه.' } },
    { n:'load', k:'mine', only:['custom'], w:{ en:'The parameter the router fills with “go download it”. Any name works.', ar:'الـ parameter اللي الـ router بيحط فيه “روح نزّله”. أي اسم ينفع.' } },
    { n:'conn', k:'mine', w:{ en:'Your local name for the connection info.', ar:'الاسم المحلي بتاعك لمعلومات الاتصال.' } },
    { n:'appPrefetch', k:'pub', w:{ en:'The directive’s selector attribute: every link that wants prefetching types it.', ar:'الـ attribute بتاع الـ selector: أي لينك عايز prefetch بيكتبه.' } },
    { n:'Prefetch', k:'pub', w:{ en:'The directive’s class name.', ar:'اسم كلاس الـ directive.' } },
    { n:'go', k:'mine', w:{ en:'Your method, named in the <code>host</code> listeners.', ar:'الميثود بتاعتك، مكتوبة في الـ <code>host</code> listeners.' } },
    { n:'router', k:'mine', only:['hover'], w:{ en:'Your field name for the injected <code>Router</code>.', ar:'اسم الـ field بتاعك للـ <code>Router</code> اللي اتعمله inject.' } },
    { n:'link', k:'mine', w:{ en:'Your field name for the injected <code>RouterLink</code>.', ar:'اسم الـ field بتاعك للـ <code>RouterLink</code> اللي اتعمله inject.' } },
    { n:'done', k:'mine', w:{ en:'Your own flag so the prefetch runs once.', ar:'العلامة بتاعتك عشان الـ prefetch يشتغل مرة واحدة.' } },
    { n:'AdminDashboard', k:'pub', w:{ en:'A class exported by <code>./admin/dashboard</code>. Importing it statically is what drags admin into the main bundle.', ar:'كلاس <code>./admin/dashboard</code> بيعمله export. إنك تعمله import عادي هو اللي بيجرّ الـ admin للـ bundle الرئيسي.' } },
    { n:'WIDGETS', k:'pub', w:{ en:'Your exported registry.', ar:'الـ registry بتاعك اللي بيتعمله export.' } },
    { n:'adminSummary', k:'pub', w:{ en:'A registry key that whoever reads <code>WIDGETS</code> has to type.', ar:'مفتاح في الـ registry لازم أي حد بيقرا <code>WIDGETS</code> يكتبه.' } },
  ]
}
};
