/* names for the lifecycle topic. Format: see inputs-outputs.mjs. */
export default {
'lifecycle': {
  note: {
    en: 'Every hook name is fixed: <code>ngOnDestroy</code>, <code>ngOnChanges</code>, <code>afterNextRender</code>. Misspell <code>ngOnDestroy</code> and Angular simply never calls it; there is no error. The <code>implements OnDestroy</code> line is what turns that typo into a compile error.',
    ar: 'كل أسماء الـ hooks ثابتة: <code>ngOnDestroy</code>، <code>ngOnChanges</code>، <code>afterNextRender</code>. لو كتبت <code>ngOnDestroy</code> غلط أنجولار ببساطة مش هيناديها أبداً؛ ومفيش error. سطر <code>implements OnDestroy</code> هو اللي بيخلّي الغلطة دي تطلع compile error.'
  },
  names: [
    { n:'input', k:'ng', w:{ en:'Angular’s function that creates an input signal.', ar:'الـ function بتاعة أنجولار اللي بتعمل input signal.' } },
    { n:'required', k:'ng',
      w:{ en:'Part of Angular’s API: <code>input.required</code> and <code>viewChild.required</code>.',
          ar:'جزء من API أنجولار: <code>input.required</code> و<code>viewChild.required</code>.' } },
    { n:'viewChild', k:'ng',
      w:{ en:'Angular’s function that finds an element in your own template by its <code>#name</code>.',
          ar:'الـ function بتاعة أنجولار اللي بتلاقي عنصر في التمبلت بتاعك بالـ <code>#name</code> بتاعه.' } },
    { n:'ElementRef', k:'ng', w:{ en:'Angular’s wrapper around a real DOM element.', ar:'الغلاف بتاع أنجولار حوالين عنصر DOM حقيقي.' } },
    { n:'nativeElement', k:'ng',
      w:{ en:'The property on <code>ElementRef</code> that holds the real DOM element.',
          ar:'الـ property في <code>ElementRef</code> اللي شايلة عنصر الـ DOM الحقيقي.' } },
    { n:'computed', k:'ng', w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'effect', k:'ng',
      w:{ en:'Angular’s function for a side effect that re-runs when a signal it read changes.',
          ar:'الـ function بتاعة أنجولار لـ side effect بيتعاد لما signal قراها تتغير.' } },
    { n:'afterNextRender', k:'ng',
      w:{ en:'Angular’s function: run once, in the browser, after the element is on the page.',
          ar:'الـ function بتاعة أنجولار: شغّل مرة واحدة، في المتصفح، بعد ما العنصر يبقى في الصفحة.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتديك service.' } },
    { n:'DestroyRef', k:'ng',
      w:{ en:'Angular’s service that tells you when the component (or service) is destroyed.',
          ar:'الـ service بتاعة أنجولار اللي بتقولك إمتى الـ component (أو الـ service) اتشال.' } },
    { n:'onDestroy', k:'ng',
      w:{ en:'The method on <code>DestroyRef</code> that registers cleanup. Lower-case <code>o</code>, no <code>ng</code>.',
          ar:'الميثود في <code>DestroyRef</code> اللي بتسجّل التنضيف. <code>o</code> صغيرة ومن غير <code>ng</code>.' } },
    { n:'ngOnDestroy', k:'ng',
      w:{ en:'The classic hook. Angular calls a method with exactly this name; any other spelling is never called.',
          ar:'الـ hook الكلاسيكي. أنجولار بينادي ميثود بالاسم ده بالظبط؛ أي كتابة تانية عمرها ما هتتنادى.' } },
    { n:'OnDestroy', k:'ng',
      w:{ en:'Angular’s interface. <code>implements OnDestroy</code> makes TypeScript check you spelled <code>ngOnDestroy</code> right.',
          ar:'الـ interface بتاع أنجولار. <code>implements OnDestroy</code> بيخلّي TypeScript يتأكد إنك كتبت <code>ngOnDestroy</code> صح.' } },
    { n:'ngOnChanges', k:'ng',
      w:{ en:'The classic hook for input changes. The name is fixed by Angular.',
          ar:'الـ hook الكلاسيكي لتغيير الـ inputs. الاسم ثابت من أنجولار.' } },
    { n:'SimpleChanges', k:'ng', w:{ en:'Angular’s type for what <code>ngOnChanges</code> receives.', ar:'الـ type بتاع أنجولار للي <code>ngOnChanges</code> بتستلمه.' } },
    { n:'@Input', k:'ng', w:{ en:'The old decorator way to declare an input.', ar:'الطريقة القديمة بالـ decorator لتعريف input.' } },
    { n:'takeUntilDestroyed', k:'ng',
      w:{ en:'Angular’s RxJS operator that unsubscribes when the component is destroyed.',
          ar:'الـ operator بتاع أنجولار في RxJS اللي بيعمل unsubscribe لما الـ component يتشال.' } },
    { n:'httpResource', k:'ng', w:{ en:'Angular’s signal-based HTTP request.', ar:'طلب HTTP بتاع أنجولار مبني على signals.' } },
    { n:'setInterval', k:'ng', w:{ en:'The browser’s timer function.', ar:'function التايمر بتاعة المتصفح.' } },
    { n:'clearInterval', k:'ng', w:{ en:'The browser’s function that stops a <code>setInterval</code>.', ar:'function المتصفح اللي بتوقّف <code>setInterval</code>.' } },
    { n:'resize', k:'ng', w:{ en:'The browser’s own event name for the window changing size.', ar:'اسم الـ event بتاع المتصفح لما حجم الشباك يتغير.' } },
    { n:'destroy', k:'ng',
      w:{ en:'A method of the chart/map library, not of Angular. Still not yours: the library decides it.',
          ar:'ميثود في مكتبة الـ chart/الـ map، مش في أنجولار. برضه مش بتاعك: المكتبة هي اللي بتحدده.' } },

    { n:'data', k:'pub', re:'(?<![\\w$\'-])data(?![\\w$-])',
      w:{ en:'An input. The parent binds it with <code>[data]</code>.', ar:'input. الأب بيربطه بـ <code>[data]</code>.' } },
    { n:'Point', k:'pub', w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'ChartPanel', k:'pub',
      w:{ en:'The component’s class name. Whoever lists it in <code>imports</code> follows a rename.',
          ar:'اسم كلاس الـ component. أي حد كاتبه في <code>imports</code> بيتغير معاه.' } },
    { n:'box', k:'mine', w:{ en:'The component’s private handle on the canvas.', ar:'المسكة الخاصة بتاعة الـ component على الـ canvas.' } },
    { n:'canvas', k:'mine', re:'(?<![\\w$<\\/-])canvas(?![\\w$-])',
      w:{ en:'The template reference <code>#canvas</code>. The string in <code>viewChild.required(\'canvas\')</code> must match it. The <code>&lt;canvas&gt;</code> tag itself is the browser’s and is left alone.',
          ar:'الـ template reference <code>#canvas</code>. النص في <code>viewChild.required(\'canvas\')</code> لازم يطابقه. وتاج <code>&lt;canvas&gt;</code> نفسه بتاع المتصفح ومش بيتلمس.' } },
    { n:'max', k:'mine', re:'(?<![\\w$.-])max(?=\\s*[(=])',
      w:{ en:'A computed the component reads in its own template. <code>Math.max</code> is JavaScript’s and is not touched.',
          ar:'computed الـ component بيقراه في التمبلت بتاعه. و<code>Math.max</code> بتاعة JavaScript ومش بتتلمس.' } },
    { n:'chart', k:'mine', w:{ en:'A local variable holding the library’s chart.', ar:'متغير محلي شايل الـ chart بتاع المكتبة.' } },
    { n:'host', k:'mine', w:{ en:'The component’s private handle on the map element.', ar:'المسكة الخاصة بتاعة الـ component على عنصر الماب.' } },
    { n:'onResize', k:'mine',
      w:{ en:'A local function. The same variable is passed to add and to remove, which is why it needs a name at all.',
          ar:'function محلية. نفس المتغير بيتبعت للـ add وللـ remove، وده السبب إن ليها اسم أصلاً.' } },
    { n:'tick', k:'mine', w:{ en:'The timer’s own method.', ar:'ميثود التايمر نفسه.' } },
    { n:'userId', k:'pub',
      w:{ en:'An input the parent binds with <code>[userId]</code>. In the old version the string <code>\'userId\'</code> inside <code>changes[...]</code> must match too, and nothing checks it.',
          ar:'input الأب بيربطه بـ <code>[userId]</code>. في النسخة القديمة النص <code>\'userId\'</code> جوه <code>changes[...]</code> لازم يطابقه كمان، ومحدش بيتأكد من ده.' } },
    { n:'theme', k:'pub', w:{ en:'An input with a default. Any parent could set it with <code>[theme]</code>.', ar:'input ليه قيمة افتراضية. أي أب يقدر يحطه بـ <code>[theme]</code>.' } },
    { n:'changes', k:'mine', only:['n1'],
      w:{ en:'The parameter name. Angular passes the value; you choose what to call it.',
          ar:'اسم الـ parameter. أنجولار بيبعت القيمة؛ وانت بتختار تسميها إيه.' } },
    { n:'user', k:'mine', w:{ en:'The component’s own resource.', ar:'الـ resource بتاع الـ component نفسه.' } },
  ]
}
};
