/* names for the output() deep dive (content/output-names.mjs) */
const ALIAS = 'todo-item.ts · with alias';
export default {
'output-names': {
  note: {
    en: 'Read the orange rows first. Those are the only names two files have to agree on. Everything green is private to one component, and everything blue belongs to Angular, TypeScript or the browser.',
    ar: 'اقرا الصفوف البرتقاني الأول. دول الأسماء الوحيدة اللي ملفين لازم يتفقوا عليها. كل حاجة خضرا خاصة بـ component واحد، وكل حاجة زرقا بتاعة أنجولار أو TypeScript أو المتصفح.'
  },
  names: [
    /* --- shared: two files must agree --- */
    { n:'deleted', k:'pub', not:[ALIAS],
      w:{ en:'The output. Declared in the child, typed again in the parent’s <code>(deleted)</code>. Rename both or the parent silently hears nothing.',
          ar:'الـ output. متعلن في الابن، ومكتوب تاني عند الأب في <code>(deleted)</code>. غيّر الاتنين وإلا الأب مش هيسمع حاجة ومحدش هيقولك.' } },
    { n:'removed', k:'pub',
      w:{ en:'An alias. Once it exists, this is the name the parent types, and the class property behind it becomes private.',
          ar:'alias. أول ما يبقى موجود، ده الاسم اللي الأب بيكتبه، والـ property اللي وراه بتبقى خاصة.' } },
    { n:'todo', k:'pub', re:'(?<![\\w$/-])todo(?![\\w$-])',
      w:{ en:'The child’s input. The parent sets it with <code>[todo]</code>.', ar:'الـ input بتاع الابن. الأب بيحطه بـ <code>[todo]</code>.' } },
    { n:'app-todo-item', k:'pub',
      w:{ en:'The child’s selector. Its <code>selector</code> string and the tag in the parent must match.',
          ar:'الـ selector بتاع الابن. النص في <code>selector</code> والتاج عند الأب لازم يبقوا زي بعض.' } },
    { n:'app-todo-list', k:'pub',
      w:{ en:'The list’s selector. Whoever shows the list types this tag.', ar:'الـ selector بتاع الليستة. أي حد بيعرض الليستة بيكتب التاج ده.' } },
    { n:'TodoItem', k:'pub',
      w:{ en:'The child’s class. The parent imports it and lists it in <code>imports</code>.',
          ar:'كلاس الابن. الأب بيعمله import وبيكتبه في <code>imports</code>.' } },
    { n:'TodoList', k:'pub',
      w:{ en:'The parent’s class. Whoever uses the list imports it by this name.', ar:'كلاس الأب. أي حد بيستخدم الليستة بيعمله import بالاسم ده.' } },
    { n:'Todo', k:'pub',
      w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'id', k:'pub',
      w:{ en:'A field on your data. Every file that reads <code>.id</code> follows a rename.',
          ar:'field في الداتا بتاعتك. أي ملف بيقرا <code>.id</code> بيتغير معاه.' } },
    { n:'title', k:'pub',
      w:{ en:'A field on your data, read by the child’s template.', ar:'field في الداتا بتاعتك، وتمبلت الابن بيقراه.' } },
    { n:'moved', k:'pub',
      w:{ en:'A second output, carrying an object.', ar:'output تاني، شايل object.' } },
    { n:'column', k:'pub',
      w:{ en:'A field inside the emitted object. The parent reads it as <code>$event.column</code>, so both sides type it.',
          ar:'field جوه الـ object اللي اتبعت. الأب بيقراه كـ <code>$event.column</code>، فالناحيتين بيكتبوه.' } },
    { n:'todoRemoved', k:'pub',
      w:{ en:'The list’s own output, so the list’s parent can hear about removals too.',
          ar:'الـ output بتاع الليستة نفسها، عشان أبو الليستة يعرف بالمسح هو كمان.' } },
    { n:'checked', k:'pub', as:'sparkle',
      w:{ en:'An input used with <code>[(checked)]</code>. Renaming it means renaming <code>checkedChange</code> to match.',
          ar:'input بيتستخدم مع <code>[(checked)]</code>. لو غيّرته لازم تغيّر <code>checkedChange</code> معاه.' } },
    { n:'checkedChange', k:'pub', as:'sparkleChange',
      w:{ en:'Must be the input’s name plus <code>Change</code>, or <code>[(checked)]</code> stops updating the parent.',
          ar:'لازم يبقى اسم الـ input وبعده <code>Change</code>، وإلا <code>[(checked)]</code> هتبطل تحدّث الأب.' } },
    { n:'app-switch', k:'pub',
      w:{ en:'The switch’s selector, typed by the settings page.', ar:'الـ selector بتاع الـ switch، وصفحة الإعدادات بتكتبه.' } },

    /* --- yours, private to one component --- */
    { n:'deleted', k:'mine', only:[ALIAS],
      w:{ en:'With an alias, the property name is only used inside the child.', ar:'مع الـ alias، اسم الـ property بيتستخدم جوه الابن بس.' } },
    { n:'remove', k:'mine',
      w:{ en:'The child’s own method, called by its own button.', ar:'ميثود الابن نفسه، والزرار بتاعه هو اللي بيناديها.' } },
    { n:'removeTodo', k:'mine',
      w:{ en:'The parent’s own method. Only the parent’s template calls it.', ar:'ميثود الأب نفسه. تمبلت الأب بس هو اللي بيناديها.' } },
    { n:'todoId', k:'mine',
      w:{ en:'A parameter. It receives <code>$event</code>, but you can call it anything.',
          ar:'parameter. بيستقبل <code>$event</code>، بس تقدر تسمّيه أي حاجة.' } },
    { n:'todos', k:'mine',
      w:{ en:'The parent’s signal holding the list.', ar:'الـ signal بتاعة الأب اللي شايلة الليستة.' } },
    { n:'t', k:'mine',
      w:{ en:'A loop variable, and separately an arrow-function parameter. Both are local.', ar:'متغير اللوب، وبرضه parameter في arrow function. الاتنين محليين.' } },
    { n:'list', k:'mine',
      w:{ en:'The arrow function’s parameter: the current array.', ar:'الـ parameter بتاع الـ arrow function: الـ array الحالية.' } },
    { n:'lastDeletedId', k:'mine', w:{ en:'A signal on the parent.', ar:'signal عند الأب.' } },
    { n:'showUndoBar', k:'mine', w:{ en:'A parent method that needs no value.', ar:'ميثود عند الأب مش محتاجة قيمة.' } },
    { n:'moveToDone', k:'mine', w:{ en:'The child’s method that emits <code>moved</code>.', ar:'ميثود الابن اللي بتبعت <code>moved</code>.' } },
    { n:'moveTodo', k:'mine', w:{ en:'The parent’s handler for <code>moved</code>.', ar:'ميثود الأب اللي بتستقبل <code>moved</code>.' } },
    { n:'flip', k:'mine', w:{ en:'The switch’s own method.', ar:'ميثود الـ switch نفسه.' } },
    { n:'darkMode', k:'mine', w:{ en:'The settings page’s signal, kept in sync by <code>[( )]</code>.', ar:'الـ signal بتاعة صفحة الإعدادات، و<code>[( )]</code> بتخليها متزامنة.' } },

    /* --- Angular's, TypeScript's, the browser's --- */
    { n:'output', k:'ng', re:'(?<![\\w$<\\/-])output(?![\\w$-])',
      w:{ en:'Angular’s function that creates an output.', ar:'الـ function بتاعة أنجولار اللي بتعمل output.' } },
    { n:'emit', k:'ng',
      w:{ en:'The one method you call on an output. Only the child calls it.', ar:'الميثود الوحيدة اللي بتناديها على الـ output. والابن بس هو اللي بيناديها.' } },
    { n:'$event', k:'ng',
      w:{ en:'Angular’s fixed name for the emitted value. Exists only inside <code>( )="…"</code> in a template.',
          ar:'اسم أنجولار الثابت للقيمة اللي اتبعتت. موجود بس جوه <code>( )="…"</code> في التمبلت.' } },
    { n:'click', k:'ng', w:{ en:'The browser’s event name.', ar:'اسم الـ event بتاع المتصفح.' } },
    { n:'input', k:'ng', re:'(?<![\\w$<(-])input(?=[.(<,])',
      w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'required', k:'ng', w:{ en:'Part of <code>input.required</code>.', ar:'جزء من <code>input.required</code>.' } },
    { n:'model', k:'ng', w:{ en:'Angular’s input and output in one.', ar:'الـ input والـ output في واحدة، من أنجولار.' } },
    { n:'alias', k:'ng', w:{ en:'An option key Angular reads. The string you give it is yours.', ar:'مفتاح إعداد أنجولار بيقراه. النص اللي بتديهوله بتاعك.' } },
    { n:'@Output', k:'ng', w:{ en:'The older decorator.', ar:'الـ decorator القديم.' } },
    { n:'EventEmitter', k:'ng', w:{ en:'The older output class. It also has <code>emit</code>.', ar:'كلاس الـ output القديم. وفيه <code>emit</code> برضه.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'set', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'update', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'filter', k:'ng', w:{ en:'JavaScript’s array method.', ar:'ميثود الـ array بتاعة JavaScript.' } },
    { n:'@for', k:'ng', w:{ en:'Angular’s loop block.', ar:'بلوك اللوب بتاع أنجولار.' } },
    { n:'track', k:'ng', w:{ en:'Part of <code>@for</code>.', ar:'جزء من <code>@for</code>.' } },
    { n:'@Component', k:'ng', w:{ en:'Angular’s decorator.', ar:'الـ decorator بتاع أنجولار.' } },
    { n:'selector', k:'ng', w:{ en:'An option key. The string after it is yours.', ar:'مفتاح إعداد. النص اللي بعده بتاعك.' } },
    { n:'templateUrl', k:'ng', w:{ en:'An option key. The path after it points at your file.', ar:'مفتاح إعداد. المسار اللي بعده بيشاور على ملفك.' } },
    { n:'imports', k:'ng', w:{ en:'An option key: the components this template uses.', ar:'مفتاح إعداد: الـ components اللي التمبلت ده بيستخدمها.' } },
  ]
}
};
