/* names for the viewChild / contentChild queries topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'queries': {
  note: {
    en: 'The string inside <code>viewChild(\'box\')</code> is not a property name. It must match a <code>#box</code> in the template, so it is shared. The property on the left of <code>=</code> is a separate name that is only yours. The code below uses <code>box</code> for both, which is common and confusing.',
    ar: 'النص اللي جوه <code>viewChild(\'box\')</code> مش اسم property. لازم يبقى زي <code>#box</code> اللي في التمبلت، فهو متشارك. والـ property اللي على شمال <code>=</code> اسم تاني خالص وبتاعك انت بس. الكود اللي تحت مستخدم <code>box</code> للاتنين، وده شائع وبيلخبط.'
  },
  names: [
    { n:'viewChild', k:'ng', only:['ts'],
      w:{ en:'Angular’s signal query for one thing in this component’s own template.',
          ar:'الـ signal query بتاعة أنجولار لحاجة واحدة في التمبلت بتاع الـ component نفسه.' } },
    { n:'viewChildren', k:'ng',
      w:{ en:'Angular’s signal query for every match in the component’s own template.',
          ar:'الـ signal query بتاعة أنجولار لكل الحاجات اللي بتطابق في تمبلت الـ component نفسه.' } },
    { n:'contentChild', k:'ng',
      w:{ en:'Angular’s query for one thing the parent projected in between your tags.',
          ar:'الـ query بتاعة أنجولار لحاجة واحدة الأب حطها بين التاجات بتاعتك.' } },
    { n:'contentChildren', k:'ng',
      w:{ en:'Angular’s query for every projected match.', ar:'الـ query بتاعة أنجولار لكل الحاجات المتبعتة من الأب اللي بتطابق.' } },
    { n:'@ViewChild', k:'ng',
      w:{ en:'The old decorator version of <code>viewChild</code>. Still Angular’s, still works, but not a signal.',
          ar:'النسخة القديمة (decorator) من <code>viewChild</code>. لسه بتاعة أنجولار ولسه شغالة، بس مش signal.' } },
    { n:'required', k:'ng',
      w:{ en:'Part of Angular’s API: <code>viewChild.required</code>, <code>input.required</code>.',
          ar:'جزء من API أنجولار: <code>viewChild.required</code> و<code>input.required</code>.' } },
    { n:'read', k:'ng',
      w:{ en:'An option key Angular reads: “give me this type instead of the default”.',
          ar:'مفتاح إعداد أنجولار بيقراه: “هاتلي النوع ده بدل الافتراضي”.' } },
    { n:'ElementRef', k:'ng',
      w:{ en:'Angular’s wrapper around a real DOM element.', ar:'الـ wrapper بتاع أنجولار حوالين عنصر DOM حقيقي.' } },
    { n:'nativeElement', k:'ng',
      w:{ en:'The property on <code>ElementRef</code> that holds the real DOM element.',
          ar:'الـ property في <code>ElementRef</code> اللي شايلة عنصر الـ DOM الحقيقي.' } },
    { n:'HTMLInputElement', k:'ng',
      w:{ en:'The browser’s type for an <code>&lt;input&gt;</code> element.', ar:'النوع بتاع المتصفح لعنصر <code>&lt;input&gt;</code>.' } },
    { n:'value', k:'ng',
      w:{ en:'The DOM’s property holding what is typed in the input box.', ar:'الـ property بتاعة الـ DOM اللي فيها المكتوب في خانة الـ input.' } },
    { n:'focus', k:'ng',
      w:{ en:'The DOM’s method that puts the cursor in the element.', ar:'ميثود الـ DOM اللي بتحط المؤشر في العنصر.' } },
    { n:'ngOnInit', k:'ng',
      w:{ en:'Angular’s lifecycle hook. The name is fixed; Angular calls it for you.',
          ar:'lifecycle hook بتاع أنجولار. الاسم ثابت؛ أنجولار هو اللي بيناديه.' } },
    { n:'ngAfterViewInit', k:'ng',
      w:{ en:'Angular’s lifecycle hook for “the template is on the page now”. The name is fixed.',
          ar:'lifecycle hook بتاع أنجولار لـ “التمبلت بقى على الصفحة خلاص”. الاسم ثابت.' } },
    { n:'effect', k:'ng', w:{ en:'Angular’s side-effect function.', ar:'الـ function بتاعة أنجولار للـ side effects.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'inject', k:'ng',
      w:{ en:'Angular’s function that hands you a dependency.', ar:'الـ function بتاعة أنجولار اللي بتديك dependency.' } },
    { n:'$event', k:'ng',
      w:{ en:'Angular’s fixed name for the event object in a template.', ar:'اسم ثابت من أنجولار للـ event object في التمبلت.' } },
    { n:'ng-content', k:'ng',
      w:{ en:'Angular’s tag for “what the parent wrote goes here”.', ar:'تاج أنجولار لـ “اللي الأب كتبه يتحط هنا”.' } },

    { n:'#box', k:'pub', re:'(?<!<!-- #)(?<=#|\')box(?![\\w$-])(?!\'\\) is)',
      w:{ en:'A template reference variable. The <code>#box</code> in the template and the string <code>\'box\'</code> in the query must match, or the query finds nothing.',
          ar:'template reference variable. الـ <code>#box</code> اللي في التمبلت والنص <code>\'box\'</code> اللي في الـ query لازم يبقوا زي بعض، وإلا الـ query مش هتلاقي حاجة.' } },
    { n:'#chip', k:'pub', re:'(?<=#|\')chip(?![\\w$-])',
      w:{ en:'Same idea: <code>#chip</code> on every chip and <code>\'chip\'</code> in <code>viewChildren</code>. (<code>class="chip"</code> is a CSS class, a different thing.)',
          ar:'نفس الفكرة: <code>#chip</code> على كل chip و<code>\'chip\'</code> في <code>viewChildren</code>. (<code>class="chip"</code> CSS class، حاجة تانية.)' } },
    { n:'box', k:'mine', re:'(?<![\\w$\'#-])box(?![\\w$\'-])',
      w:{ en:'The class property that holds the query result. Nobody outside reads it, so rename it freely; the <code>\'box\'</code> string stays.',
          ar:'الـ property في الكلاس اللي شايلة نتيجة الـ query. محدش برّه بيقراها، فغيّرها براحتك؛ والنص <code>\'box\'</code> يفضل زي ما هو.' } },
    { n:'input', k:'mine', re:'(?<=readonly |this\\.)input(?![\\w$-])',
      w:{ en:'A property that happens to be called <code>input</code>. It is not Angular’s <code>input()</code>, it is your name for the query result.',
          ar:'property صدفة اسمها <code>input</code>. دي مش <code>input()</code> بتاعة أنجولار، ده اسمك انت لنتيجة الـ query.' } },
    { n:'list', k:'mine',
      w:{ en:'The property holding the <code>ResultList</code> instance.', ar:'الـ property اللي شايلة الـ instance بتاع <code>ResultList</code>.' } },
    { n:'listEl', k:'mine', w:{ en:'Your property name.', ar:'اسم الـ property بتاعك.' } },
    { n:'chips', k:'mine', w:{ en:'Your property name.', ar:'اسم الـ property بتاعك.' } },
    { n:'clearAndFocus', k:'mine',
      w:{ en:'The component’s own method, called from its own template.', ar:'ميثود الـ component نفسه، بيناديها من التمبلت بتاعه.' } },
    { n:'onType', k:'mine',
      w:{ en:'The component’s own method, called from its own template.', ar:'ميثود الـ component نفسه، بيناديها من التمبلت بتاعه.' } },
    { n:'ResultList', k:'pub',
      w:{ en:'The child’s class name. The query finds the child by this class, so it follows a rename.',
          ar:'اسم كلاس الابن. الـ query بتلاقي الابن بالكلاس ده، فبيتغير معاه.' } },
    { n:'scrollToTop', k:'pub',
      w:{ en:'A public method on the child that the parent calls. Rename it in both files.',
          ar:'ميثود public في الابن والأب بيناديها. غيّرها في الملفين.' } },
    { n:'results', k:'pub', re:'(?<=\\[|readonly )results(?![\\w$-])',
      w:{ en:'The child’s input, bound by the parent with <code>[results]</code>. The <code>results()</code> on the right is the parent’s own value.',
          ar:'الـ input بتاع الابن، والأب بيربطه بـ <code>[results]</code>. و<code>results()</code> اللي على اليمين دي قيمة الأب نفسه.' } },
    { n:'Tabs', k:'pub',
      w:{ en:'The container’s class name.', ar:'اسم كلاس الـ container.' } },
    { n:'Tab', k:'pub',
      w:{ en:'The child’s class. <code>contentChildren(Tab)</code> finds children by it, so both files change together.',
          ar:'كلاس الابن. <code>contentChildren(Tab)</code> بيلاقي الأبناء بيه، فالملفين بيتغيروا مع بعض.' } },
    { n:'app-tabs', k:'pub',
      w:{ en:'Selector: the string in <code>Tabs</code> and the tag the caller writes.', ar:'الـ selector: النص في <code>Tabs</code> والتاج اللي بيكتبه اللي بيستخدمه.' } },
    { n:'app-tab', k:'pub',
      w:{ en:'Selector: the string in <code>Tab</code> and the tag the caller writes.', ar:'الـ selector: النص في <code>Tab</code> والتاج اللي بيكتبه اللي بيستخدمه.' } },
    { n:'tabs', k:'mine',
      w:{ en:'The query result, read only by <code>Tabs</code> itself.', ar:'نتيجة الـ query، و<code>Tabs</code> بس اللي بيقراها.' } },
    { n:'active', k:'mine',
      w:{ en:'<code>Tabs</code>’ own signal for which tab is showing.', ar:'الـ signal بتاعة <code>Tabs</code> نفسه لأنهي tab ظاهرة.' } },
    { n:'label', k:'pub',
      w:{ en:'The tab’s input. The caller sets it with <code>label="…"</code> and <code>Tabs</code> reads <code>t.label()</code>: three files.',
          ar:'الـ input بتاع الـ tab. اللي بيستخدمه بيحطه بـ <code>label="…"</code> و<code>Tabs</code> بيقرا <code>t.label()</code>: تلات ملفات.' } },
    { n:'visible', k:'pub',
      w:{ en:'A signal on <code>Tab</code> that <code>Tabs</code> sets from outside. Rename it in both.',
          ar:'signal في <code>Tab</code> و<code>Tabs</code> بيغيّرها من برّه. غيّرها في الاتنين.' } },
    { n:'id', k:'pub',
      w:{ en:'A field on <code>Tab</code> that <code>Tabs</code> tracks by.', ar:'field في <code>Tab</code> و<code>Tabs</code> بيعمل بيه track.' } },
  ]
}
};
