/* names for the routing topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'routing': {
  note: {
    en: 'Every key in a route object (<code>path</code>, <code>loadComponent</code>, <code>canActivate</code>…) is Angular’s. The <em>values</em> are yours, and many of them are promises: with <code>withComponentInputBinding()</code>, <code>:id</code>, <code>?status=</code> and <code>data: { section }</code> must be spelled exactly like the inputs they fill.',
    ar: 'كل مفتاح في الـ route object (<code>path</code>، <code>loadComponent</code>، <code>canActivate</code>…) بتاع أنجولار. أما <em>القيم</em> فبتاعتك، وكتير منها وعود: مع <code>withComponentInputBinding()</code>، الـ <code>:id</code> والـ <code>?status=</code> والـ <code>data: { section }</code> لازم يتكتبوا بالظبط زي الـ inputs اللي بيملوها.'
  },
  names: [
    { n:'Routes', k:'ng', w:{ en:'Angular’s type for a list of routes.', ar:'النوع بتاع أنجولار لقايمة routes.' } },
    { n:'path', k:'ng',
      w:{ en:'A route key Angular reads. The URL text you put in it is yours.',
          ar:'مفتاح route أنجولار بيقراه. نص الـ URL اللي بتحطه فيه بتاعك.' } },
    { n:'pathMatch', k:'ng',
      w:{ en:'A route key: <code>\'full\'</code> means the whole URL must match, not just the start.',
          ar:'مفتاح route: <code>\'full\'</code> معناها إن الـ URL كله لازم يطابق، مش أوله بس.' } },
    { n:'redirectTo', k:'ng', w:{ en:'A route key Angular reads.', ar:'مفتاح route أنجولار بيقراه.' } },
    { n:'title', k:'ng',
      w:{ en:'A route key: Angular puts this text in the browser tab.', ar:'مفتاح route: أنجولار بيحط النص ده في تاب المتصفح.' } },
    { n:'loadComponent', k:'ng',
      w:{ en:'A route key: download this component’s code only when the route is visited.',
          ar:'مفتاح route: نزّل كود الـ component ده بس لما حد يروح للـ route.' } },
    { n:'loadChildren', k:'ng',
      w:{ en:'A route key: download a whole list of child routes lazily.', ar:'مفتاح route: نزّل قايمة routes فرعية كاملة وقت الحاجة.' } },
    { n:'canActivate', k:'ng', w:{ en:'A route key for guards that run before entering.', ar:'مفتاح route للـ guards اللي بتشتغل قبل الدخول.' } },
    { n:'canMatch', k:'ng',
      w:{ en:'A route key for guards that decide if this route counts at all.', ar:'مفتاح route للـ guards اللي بتقرر الـ route ده يتحسب أصلاً ولا لأ.' } },
    { n:'data', k:'ng', only:['cfg'],
      w:{ en:'A route key for static data. The keys inside it are yours.', ar:'مفتاح route لداتا ثابتة. المفاتيح اللي جواه بتاعتك.' } },
    { n:'**', k:'ng',
      w:{ en:'Angular’s wildcard path: “anything nothing else matched”. It must come last.',
          ar:'الـ wildcard path بتاع أنجولار: “أي حاجة محدش تاني طابقها”. لازم يبقى في الآخر.' } },
    { n:'CanActivateFn', k:'ng', w:{ en:'Angular’s type for a guard function.', ar:'النوع بتاع أنجولار لـ guard function.' } },
    { n:'CanMatchFn', k:'ng', w:{ en:'Angular’s type for a match guard.', ar:'النوع بتاع أنجولار لـ match guard.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a dependency.', ar:'الـ function بتاعة أنجولار اللي بتديك dependency.' } },
    { n:'Router', k:'ng', w:{ en:'Angular’s navigation service.', ar:'الـ service بتاعة أنجولار للتنقل.' } },
    { n:'ActivatedRoute', k:'ng',
      w:{ en:'Angular’s service describing the route this component is on.', ar:'الـ service بتاعة أنجولار اللي بتوصف الـ route اللي الـ component ده عليه.' } },
    { n:'createUrlTree', k:'ng', w:{ en:'A <code>Router</code> method.', ar:'ميثود في الـ <code>Router</code>.' } },
    { n:'navigate', k:'ng', w:{ en:'A <code>Router</code> method.', ar:'ميثود في الـ <code>Router</code>.' } },
    { n:'queryParams', k:'ng',
      w:{ en:'An option key Angular reads. The keys inside it become <code>?key=</code> in the URL.',
          ar:'مفتاح إعداد أنجولار بيقراه. المفاتيح اللي جواه بتبقى <code>?key=</code> في الـ URL.' } },
    { n:'relativeTo', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'queryParamsHandling', k:'ng',
      w:{ en:'An option key: <code>\'merge\'</code> keeps the other query params.', ar:'مفتاح إعداد: <code>\'merge\'</code> بيحافظ على باقي الـ query params.' } },
    { n:'provideRouter', k:'ng', w:{ en:'Angular’s function that switches the router on.', ar:'الـ function بتاعة أنجولار اللي بتشغّل الـ router.' } },
    { n:'withComponentInputBinding', k:'ng',
      w:{ en:'Angular’s feature that fills inputs from the URL by matching names.',
          ar:'الـ feature بتاعة أنجولار اللي بتملا الـ inputs من الـ URL لو الأسامي زي بعض.' } },
    { n:'withPreloading', k:'ng', w:{ en:'Angular’s router feature.', ar:'feature في الـ router بتاع أنجولار.' } },
    { n:'input', k:'ng', re:'(?<![\\w$<(-])input(?=[.(<,])',
      w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'numberAttribute', k:'ng',
      w:{ en:'A ready-made function from Angular that turns the URL’s text <code>"2"</code> into the number <code>2</code>.',
          ar:'function جاهزة من أنجولار بتحوّل النص <code>"2"</code> اللي في الـ URL لرقم <code>2</code>.' } },
    { n:'httpResource', k:'ng',
      w:{ en:'Angular’s signal-based HTTP fetch.', ar:'الـ HTTP fetch بتاع أنجولار اللي مبني على signals.' } },

    { n:'routes', k:'pub', re:'(?<![\\w$.-])routes(?![\\w$-])',
      w:{ en:'Your exported array. <code>app.config.ts</code> imports it by this name.',
          ar:'الـ array اللي انت عامله export. <code>app.config.ts</code> بيعمله import بالاسم ده.' } },
    { n:'orders', k:'pub', re:'(?<=\')orders(?=[/\'])',
      w:{ en:'A URL segment. Every <code>routerLink</code> and <code>redirectTo</code> that points here must use the same text.',
          ar:'جزء من الـ URL. أي <code>routerLink</code> أو <code>redirectTo</code> بيشاور هنا لازم يستخدم نفس النص.' } },
    { n:'id', k:'pub', only:['cfg','chunk'],
      w:{ en:'The <code>:id</code> in the path and the <code>id</code> input must be spelled the same, or the input stays empty.',
          ar:'الـ <code>:id</code> اللي في الـ path والـ input اللي اسمه <code>id</code> لازم يتكتبوا زي بعض، وإلا الـ input هيفضل فاضي.' } },
    { n:'section', k:'pub',
      w:{ en:'A key inside route <code>data</code>, and the input that receives it. Same name on both sides.',
          ar:'مفتاح جوه <code>data</code> بتاعة الـ route، والـ input اللي بيستقبله. نفس الاسم في الناحيتين.' } },
    { n:'tab', k:'pub',
      w:{ en:'Filled from <code>?tab=</code>, so every link that sets it uses this name.', ar:'بيتملي من <code>?tab=</code>، فأي لينك بيحطه بيستخدم الاسم ده.' } },
    { n:'OrderPage', k:'pub',
      w:{ en:'The class name the lazy import picks out of the file.', ar:'اسم الكلاس اللي الـ lazy import بيطلّعه من الملف.' } },
    { n:'ADMIN_ROUTES', k:'pub',
      w:{ en:'The array exported by <code>admin.routes.ts</code>.', ar:'الـ array اللي <code>admin.routes.ts</code> عامله export.' } },
    { n:'authGuard', k:'pub',
      w:{ en:'Your guard, exported from one file and listed in the routes.', ar:'الـ guard بتاعك، متعمله export من ملف ومكتوب في الـ routes.' } },
    { n:'adminMatch', k:'pub',
      w:{ en:'Your match guard, exported and listed in the routes.', ar:'الـ match guard بتاعك، متعمله export ومكتوب في الـ routes.' } },
    { n:'Session', k:'pub', w:{ en:'Your service class.', ar:'كلاس الـ service بتاعك.' } },
    { n:'sign-in', k:'pub',
      w:{ en:'The path of another route. It must match that route’s <code>path</code>.', ar:'الـ path بتاع route تاني. لازم يطابق الـ <code>path</code> بتاعه.' } },
    { n:'next', k:'pub',
      w:{ en:'A query param name you chose. The sign-in page reads <code>?next=</code>, so both use the same word.',
          ar:'اسم query param انت اختاره. صفحة الـ sign-in بتقرا <code>?next=</code>، فالاتنين بيستخدموا نفس الكلمة.' } },
    { n:'route', k:'mine',
      w:{ en:'Two unrelated names: the guard’s first parameter, and the list’s injected <code>ActivatedRoute</code>. Both are yours to rename.',
          ar:'اسمين ملهمش علاقة ببعض: أول parameter في الـ guard، والـ <code>ActivatedRoute</code> اللي الليستة عاملاله inject. الاتنين بتوعك وتقدر تغيّرهم.' } },
    { n:'state', k:'mine',
      w:{ en:'The guard’s second parameter. Angular passes it by position, so the name is yours.',
          ar:'تاني parameter في الـ guard. أنجولار بيبعته بالترتيب، فالاسم بتاعك.' } },
    { n:'router', k:'mine', re:'(?<![\\w$/-])router(?![\\w$-])', w:{ en:'Your property holding the <code>Router</code>.', ar:'الـ property بتاعتك اللي شايلة الـ <code>Router</code>.' } },
    { n:'status', k:'pub', re:'(?<![\\w$?-])status(?![\\w$=-])',
      w:{ en:'An input filled from <code>?status=</code>. <code>setStatus</code> writes the same key into <code>queryParams</code>, so they must match.',
          ar:'input بيتملي من <code>?status=</code>. و<code>setStatus</code> بيكتب نفس المفتاح في <code>queryParams</code>، فلازم يبقوا زي بعض.' } },
    { n:'page', k:'pub', re:'(?<![\\w$&?-])page(?![\\w$=-])',
      w:{ en:'An input filled from <code>?page=</code>. Same rule as <code>status</code>.', ar:'input بيتملي من <code>?page=</code>. نفس قاعدة <code>status</code>.' } },
    { n:'setStatus', k:'mine',
      w:{ en:'The component’s own method, called from its own template.', ar:'ميثود الـ component نفسه، بيناديها من التمبلت بتاعه.' } },
    { n:'appConfig', k:'pub',
      w:{ en:'Your config object. <code>main.ts</code> imports it by this name.', ar:'الـ config object بتاعك. <code>main.ts</code> بيعمله import بالاسم ده.' } },
  ]
}
};
