/* names for the security topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'security': {
  note: {
    en: 'Every dangerous word on this page is Angular’s or the browser’s: <code>bypassSecurityTrust…</code>, <code>innerHTML</code>, <code>nativeElement</code>. That is why you can grep for them. The names you chose (<code>sanitizer</code>, <code>comment</code>, <code>ALLOWED</code>) are harmless labels; renaming them changes nothing about safety.',
    ar: 'كل كلمة خطيرة في الصفحة دي بتاعة أنجولار أو المتصفح: <code>bypassSecurityTrust…</code> و<code>innerHTML</code> و<code>nativeElement</code>. وعشان كده تقدر تدوّر عليها بـ grep. والأسماء اللي انت اخترتها (<code>sanitizer</code> و<code>comment</code> و<code>ALLOWED</code>) مجرد أسامي؛ لو غيّرتها مفيش حاجة في الأمان هتتغير.'
  },
  names: [
    { n:'innerHTML', k:'ng',
      w:{ en:'The browser’s DOM property. Bound with <code>[innerHTML]</code>, Angular sanitizes it first; set directly on <code>nativeElement</code>, nothing does.',
          ar:'property بتاعة المتصفح في الـ DOM. لما تربطها بـ <code>[innerHTML]</code> أنجولار بينضّفها الأول؛ لكن لو حطيتها على <code>nativeElement</code> على طول محدش بينضّف حاجة.' } },
    { n:'href', k:'ng',
      w:{ en:'The browser’s link property. Angular treats it as a URL and rewrites <code>javascript:</code> links to <code>unsafe:</code>.',
          ar:'property اللينك بتاعة المتصفح. أنجولار بيعاملها كـ URL وبيحوّل أي لينك <code>javascript:</code> لـ <code>unsafe:</code>.' } },
    { n:'DomSanitizer', k:'ng',
      w:{ en:'Angular’s sanitizer service. You get it with <code>inject(DomSanitizer)</code>.',
          ar:'الـ service بتاعة أنجولار اللي بتنضّف. بتجيبها بـ <code>inject(DomSanitizer)</code>.' } },
    { n:'inject', k:'ng', only:['ts'], w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتديك service.' } },
    { n:'sanitize', k:'ng',
      w:{ en:'The <code>DomSanitizer</code> method that really filters the value. This is the one to use.',
          ar:'الميثود بتاعة <code>DomSanitizer</code> اللي بتفلتر القيمة بجد. دي اللي تستخدمها.' } },
    { n:'bypassSecurityTrustHtml', k:'ng',
      w:{ en:'Angular’s method that switches the sanitizer off for one value. The long scary name is on purpose.',
          ar:'ميثود أنجولار اللي بتقفل الـ sanitizer لقيمة واحدة. الاسم الطويل المخيف ده مقصود.' } },
    { n:'bypassSecurityTrustResourceUrl', k:'ng',
      w:{ en:'The same switch for a URL that will load code, like an <code>&lt;iframe src&gt;</code>. Only for URLs you checked yourself.',
          ar:'نفس المفتاح بس لـ URL هيحمّل كود، زي <code>&lt;iframe src&gt;</code>. بس للـ URLs اللي انت اتأكدت منها بنفسك.' } },
    { n:'SecurityContext', k:'ng', re:'(?<![\\w$-])SecurityContext(?:\\.[A-Z_]+)?(?![\\w$-])',
      w:{ en:'Angular’s list of places a value can land. <code>HTML</code>, <code>STYLE</code>, <code>URL</code>, <code>RESOURCE_URL</code> and <code>SCRIPT</code> are Angular’s names too.',
          ar:'قايمة أنجولار للأماكن اللي القيمة ممكن تتحط فيها. و<code>HTML</code> و<code>STYLE</code> و<code>URL</code> و<code>RESOURCE_URL</code> و<code>SCRIPT</code> كلها أسماء أنجولار برضه.' } },
    { n:'nativeElement', k:'ng',
      w:{ en:'The real DOM element inside an <code>ElementRef</code>. Touching it skips Angular’s protection completely.',
          ar:'الـ element الحقيقي في الـ DOM اللي جوه <code>ElementRef</code>. لو لمسته بتعدّي حماية أنجولار خالص.' } },
    { n:'document.write', k:'ng',
      w:{ en:'The browser’s oldest way to inject raw HTML. Never feed it user text.',
          ar:'أقدم طريقة في المتصفح تحط بيها HTML خام. أوعى تدّيه نص كاتبه يوزر.' } },
    { n:'encodeURIComponent', k:'ng',
      w:{ en:'JavaScript’s function that makes a value safe to put inside a URL.',
          ar:'function بتاعة JavaScript بتخلّي القيمة آمنة إنها تتحط جوه URL.' } },
    { n:'URL', k:'ng',
      w:{ en:'JavaScript’s built-in URL parser. <code>hostname</code> is one of its properties.',
          ar:'الـ parser الجاهز بتاع JavaScript للـ URLs. و<code>hostname</code> واحدة من الـ properties بتاعته.' } },
    { n:'hostname', k:'ng', w:{ en:'A property of JavaScript’s <code>URL</code>.', ar:'property في <code>URL</code> بتاعة JavaScript.' } },
    { n:'provideHttpClient', k:'ng', w:{ en:'Angular’s function that sets up <code>HttpClient</code>.', ar:'الـ function بتاعة أنجولار اللي بتجهّز <code>HttpClient</code>.' } },
    { n:'withXsrfConfiguration', k:'ng',
      w:{ en:'Angular’s option for <code>provideHttpClient</code>. <code>cookieName</code> and <code>headerName</code> are the keys it reads.',
          ar:'إعداد من أنجولار لـ <code>provideHttpClient</code>. و<code>cookieName</code> و<code>headerName</code> هما المفاتيح اللي بيقراها.' } },
    { n:'cookieName', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'headerName', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'XSRF-TOKEN', k:'pub', as:'MY-CSRF-COOKIE',
      w:{ en:'Angular’s default cookie name, but really a deal with your server: the server must set a cookie with exactly this name. Change it only together with the server.',
          ar:'اسم الكوكي الافتراضي عند أنجولار، بس هو في الحقيقة اتفاق مع السيرفر بتاعك: السيرفر لازم يعمل كوكي بالاسم ده بالظبط. غيّره بس مع السيرفر.' } },
    { n:'X-XSRF-TOKEN', k:'pub', as:'X-MY-CSRF-HEADER',
      w:{ en:'The header Angular sends back. The server checks for this exact name, so both sides change together.',
          ar:'الـ header اللي أنجولار بيرجّعه. السيرفر بيدوّر على الاسم ده بالظبط، فالناحيتين بيتغيروا مع بعض.' } },
    { n:'@Pipe', k:'ng', w:{ en:'Angular’s decorator that makes a class a pipe.', ar:'الـ decorator بتاع أنجولار اللي بيخلّي الكلاس pipe.' } },
    { n:'name', k:'ng', only:['sf1','sf2'],
      w:{ en:'An option key Angular reads. The string you give it is yours.', ar:'مفتاح إعداد أنجولار بيقراه. النص اللي بتحطه فيه بتاعك.' } },
    { n:'PipeTransform', k:'ng', w:{ en:'Angular’s interface for pipes. It promises a <code>transform</code> method.', ar:'الـ interface بتاعة أنجولار للـ pipes. بتوعد إن فيه ميثود <code>transform</code>.' } },
    { n:'transform', k:'ng',
      w:{ en:'The method Angular calls on every pipe. It must be spelled exactly like this.',
          ar:'الميثود اللي أنجولار بيناديها في أي pipe. لازم تتكتب كده بالظبط.' } },

    { n:'safeHtml', k:'pub',
      w:{ en:'The pipe’s name: templates type it after <code>|</code>. Rename it here and in every template that uses it.',
          ar:'اسم الـ pipe: التمبلتس بتكتبه بعد <code>|</code>. غيّره هنا وفي كل تمبلت بيستخدمه.' } },
    { n:'SafeHtml', k:'pub',
      w:{ en:'Your pipe’s class name; components list it in <code>imports</code>. Careful: Angular also has a type called <code>SafeHtml</code>. This is not it.',
          ar:'اسم كلاس الـ pipe بتاعك؛ الـ components بتكتبه في <code>imports</code>. خد بالك: أنجولار عنده type اسمه <code>SafeHtml</code> برضه. ده مش هو.' } },
    { n:'trustHtml', k:'pub',
      w:{ en:'The dangerous pipe’s name, typed after <code>|</code> in templates.', ar:'اسم الـ pipe الخطيرة، بيتكتب بعد <code>|</code> في التمبلتس.' } },
    { n:'TrustHtml', k:'pub',
      w:{ en:'The dangerous pipe’s class name, listed in <code>imports</code> wherever it is used.', ar:'اسم كلاس الـ pipe الخطيرة، بيتكتب في <code>imports</code> في أي مكان بيستخدمها.' } },
    { n:'sanitizer', k:'mine',
      w:{ en:'Your field that holds the <code>DomSanitizer</code>. Call it anything; the safety comes from the class, not the name.',
          ar:'الـ field بتاعك اللي شايل الـ <code>DomSanitizer</code>. سمّيه أي حاجة؛ الأمان جاي من الكلاس مش من الاسم.' } },
    { n:'value', k:'mine', only:['sf1','sf2'],
      w:{ en:'The parameter of <code>transform</code>. Angular passes the value by position, so the name is yours.',
          ar:'الـ parameter بتاع <code>transform</code>. أنجولار بيبعت القيمة حسب الترتيب، فالاسم بتاعك.' } },
    { n:'comment', k:'mine',
      w:{ en:'A property of your component, read by its own template.', ar:'property في الـ component بتاعك، والتمبلت بتاعه بيقراها.' } },
    { n:'userLink', k:'mine',
      w:{ en:'A property of your component, read by its own template.', ar:'property في الـ component بتاعك، والتمبلت بتاعه بيقراها.' } },
    { n:'ALLOWED', k:'mine', w:{ en:'Your allowlist constant.', ar:'الـ constant بتاعك اللي فيه القايمة المسموحة.' } },
    { n:'embed', k:'mine', only:['ctx'], re:'(?<![\\w$/.-])embed(?=\\()',
      w:{ en:'Your method. The <code>embed</code> inside the YouTube address and the error text are just words in a string.',
          ar:'الميثود بتاعتك. و<code>embed</code> اللي جوه عنوان يوتيوب ونص الإيرور مجرد كلام جوه string.' } },
    { n:'url', k:'mine', only:['ctx'],
      w:{ en:'Your parameter. <code>URL</code> with capitals is JavaScript’s class, a different name.', ar:'الـ parameter بتاعك. و<code>URL</code> بالكابيتال ده كلاس JavaScript، اسم تاني خالص.' } },
    { n:'host', k:'mine', only:['ctx'], re:'(?<![\\w$-])host(?=\\s*=|\\))',
      w:{ en:'Your local variable. The word “host” in the error message is just text.', ar:'متغير محلي بتاعك. وكلمة “host” اللي في رسالة الإيرور مجرد نص.' } },
    { n:'commentFromUser', k:'mine', w:{ en:'A variable name you chose.', ar:'اسم متغير انت اخترته.' } },
    { n:'videoId', k:'mine', w:{ en:'A variable name you chose.', ar:'اسم متغير انت اخترته.' } },
    { n:'userText', k:'mine', w:{ en:'A variable name you chose.', ar:'اسم متغير انت اخترته.' } },
    { n:'el', k:'mine',
      w:{ en:'Your field holding an <code>ElementRef</code>. <code>nativeElement</code> after the dot is Angular’s.', ar:'الـ field بتاعك اللي شايل <code>ElementRef</code>. و<code>nativeElement</code> اللي بعد النقطة بتاعة أنجولار.' } },
  ]
}
};
