/* names for the services & dependency injection topic. Format: see inputs-outputs.mjs. */
export default {
'services-di': {
  note: {
    en: 'A service’s class name and its <b>public</b> members are <b>orange</b>: every component that injects it types them. The field you store the service in (<code>session</code>, <code>toasts</code>) is <b>green</b>: each component picks its own.',
    ar: 'اسم كلاس الـ service والحاجات <b>الـ public</b> اللي فيه <b>برتقاني</b>: أي component بيعمله inject بيكتبها. واسم الـ field اللي بتحط فيه الـ service (<code>session</code>، <code>toasts</code>) <b>أخضر</b>: كل component بيختار اسمه.'
  },
  names: [
    { n:'@Injectable', k:'ng',
      w:{ en:'Angular’s decorator that marks a class as something the injector can create.',
          ar:'الـ decorator بتاع أنجولار اللي بيعلّم الكلاس إنه حاجة الـ injector يقدر يعملها.' } },
    { n:'providedIn', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'root', k:'ng',
      w:{ en:'Angular’s fixed value: one instance for the whole app. Not a name you choose.',
          ar:'قيمة ثابتة من أنجولار: نسخة واحدة للتطبيق كله. مش اسم انت بتختاره.' } },
    { n:'inject', k:'ng',
      w:{ en:'Angular’s function that hands you the one shared instance.',
          ar:'الـ function بتاعة أنجولار اللي بتديك النسخة الواحدة المتشاركة.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'computed', k:'ng', w:{ en:'Angular’s derived signal.', ar:'الـ signal المشتقة بتاعة أنجولار.' } },
    { n:'asReadonly', k:'ng',
      w:{ en:'A signal method: gives out a copy nobody outside can <code>set</code>.',
          ar:'ميثود بتاعة الـ signal: بتطلّع نسخة محدش برّه يقدر يعمل عليها <code>set</code>.' } },
    { n:'set', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'update', k:'ng', w:{ en:'A signal method.', ar:'ميثود بتاعة الـ signal.' } },
    { n:'Router', k:'ng', w:{ en:'Angular’s router service.', ar:'الـ service بتاعة الـ router في أنجولار.' } },
    { n:'navigateByUrl', k:'ng', w:{ en:'A <code>Router</code> method.', ar:'ميثود في الـ <code>Router</code>.' } },
    { n:'CanActivateFn', k:'ng', w:{ en:'Angular’s type for a guard function.', ar:'الـ type بتاع أنجولار لـ function الـ guard.' } },
    { n:'createUrlTree', k:'ng', w:{ en:'A <code>Router</code> method that builds a redirect.', ar:'ميثود في الـ <code>Router</code> بتبني redirect.' } },
    { n:'HttpInterceptorFn', k:'ng', w:{ en:'Angular’s type for an interceptor function.', ar:'الـ type بتاع أنجولار لـ function الـ interceptor.' } },
    { n:'click', k:'ng', w:{ en:'The browser’s own event name.', ar:'اسم الـ event بتاع المتصفح نفسه.' } },

    { n:'Session', k:'pub',
      w:{ en:'The service’s class name. It is also the key <code>inject()</code> looks it up by, so every file that injects it follows a rename.',
          ar:'اسم كلاس الـ service. وهو كمان المفتاح اللي <code>inject()</code> بيدوّر بيه، فأي ملف بيعمله inject بيتغير معاه.' } },
    { n:'_user', k:'mine',
      w:{ en:'The private writable signal. Nothing outside the service can see it.',
          ar:'الـ signal الخاصة اللي بتتكتب. محدش برّه الـ service يقدر يشوفها.' } },
    { n:'user', k:'pub', only:['svc'],
      w:{ en:'The public, read-only view of <code>_user</code>. Any component may read <code>session.user()</code>.',
          ar:'النسخة الـ public اللي للقراية بس من <code>_user</code>. أي component يقدر يقرا <code>session.user()</code>.' } },
    { n:'User', k:'pub', w:{ en:'Your data type. Every file that imports it follows a rename.', ar:'نوع الداتا بتاعك. أي ملف بيعمله import بيتغير معاه.' } },
    { n:'isSignedIn', k:'pub',
      w:{ en:'Public on the service, read by the header and the guard. Rename it in all three files.',
          ar:'public في الـ service، والهيدر والـ guard بيقروه. غيّره في التلات ملفات.' } },
    { n:'initials', k:'pub', w:{ en:'Public on the service, read by the header’s template.', ar:'public في الـ service، وتمبلت الهيدر بيقراه.' } },
    { n:'signIn', k:'pub', re:'(?<![\\w$-])(?<!api\\.)signIn(?![\\w$-])',
      w:{ en:'The service’s method, called by the login page. <code>api.signIn</code> is a different method on a different service and is left alone.',
          ar:'ميثود الـ service، وصفحة اللوجين بتناديها. و<code>api.signIn</code> ميثود تانية في service تانية ومش بتتلمس.' } },
    { n:'signOut', k:'pub', w:{ en:'The service’s method, called from the header’s template.', ar:'ميثود الـ service، بتتنادى من تمبلت الهيدر.' } },
    { n:'session', k:'mine',
      w:{ en:'The field each component stores the service in. Header and Login each chose this name; they could differ.',
          ar:'الـ field اللي كل component بيحط فيه الـ service. الهيدر واللوجين كل واحد اختار الاسم ده؛ ينفع يختلفوا.' } },
    { n:'app-header', k:'pub',
      w:{ en:'The header’s selector: the tag the app shell types.', ar:'الـ selector بتاع الهيدر: التاج اللي الـ app shell بيكتبه.' } },
    { n:'sign-in', k:'pub',
      w:{ en:'A route path. The link, the guard’s redirect and the route definition must all spell it the same.',
          ar:'مسار route. اللينك والـ redirect بتاع الـ guard وتعريف الـ route لازم يكتبوه زي بعض.' } },
    { n:'authGuard', k:'pub',
      w:{ en:'Your guard’s name. The routes file that lists it in <code>canActivate</code> follows a rename.',
          ar:'اسم الـ guard بتاعك. ملف الـ routes اللي كاتبه في <code>canActivate</code> بيتغير معاه.' } },
    { n:'Toasts', k:'pub', w:{ en:'The toast service’s class name, injected in several files.', ar:'اسم كلاس الـ service بتاعة الـ toasts، بيتعمله inject في كذا ملف.' } },
    { n:'_all', k:'mine', w:{ en:'The private writable list inside the service.', ar:'الليستة الخاصة اللي بتتكتب جوه الـ service.' } },
    { n:'all', k:'pub', w:{ en:'Public, read-only. The toast strip’s template reads it.', ar:'public وللقراية بس. تمبلت الـ toast strip بيقراه.' } },
    { n:'show', k:'pub', w:{ en:'Public method, called by the interceptor.', ar:'ميثود public، الـ interceptor بيناديها.' } },
    { n:'dismiss', k:'pub', w:{ en:'Public method, called by the service itself and by the toast strip’s template.', ar:'ميثود public، الـ service نفسها بتناديها وتمبلت الـ toast strip كمان.' } },
    { n:'toasts', k:'mine',
      w:{ en:'The local name each file gives the injected <code>Toasts</code> service.', ar:'الاسم المحلي اللي كل ملف بيديه للـ service <code>Toasts</code> اللي اتعملها inject.' } },
    { n:'errorInterceptor', k:'pub',
      w:{ en:'Your interceptor’s name. The app config that registers it follows a rename.',
          ar:'اسم الـ interceptor بتاعك. الـ app config اللي بيسجّله بيتغير معاه.' } },
  ]
}
};
