/* names for the signal-based state / store topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'signal-state': {
  note: {
    en: 'In a store the line between <b>green</b> and <b>orange</b> is <code>private</code>. The <code>_todos</code> signals behind it are yours alone; every public view and method is read by components, so renaming one means renaming it in every template that calls it.',
    ar: 'في الـ store الحد الفاصل بين <b>الأخضر</b> و<b>البرتقاني</b> هو <code>private</code>. الـ signals اللي زي <code>_todos</code> اللي وراه بتاعتك لوحدك؛ وأي view أو ميثود public الـ components بتقراها، فلو غيّرت اسم واحدة لازم تغيّره في كل تمبلت بيناديها.'
  },
  names: [
    { n:'@Injectable', k:'ng', w:{ en:'Angular’s decorator for a service.', ar:'الـ decorator بتاع أنجولار للسيرفس.' } },
    { n:'providedIn', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'root', k:'ng', w:{ en:'Angular’s fixed value: one shared store for the whole app.', ar:'قيمة ثابتة من أنجولار: store واحد متشارك للتطبيق كله.' } },
    { n:'signal', k:'ng', w:{ en:'Angular’s writable signal.', ar:'الـ signal بتاعة أنجولار اللي بتتكتب.' } },
    { n:'asReadonly', k:'ng', w:{ en:'A signal method: the same value, but without <code>set</code> or <code>update</code>.', ar:'ميثود في الـ signal: نفس القيمة، بس من غير <code>set</code> أو <code>update</code>.' } },
    { n:'computed', k:'ng', w:{ en:'Angular’s derived, read-only signal.', ar:'الـ signal المشتقة بتاعة أنجولار، للقراية بس.' } },
    { n:'linkedSignal', k:'ng', w:{ en:'Angular’s signal that is derived like a computed but can also be <code>set</code>.', ar:'الـ signal بتاعة أنجولار اللي بتتحسب زي الـ computed بس كمان ينفع تعملها <code>set</code>.' } },
    { n:'set', k:'ng', w:{ en:'A signal method, and also a <code>Map</code> method. Both built in.', ar:'ميثود في الـ signal، وكمان ميثود في الـ <code>Map</code>. الاتنين جاهزين.' } },
    { n:'update', k:'ng', w:{ en:'A signal method: compute the new value from the old one.', ar:'ميثود في الـ signal: احسب القيمة الجديدة من القديمة.' } },
    { n:'input', k:'ng', w:{ en:'Angular’s function that creates an input.', ar:'الـ function بتاعة أنجولار اللي بتعمل input.' } },
    { n:'required', k:'ng', w:{ en:'Part of Angular’s API: <code>input.required</code>.', ar:'جزء من API أنجولار: <code>input.required</code>.' } },
    { n:'inject', k:'ng', w:{ en:'Angular’s function that hands you a service.', ar:'الـ function بتاعة أنجولار اللي بتديك سيرفس.' } },
    { n:'firstValueFrom', k:'ng', w:{ en:'An RxJS function that turns an observable into a promise.', ar:'function من RxJS بتحوّل observable لـ promise.' } },
    { n:'map', k:'ng', w:{ en:'JavaScript’s array method.', ar:'ميثود الـ array بتاعة JavaScript.' } },
    { n:'every', k:'ng', w:{ en:'JavaScript’s array method.', ar:'ميثود الـ array بتاعة JavaScript.' } },
    { n:'slice', k:'ng', w:{ en:'JavaScript’s array method.', ar:'ميثود الـ array بتاعة JavaScript.' } },
    { n:'Map', k:'ng', w:{ en:'JavaScript’s built-in key → value collection.', ar:'الـ collection الجاهزة في JavaScript بتاعة مفتاح → قيمة.' } },
    { n:'ReadonlyMap', k:'ng', w:{ en:'TypeScript’s read-only view of a <code>Map</code>.', ar:'الـ view بتاع TypeScript لـ <code>Map</code> للقراية بس.' } },
    { n:'get', k:'ng', w:{ en:'A <code>Map</code> method.', ar:'ميثود في <code>Map</code>.' } },
    { n:'values', k:'ng', w:{ en:'A <code>Map</code> method.', ar:'ميثود في <code>Map</code>.' } },
    { n:'delete', k:'ng', w:{ en:'A <code>Map</code> method.', ar:'ميثود في <code>Map</code>.' } },
    { n:'randomUUID', k:'ng', w:{ en:'The browser’s <code>crypto</code> function for a unique id.', ar:'function في <code>crypto</code> بتاع المتصفح بتعمل id فريد.' } },

    { n:'TodosStore', k:'pub', w:{ en:'Your store class. Every component that injects it types this name.', ar:'كلاس الـ store بتاعك. أي component بيعمله inject بيكتب الاسم ده.' } },
    { n:'Todo', k:'pub', w:{ en:'Your data type, imported by whoever uses it.', ar:'نوع الداتا بتاعك، أي حد بيستخدمه بيعمله import.' } },
    { n:'_todos', k:'mine',
      w:{ en:'The private writable signal. Only the store touches it, so rename it freely. The <code>_</code> is just a habit.',
          ar:'الـ signal الخاصة اللي بتتكتب. الـ store بس اللي بيلمسها، فغيّرها براحتك. والـ <code>_</code> مجرد عادة.' } },
    { n:'_filter', k:'mine', w:{ en:'Private writable signal.', ar:'signal خاصة بتتكتب.' } },
    { n:'_busy', k:'mine', w:{ en:'Private writable signal.', ar:'signal خاصة بتتكتب.' } },
    { n:'todos', k:'pub', w:{ en:'A public read-only view. Components read <code>store.todos()</code>, so rename it there too.', ar:'view public للقراية بس. الـ components بتقرا <code>store.todos()</code>، فغيّره هناك كمان.' } },
    { n:'filter', k:'pub', re:'(?<![\\w$.-])filter(?![\\w$-])',
      w:{ en:'A public read-only view of the filter. The <code>.filter(…)</code> on arrays is JavaScript’s own and is not touched.',
          ar:'view public للفلتر للقراية بس. و<code>.filter(…)</code> اللي على الـ arrays بتاعة JavaScript نفسها ومش بتتلمس.' } },
    { n:'busy', k:'pub', w:{ en:'A public read-only view.', ar:'view public للقراية بس.' } },
    { n:'visible', k:'pub', w:{ en:'A public computed. Components read <code>store.visible()</code>.', ar:'computed public. الـ components بتقرا <code>store.visible()</code>.' } },
    { n:'openCount', k:'pub', w:{ en:'A public computed, read in component templates.', ar:'computed public، بيتقري في تمبلتات الـ components.' } },
    { n:'allDone', k:'pub', w:{ en:'A public computed.', ar:'computed public.' } },
    { n:'isEmpty', k:'pub', w:{ en:'A public computed.', ar:'computed public.' } },
    { n:'setFilter', k:'pub', w:{ en:'A public method components call.', ar:'ميثود public الـ components بتناديها.' } },
    { n:'toggle', k:'pub', re:'(?<![\\w$-])(?<!api\\.)toggle(?![\\w$-])',
      w:{ en:'A public store method; components call <code>store.toggle()</code>. The <code>api.toggle</code> is a different method on your API service.',
          ar:'ميثود public في الـ store؛ الـ components بتنادي <code>store.toggle()</code>. و<code>api.toggle</code> ميثود تانية في سيرفس الـ API بتاعك.' } },
    { n:'add', k:'pub', w:{ en:'A public store method.', ar:'ميثود public في الـ store.' } },
    { n:'done', k:'pub', re:'(?<![\\w$\'-])done(?![\\w$\'-])',
      w:{ en:'A field of your <code>Todo</code> type. The <code>\'done\'</code> string is a filter value, a different thing.',
          ar:'field في نوع الـ <code>Todo</code> بتاعك. والنص <code>\'done\'</code> قيمة فلتر، حاجة تانية.' } },
    { n:'_byId', k:'mine', as:'okra', w:{ en:'Private writable signal holding the map.', ar:'signal خاصة بتتكتب شايلة الـ map.' } },
    { n:'all', k:'pub', as:'fig', re:'(?<![\\w$\'-])all(?![\\w$\'-])',
      w:{ en:'A public computed. The <code>\'all\'</code> string is a filter value, a different thing.', ar:'computed public. والنص <code>\'all\'</code> قيمة فلتر، حاجة تانية.' } },
    { n:'one', k:'pub', as:'leek', w:{ en:'A public function that returns a computed for one id.', ar:'function public بترجّع computed لـ id واحد.' } },
    { n:'upsert', k:'pub', as:'guava', w:{ en:'A public store method.', ar:'ميثود public في الـ store.' } },
    { n:'remove', k:'pub', as:'apricot', w:{ en:'A public store method.', ar:'ميثود public في الـ store.' } },
    { n:'Order', k:'pub', as:'Sesame', w:{ en:'Your data type.', ar:'نوع الداتا بتاعك.' } },
    { n:'products', k:'pub', w:{ en:'An input. A parent sets it with <code>[products]</code>.', ar:'input. الأب بيحطه بـ <code>[products]</code>.' } },
    { n:'Product', k:'pub', w:{ en:'Your data type.', ar:'نوع الداتا بتاعك.' } },
    { n:'selected', k:'mine', w:{ en:'Your linked signal, read and set by this component.', ar:'الـ linked signal بتاعتك، الـ component ده بيقراها وبيعملها set.' } },
    { n:'toggleOptimistic', k:'pub', as:'tahini', w:{ en:'A public store method.', ar:'ميثود public في الـ store.' } },
    { n:'before', k:'mine', as:'hummus', w:{ en:'A local snapshot for the rollback.', ar:'نسخة محلية عشان الـ rollback.' } },
    { n:'api', k:'mine', w:{ en:'The store’s field holding your API service.', ar:'الـ field بتاع الـ store اللي شايل سيرفس الـ API بتاعك.' } },
    { n:'toasts', k:'mine', as:'molokhia', w:{ en:'The store’s field holding your toast service.', ar:'الـ field بتاع الـ store اللي شايل سيرفس الـ toasts بتاعك.' } },
    { n:'history', k:'mine', w:{ en:'Private signal holding the undo stack.', ar:'signal خاصة شايلة ستاك الـ undo.' } },
    { n:'commit', k:'mine', as:'zucchini', w:{ en:'A private method. Only the store calls it.', ar:'ميثود خاصة. الـ store بس اللي بيناديها.' } },
    { n:'undo', k:'pub', w:{ en:'A public store method.', ar:'ميثود public في الـ store.' } },
    { n:'TodoList', k:'pub', w:{ en:'Your component’s class name.', ar:'اسم كلاس الـ component بتاعك.' } },
    { n:'store', k:'mine', w:{ en:'The component’s field holding the store. Its template reads <code>store.…</code>, still inside the same component.', ar:'الـ field بتاع الـ component اللي شايل الـ store. التمبلت بتاعه بيقرا <code>store.…</code>، وده برضه جوه نفس الـ component.' } },
  ]
}
};
