/* names for the unit / component testing topic.
   n: the name exactly as typed in the code.   k: ng | mine | pub.
   w: what it is, and what has to change with it.   { en, ar }
   re / only / as: see _build/names.mjs.                                  */
export default {
'testing': {
  note: {
    en: 'A test types three kinds of words: the test runner’s (<code>describe</code>, <code>it</code>, <code>expect</code>), Angular’s (<code>TestBed</code>, <code>whenStable</code>) and <b>names from the code under test</b>. Those last ones are orange: rename <code>withVat</code> or an input in the app and the test must follow. The text inside <code>describe(\'…\')</code> and <code>it(\'…\')</code> is just a label.',
    ar: 'التيست بيكتب تلات أنواع كلام: كلام الـ test runner (<code>describe</code> و<code>it</code> و<code>expect</code>)، وكلام أنجولار (<code>TestBed</code> و<code>whenStable</code>)، و<b>أسماء من الكود اللي بتختبره</b>. الأخيرة دي برتقاني: لو غيّرت <code>withVat</code> أو input في التطبيق، التيست لازم يتغير معاه. والنص اللي جوه <code>describe(\'…\')</code> و<code>it(\'…\')</code> مجرد عنوان.'
  },
  names: [
    { n:'describe', k:'ng', re:'(?<![\\w$.-])describe(?=\\()',
      w:{ en:'The test runner’s function (Jasmine, Jest and Vitest all have it) that groups tests. The string is a free label.',
          ar:'function بتاعة الـ test runner (Jasmine وJest وVitest كلهم فيهم) بتجمّع التستات. والنص اللي جواها عنوان براحتك.' } },
    { n:'it', k:'ng', re:'(?<![\\w$.-])it(?=\\()',
      w:{ en:'The test runner’s function for one test. The sentence inside is yours; the word <code>it</code> is not.',
          ar:'function الـ test runner لتيست واحد. الجملة اللي جواها بتاعتك؛ لكن كلمة <code>it</code> لأ.' } },
    { n:'beforeEach', k:'ng', w:{ en:'The test runner’s hook that runs before every test.', ar:'hook بتاع الـ test runner بيشتغل قبل كل تيست.' } },
    { n:'expect', k:'ng', w:{ en:'The test runner’s assertion function.', ar:'function الـ test runner اللي بتتأكد من النتيجة.' } },
    { n:'toBe', k:'ng', w:{ en:'A matcher from the test runner.', ar:'matcher من الـ test runner.' } },
    { n:'toContain', k:'ng', w:{ en:'A matcher from the test runner.', ar:'matcher من الـ test runner.' } },
    { n:'toHaveBeenCalled', k:'ng', w:{ en:'A spy matcher from the test runner.', ar:'matcher للـ spy من الـ test runner.' } },
    { n:'toHaveBeenCalledWith', k:'ng', w:{ en:'A spy matcher that also checks the arguments.', ar:'matcher للـ spy بيتأكد كمان من الـ arguments.' } },
    { n:'jasmine.createSpy', k:'ng',
      w:{ en:'Jasmine’s fake function that remembers its calls (Vitest: <code>vi.fn()</code>). The string you pass is only a label for error messages.',
          ar:'function مزيفة من Jasmine بتفتكر اتنادت إزاي (في Vitest: <code>vi.fn()</code>). والنص اللي بتبعته مجرد اسم بيظهر في رسايل الإيرور.' } },
    { n:'TestBed', k:'ng', w:{ en:'Angular’s testing environment.', ar:'بيئة التستات بتاعة أنجولار.' } },
    { n:'configureTestingModule', k:'ng',
      w:{ en:'The <code>TestBed</code> method that sets up <code>imports</code> and <code>providers</code> for the test.',
          ar:'ميثود <code>TestBed</code> اللي بتجهّز الـ <code>imports</code> والـ <code>providers</code> للتيست.' } },
    { n:'providers', k:'ng', w:{ en:'An option key Angular reads.', ar:'مفتاح إعداد أنجولار بيقراه.' } },
    { n:'useValue', k:'ng', w:{ en:'Part of a provider: “use this object instead”.', ar:'جزء من الـ provider: “استخدم الأوبجكت ده بداله”.' } },
    { n:'createComponent', k:'ng', w:{ en:'The <code>TestBed</code> method that builds a real component for the test.', ar:'ميثود <code>TestBed</code> اللي بتبني component حقيقي للتيست.' } },
    { n:'whenStable', k:'ng',
      w:{ en:'Angular’s “wait until the screen is up to date”. Works with and without zone.js.',
          ar:'بتاعة أنجولار: “استنى لحد ما الشاشة تتحدّث”. بتشتغل بـ zone.js ومن غيره.' } },
    { n:'nativeElement', k:'ng', w:{ en:'The component’s real DOM element.', ar:'الـ element الحقيقي بتاع الـ component في الـ DOM.' } },
    { n:'componentRef', k:'ng', w:{ en:'Angular’s handle on the created component.', ar:'المسكة اللي أنجولار بيديهالك على الـ component اللي اتعمل.' } },
    { n:'setInput', k:'ng',
      w:{ en:'Angular’s way to set an input from a test. The first argument is the input’s name as a string.',
          ar:'طريقة أنجولار إنك تحط قيمة input من التيست. أول argument هو اسم الـ input كـ string.' } },
    { n:'componentInstance', k:'ng', w:{ en:'The component’s class instance, so you can reach its outputs.', ar:'الـ instance بتاع كلاس الـ component، عشان توصل للـ outputs بتاعته.' } },
    { n:'querySelector', k:'ng', w:{ en:'The browser’s DOM search.', ar:'البحث في الـ DOM بتاع المتصفح.' } },
    { n:'textContent', k:'ng', w:{ en:'The browser’s DOM property: all the text inside an element.', ar:'property في الـ DOM بتاعة المتصفح: كل النص اللي جوه الـ element.' } },
    { n:'click', k:'ng', re:'(?<=\\.)click(?=\\()', w:{ en:'The browser’s DOM method that clicks an element.', ar:'ميثود الـ DOM بتاعة المتصفح اللي بتدوس على الـ element.' } },
    { n:'provideHttpClientTesting', k:'ng', w:{ en:'Angular’s fake backend: requests are caught instead of sent.', ar:'الباك إند المزيف بتاع أنجولار: الـ requests بتتمسك بدل ما تتبعت.' } },
    { n:'HttpTestingController', k:'ng',
      w:{ en:'Angular’s controller for that fake backend. <code>expectOne</code>, <code>flush</code> and <code>verify</code> are its methods.',
          ar:'الكنترولر بتاع أنجولار للباك إند المزيف. و<code>expectOne</code> و<code>flush</code> و<code>verify</code> ميثودز بتاعته.' } },
    { n:'expectOne', k:'ng', w:{ en:'A method of <code>HttpTestingController</code>.', ar:'ميثود في <code>HttpTestingController</code>.' } },
    { n:'flush', k:'ng', w:{ en:'A method of the caught request: answer it with this data.', ar:'ميثود في الـ request اللي اتمسك: رد عليه بالداتا دي.' } },
    { n:'verify', k:'ng', w:{ en:'A method of <code>HttpTestingController</code>.', ar:'ميثود في <code>HttpTestingController</code>.' } },

    { n:'Cart', k:'pub', re:'(?<![\\w$\'-])Cart(?![\\w$\'-])',
      w:{ en:'The component class, imported from its own file. The <code>\'Cart\'</code> in <code>describe</code> and <code>\'Cart (1)\'</code> are just text.',
          ar:'كلاس الـ component، متعمله import من الملف بتاعه. و<code>\'Cart\'</code> اللي في <code>describe</code> و<code>\'Cart (1)\'</code> مجرد نص.' } },
    { n:'CartStore', k:'pub',
      w:{ en:'The real service class. The test names it in <code>provide</code> so Angular knows which one to replace.',
          ar:'كلاس الـ service الحقيقي. التيست بيكتبه في <code>provide</code> عشان أنجولار يعرف يستبدل أنهي واحد.' } },
    { n:'items', k:'pub',
      w:{ en:'The fake must copy the real store’s shape: the component reads <code>store.items</code>, so this name must match the real <code>CartStore</code>.',
          ar:'الـ fake لازم ينسخ شكل الـ store الحقيقي: الـ component بيقرا <code>store.items</code>، فالاسم ده لازم يطابق <code>CartStore</code> الحقيقي.' } },
    { n:'add', k:'pub', re:'(?<![\\w$\'-])(?<!button\\.)add(?![\\w$\'-])',
      w:{ en:'Same rule: the component calls <code>store.add()</code>, so the fake needs the same method name. The <code>\'add\'</code> string is just the spy’s label.',
          ar:'نفس القاعدة: الـ component بينادي <code>store.add()</code>، فالـ fake محتاج نفس اسم الميثود. و<code>\'add\'</code> اللي كـ string مجرد اسم للـ spy.' } },
    { n:'.add', k:'pub', re:'(?<=button)\\.add(?=\')', as:'.buy-btn',
      w:{ en:'A CSS class in the <code>Cart</code> template. The test finds the button by it, so rename it in the template and the test together.',
          ar:'CSS class في تمبلت <code>Cart</code>. التيست بيلاقي الزرار بيه، فغيّره في التمبلت والتيست مع بعض.' } },
    { n:'.remove', k:'pub', as:'.trash-btn',
      w:{ en:'A CSS class in the <code>ProductCard</code> template, typed again by the test.', ar:'CSS class في تمبلت <code>ProductCard</code>، والتيست بيكتبه تاني.' } },
    { n:'ProductCard', k:'pub', w:{ en:'The component class, imported from its own file.', ar:'كلاس الـ component، متعمله import من الملف بتاعه.' } },
    { n:'product', k:'pub', re:'(?<=setInput\\(\')product(?=\')',
      w:{ en:'The input’s name, written as a string. It must match the <code>input()</code> in <code>ProductCard</code> exactly, and nothing warns you if it does not.',
          ar:'اسم الـ input مكتوب كـ string. لازم يطابق الـ <code>input()</code> اللي في <code>ProductCard</code> بالظبط، ومحدش هينبهك لو مش مطابق.' } },
    { n:'removed', k:'pub', re:'(?<=\\.)removed(?![\\w$-])', w:{ en:'The output’s name in <code>ProductCard</code>. Rename it there and here.', ar:'اسم الـ output في <code>ProductCard</code>. غيّره هناك وهنا.' } },
    { n:'UserApi', k:'pub', w:{ en:'Your service class, imported from its own file.', ar:'كلاس الـ service بتاعك، متعمله import من الملف بتاعه.' } },
    { n:'load', k:'pub', w:{ en:'A method of <code>UserApi</code>. Rename it there and in the test.', ar:'ميثود في <code>UserApi</code>. غيّرها هناك وفي التيست.' } },
    { n:'withVat', k:'pub', re:'(?<![\\w$\'-])withVat(?![\\w$\'-])',
      w:{ en:'Exported from <code>money.ts</code> and imported by the spec, so both files change. The <code>\'withVat\'</code> in <code>describe</code> is just a label.',
          ar:'متعمله export من <code>money.ts</code> والـ spec بيعمله import، فالملفين بيتغيروا. و<code>\'withVat\'</code> اللي في <code>describe</code> مجرد عنوان.' } },

    { n:'store', k:'mine', re:'(?<![\\w$/.-])store(?![\\w$-])', w:{ en:'The test’s own name for the fake. <code>useValue: store</code> is what connects it.', ar:'الاسم اللي التيست اختاره للـ fake. و<code>useValue: store</code> هو اللي بيربطه.' } },
    { n:'fixture', k:'mine', w:{ en:'A variable name you chose for what <code>createComponent</code> returns.', ar:'اسم متغير انت اخترته للي <code>createComponent</code> بترجعه.' } },
    { n:'f', k:'mine', only:['ts'], w:{ en:'The same thing as <code>fixture</code>, just shorter. Any name works.', ar:'نفس <code>fixture</code> بس أقصر. أي اسم ينفع.' } },
    { n:'emitted', k:'mine', w:{ en:'A variable name you chose.', ar:'اسم متغير انت اخترته.' } },
    { n:'http', k:'mine', re:'(?<![\\w$/-])http(?=[\\s.])',
      w:{ en:'Your variable holding the <code>HttpTestingController</code>. The <code>http</code> in the import path is part of Angular’s package name.',
          ar:'المتغير بتاعك اللي شايل الـ <code>HttpTestingController</code>. و<code>http</code> اللي في مسار الـ import جزء من اسم باكدج أنجولار.' } },
    { n:'amount', k:'mine', w:{ en:'A parameter name. Callers pass by position, so it is private.', ar:'اسم parameter. اللي بينادي بيبعت حسب الترتيب، فهو خاص.' } },
  ]
}
};
